### PR TITLE
Comdb2RLE + hintz

### PR DESCRIPTION
**Pull request by akshatsikarwar**

### CODE REVIEW

**Comment by riverszhang89** [comment]
roborivers runs out of disk space. However some of them were really failures.

**Comment by akshatsikarwar** [comment]
Yes - I'm looking at the cores.

**Comment by riverszhang89** [comment]
Holy moly - docker images are taking up all the space.

**Comment by mponomar** [comment]
There should only be 3.  They get deleted before the test starts and after it finishes (successfully).

**Comment by riverszhang89** [comment]
@mponomar `docker rm` only deletes the container.

`docker build -t smoketest-deb` creates an untagged image above `smoketest-deb`. The untagged image can only be deleted by `docker rmi`.

For example, I have these images.

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
smoketest-inst      latest              55c760e66776        44 minutes ago      729MB
smoketest-rpm       latest              428be688d0e3        45 minutes ago      895MB
smoketest-deb       latest              d8be804c5671        About an hour ago   611MB
ubuntu              latest              ebcd9d4fca80        2 weeks ago         118MB
centos              latest              8140d0c64310        2 weeks ago         193MB
```

After smoke test, I now have:
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
smoketest-inst      latest              55c760e66776        44 minutes ago      729MB
smoketest-rpm       latest              428be688d0e3        45 minutes ago      895MB
smoketest-deb       latest              d8be804c5671        About an hour ago   611MB
<none>              <none>              08273fadc845        3 hours ago         729MB
<none>              <none>              bd5819ddfc59        3 hours ago         894MB
<none>              <none>              45956f652954        3 hours ago         619MB
ubuntu              latest              ebcd9d4fca80        2 weeks ago         118MB
centos              latest              8140d0c64310        2 weeks ago         193MB
```

These 3 untagged images must be removed by `docker rmi`:
```
$ docker rmi $(docker images | grep "^<none>" | awk "{print $3}") >/dev/null 2>&1
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
smoketest-inst      latest              55c760e66776        About an hour ago   729MB
smoketest-rpm       latest              428be688d0e3        About an hour ago   895MB
smoketest-deb       latest              d8be804c5671        About an hour ago   611MB
ubuntu              latest              ebcd9d4fca80        2 weeks ago         118MB
centos              latest              8140d0c64310        2 weeks ago         193MB
```

**Pull request merged**
