### PR TITLE
Cdb2 setinfo

### PR DESCRIPTION
**Pull request by markhannum**
Accept argv0 from cdb2api

### CODE REVIEW

**Comment by markhannum** [comment]
sp crashed with this stack:
#0  0x00000000008ac220 in mspace_free (msp=0x64f3d50, mem=0x65445f0) at /bb/comdb2a/roborivers/branches/master/dlmalloc/dlmalloc.c:5018
#1  0x000000000089c51f in comdb2_free_int (cm=0x635d110, ptr=0x6544600) at /bb/comdb2a/roborivers/branches/master/mem/mem.c:774
#2  0x000000000089c72a in comdb2_free (ptr=0x6544600) at /bb/comdb2a/roborivers/branches/master/mem/mem.c:837
#3  0x000000000059ac51 in sql_mem_free (mem=0x6544600) at /bb/comdb2a/roborivers/branches/master/db/sqlinterfaces.c:1417
#4  0x00000000008fbc83 in sqlite3_free (p=0x6544600) at /bb/comdb2a/roborivers/branches/master/sqlite/malloc.c:449
#5  0x00000000008fbd23 in sqlite3DbFree (db=0x64f4140, p=0x6544600) at /bb/comdb2a/roborivers/branches/master/sqlite/malloc.c:489
#6  0x0000000000940b86 in releaseMemArray (p=0x64f9358, N=5) at /bb/comdb2a/roborivers/branches/master/sqlite/vdbeaux.c:1593
#7  0x0000000000941fa9 in closeAllCursors (p=0x65064a8) at /bb/comdb2a/roborivers/branches/master/sqlite/vdbeaux.c:2155
#8  0x0000000000942e97 in sqlite3VdbeHalt (p=0x65064a8) at /bb/comdb2a/roborivers/branches/master/sqlite/vdbeaux.c:2681
#9  0x000000000092b666 in sqlite3VdbeExec (p=0x65064a8) at /bb/comdb2a/roborivers/branches/master/sqlite/vdbe.c:1281
#10 0x000000000093b4da in sqlite3Step (p=0x65064a8) at /bb/comdb2a/roborivers/branches/master/sqlite/vdbeapi.c:756
#11 0x000000000093b721 in sqlite3_step (pStmt=0x65064a8) at /bb/comdb2a/roborivers/branches/master/sqlite/vdbeapi.c:825
#12 0x000000000086b209 in dbstmt_exec (lua=0x68a33a0) at /bb/comdb2a/roborivers/branches/master/lua/sp.c:3302
#13 0x000000000087d97e in luaD_precall (L=0x68a33a0, func=0x6769318, nresults=0) at /bb/comdb2a/roborivers/branches/master/lua/ldo.c:327
#14 0x0000000000893869 in luaV_execute (L=0x68a33a0, nexeccalls=1) at /bb/comdb2a/roborivers/branches/master/lua/lvm.c:653
#15 0x000000000087dc23 in luaD_call (L=0x68a33a0, func=0x68a37a0, nResults=-1) at /bb/comdb2a/roborivers/branches/master/lua/ldo.c:385
#16 0x000000000087893d in f_call (L=0x68a33a0, ud=0x7fbd3086c7b0) at /bb/comdb2a/roborivers/branches/master/lua/lapi.c:800
#17 0x000000000087cc10 in luaD_rawrunprotected (L=0x68a33a0, f=0x878908 <f_call>, ud=0x7fbd3086c7b0) at /bb/comdb2a/roborivers/branches/master/lua/ldo.c:117
#18 0x000000000087e019 in luaD_pcall (L=0x68a33a0, func=0x878908 <f_call>, u=0x7fbd3086c7b0, old_top=16, ef=0)
    at /bb/comdb2a/roborivers/branches/master/lua/ldo.c:471
#19 0x00000000008789ec in lua_pcall (L=0x68a33a0, nargs=3, nresults=-1, errfunc=0) at /bb/comdb2a/roborivers/branches/master/lua/lapi.c:821
#20 0x00000000008730d8 in run_sp_int (clnt=0x7fbd33e95ed0, argcnt=3, err=0x7fbd3086c8a0) at /bb/comdb2a/roborivers/branches/master/lua/sp.c:5907
#21 0x00000000008731ee in run_sp (clnt=0x7fbd33e95ed0, argcnt=3, err=0x7fbd3086c8a0) at /bb/comdb2a/roborivers/branches/master/lua/sp.c:5932
#22 0x0000000000874be7 in exec_thread_int (thd=0x7fbd3086c970, clnt=0x7fbd33e95ed0) at /bb/comdb2a/roborivers/branches/master/lua/sp.c:6494
#23 0x0000000000875ba3 in exec_thread (thd=0x7fbd3086c970, clnt=0x7fbd33e95ed0) at /bb/comdb2a/roborivers/branches/master/lua/sp.c:6792
#24 0x00000000005a67ab in sqlengine_work_lua_thread (thddata=0x7fbd3086c970, work=0x7fbd33e95ed0)
    at /bb/comdb2a/roborivers/branches/master/db/sqlinterfaces.c:5919
#25 0x00000000005a6de3 in sqlengine_work_appsock_pp (pool=0x61cd010, work=0x7fbd33e95ed0, thddata=0x7fbd3086c970, op=0)
    at /bb/comdb2a/roborivers/branches/master/db/sqlinterfaces.c:6077
#26 0x00000000006fc862 in thdpool_thd (voidarg=0x7fbd43d831b0) at /bb/comdb2a/roborivers/branches/master/bb/thdpool.c:708
#27 0x00000000006e3399 in thr_func (arg=0x61e5f88) at /bb/comdb2a/roborivers/branches/master/bb/comdb2_pthread_create.c:235

**Comment by riverszhang89** [comment]
I have seen sp test crashes in malloc:

- http://comdb2.s3-website-us-east-1.amazonaws.com/tests/1efa8e83cb178bb26a3c6058e48377b5007c816d/detail.txt

- http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d5539ec05de4dd564038e9c3d10d2e36ad5c866d/detail.txt

**Comment by akshatsikarwar** [comment]
we haz bug

**Comment by markhannum** [comment]
Closing - i have a new pr for a "cleaner" branch "cdb2_setinfo_clean".

**Pull request closed without merging**
