### PR TITLE
Give correct user if hndl is used after auth error 8.0

### PR DESCRIPTION
**Pull request by mohitkhullar**
https://github.com/bloomberg/comdb2/pull/4928 -> 8.0

### CODE REVIEW

**Review by mponomar — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>245/564 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fdb_compare_rte_connect_generated<br>fdb_compare<br>incoh_remsql<br>incoh_remsql_rte_connect_generated<br>writes_remsql_names_rte_connect_generated<br>writes_remsql_names_partial_index_off_generated<br>writes_remsql_names_fdbpushredirect_generated<br>writes_remsql_names_fdbpush_generated<br>writes_remsql_names_negativerowid_generated<br>writes_remsql_names</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>250/564 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts_logicalsc_generated [setup failure]<br>fdb_compare_rte_connect_generated<br>fdb_compare<br>incoh_remsql<br>incoh_remsql_rte_connect_generated<br>writes_remsql_names_rte_connect_generated<br>writes_remsql_names_partial_index_off_generated<br>writes_remsql_names_fdbpushredirect_generated<br>writes_remsql_names_fdbpush_generated<br>writes_remsql_names_negativerowid_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>246/564 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_newuniq_logicalsc_generated [setup failure]<br>writes_remsql_names_negativerowid_generated [setup failure]<br>fdb_compare_rte_connect_generated<br>fdb_compare<br>incoh_remsql_rte_connect_generated<br>incoh_remsql<br>writes_remsql_names_rte_connect_generated<br>writes_remsql_names_partial_index_off_generated<br>writes_remsql_names<br>writes_remsql_names_fdbpushredirect_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>255/564 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>scupdates_logicalsc_generated [setup failure]<br>fdb_compare_rte_connect_generated<br>fdb_compare<br>incoh_remsql_rte_connect_generated<br>incoh_remsql<br>writes_remsql_names_rte_connect_generated<br>writes_remsql_names_partial_index_off_generated<br>writes_remsql_names_fdbpushredirect_generated<br>writes_remsql_names_negativerowid_generated<br>writes_remsql_names</p>

**Pull request closed without merging**
