### PR TITLE
fix ioerror during remsql when dohsql is used

### PR DESCRIPTION
**Pull request by dorinhogea**
Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

Use ioerror test with dohsql + remsql; fixes for the retry and the locking when shard processing fails due to remote I/O failure.

### CODE REVIEW

**Comment by dorinhogea** [comment]
It is a different runit

**Comment by riverszhang89** [comment]
The same runit will work, no? [The part you deleted ](https://github.com/bloomberg/comdb2/blob/master/tests/simple_remsql.test/runit#L31-L78) handles whitelist testopts only and does not affect other test scenarios in any way.

**Comment by dorinhogea** [comment]
simple_remsql test checks the output results.  This tests random I/O errors and makes sure that we handle errors gracefully.  Output is variable

**Comment by riverszhang89** [comment]
Thanks for clarifying.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/979fe72/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/368 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_async_constraints_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/979fe72/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/979fe72/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2446'>Resubmit</a></p>

**Review by mponomar — APPROVED** [review]
LGTM.  There's a couple of files here that you probably don't want to keep in the tests, eg:
tests/ioerror_remsql.test/repro.txt
tests/ioerror_remsql.test/runtest.sh
tests/ioerror_remsql.test/setenv.sh

would be great if you got rid of them.  Otherwise looks good to go.

**Comment by dorinhogea** [comment]
Thank you Mike

**Pull request merged**
