### PR TITLE
Fix error message when upsert is not supported

### PR DESCRIPTION
**Pull request by nirbhayc**
Comdb2 reported 'unknown error' for INSERT OR IGNORE when upsert wasn't enabled. Also update docs and tests for INSERT OR (IGNORE|REPLACE) syntax.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

### CODE REVIEW

**Comment by adizaimi** [comment]
We don't have a case in our testsuite where we would print 'UPSERT not enabled', correct? We always have that enabled.
This looks good.

**Comment by nirbhayc** [comment]
@adizaimi added some tests, thanks for looking!

**Comment by nirbhayc** [comment]
Cherry-picked to 7.0

**Comment by nirbhayc** [comment]
Thank you @adizaimi !

**Pull request merged**
