### PR TITLE
Fix crash caused by uninitialized Mem.tz

### PR DESCRIPTION
**Pull request by riverszhang89**
See tests/datetime.test/t16.sql for a reproducer.

(DRQS 165247061)

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
```

**Review by mistachkin — APPROVED** [review]
Looks good.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/401 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated<br>simple_timepart<br>basic_nogenid48_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/24483d73/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/24483d73/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2739'>Resubmit</a></p>

**Comment by riverszhang89** [comment]
@mistachkin Thanks for the review, Joe!

**Pull request merged**
