### PR TITLE
Allow client to toggle log deletion

### PR DESCRIPTION
**Pull request by morgando**
The new bulk import implementation will select from `comdb2_files` multiple times to get all of the files needed to create a partial clone of a database. Log deletion needs to be disabled over these calls: If the first call grabs btree files and then a log file required to run recovery is deleted before the second call grabs the log files, then recovery will fail when the clone comes up. Allowing the client to disable log deletion allows the them to safely run multiple queries against `comdb2_files`.

Log deletion is disabled when a client runs `set logdelete off`. Multiple clients can disable log deletion at the same time. If log deletion has been disabled by one or more clients, then it will be re-enabled when each of the clients that has disabled it either
1) re-enables it explicitly (by running `set logdelete on`)
2) ends its session (either naturally or via a crash)

I did not document this feature outside of a code comment since it currently has no utility for clients outside of the system and could be dangerous if misused.

### CODE REVIEW

**Review by mponomar — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/585 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_multiddl_generated<br>timepart_trunc<br>snap_ha_retry_newsi_generated</p>

**Review by mponomar — DISMISSED** [review]

**Review by LiSodium — DISMISSED** [review]
lgtm

**Review by LiSodium — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/585 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>simple_timepart_reptimeout_generated [setup failure]<br>unionpar_maxqueue [setup failure]<br>verify_error_partial_index_off_generated [setup failure]<br>snap_ha_retry_newsi_generated<br>clnt_logdel_toggle<br>auth<br>disttxn</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/585 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>verify_error [setup failure]<br>timepart_trunc_multiddl_generated<br>snap_ha_retry_newsi_generated</p>

**Review by mponomar — APPROVED** [review]

**Review by LiSodium — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/585 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sicomplex3 [setup failure]<br>sc_lotsoftables [setup failure]<br>sc_transactional_rowlocks_generated<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated<br>truncatesc_offline_generated<br>ssl_remsql_fdbpush_generated</p>

**Comment by morgando** [comment]
`cdb2test   Oct 15 17:01:15 2024  in-comdb2db clnt_logdel.R20241015.8`

**Pull request merged**
