### PR TITLE
Fix cascading updates in self-referencing FK constraints

### PR DESCRIPTION
**Pull request by nirbhayc**
.

### CODE REVIEW

**Comment by nirbhayc** [comment]
master & replicant throw different error messages:
```diff
--- ./common/c1/db/ddl_no_csc2.test/t06_fk.expected     2019-10-17 16:34:26.770383341 -0400
+++ ./common/c1/db/ddl_no_csc2.test/t06_fk.output       2019-10-17 16:35:17.258319078 -0400
@@ -347,7 +347,7 @@
 (i=1, j=2)
 (i=1, j=3)
 (i=1, j=4)
-[update t2 set i=2 where i=1] failed with rc 3 verify key constraint cannot resolve constraint table 't1' index '$KEY_877B2989'
+[update t2 set i=2 where i=1] failed with rc 3 verify key constraint cannot resolve constraint table 't2' key '$KEY_1E994F88' -> table 't1' index '0' key '$KEY_877B2989'
 (rows updated=1)
 (i=2, j=1)
 (i=2, j=2)
```

**Comment by nirbhayc** [comment]
Benchmark test:
```sql
drop table t2;
drop table t1;
create table t1(i int index, j int)$$
create table t2(i int index, j int, foreign key(i) references t1(i) on delete cascade on update cascade)$$
set maxtransize 1000000
insert into t1 values(1,1);
insert into t2 select 1, value from generate_series(1, 100000);
update t1 set i=2 where i=1
```
**branch: nirbhayc:comdb2-fk-self-ref (without genid hash)**
$ time cdb2sql nctdb local "update t1 set i=2 where i=1"
real    0m7.755s
real    0m8.597s
real    0m10.005s

**branch: nirbhayc:comdb2-fk-self-ref (with genid hash)**
real    0m7.468s
real    0m6.421s
real    0m6.272s

**branch: master**
real    0m7.473s
real    0m7.179s
real    0m8.039s

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/96520f6/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/380 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_constraints_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/96520f6/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/96520f6/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=1860'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/43c918b/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/380 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ruleset_no_fp_generated [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/43c918b/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/43c918b/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=1860'>Resubmit</a></p>

**Review by mponomar — COMMENTED** [review]
Talked to Nirbhay - suggested we cache the genids on the first lookup, and consult the cache instead.  Otherwise we end up scanning the constraints tables on every update/delete with a constraint.  Don't have metrics, but I'm afraid it can get out of hand fo larger transactions.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ccf5740/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ccf5740/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ccf5740/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=1860'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ccf5740/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/381 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>tunables</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ccf5740/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ccf5740/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=1860'>Resubmit</a></p>

**Comment by nirbhayc** [comment]
Hashing genids definitely shows some improved performance.

prepare_small.sh
```
/bb/bin/cdb2sql nctdb local "drop table if exists t2"
/bb/bin/cdb2sql nctdb local "drop table if exists t1"
/bb/bin/cdb2sql nctdb local "create table t1(i int index)"
/bb/bin/cdb2sql nctdb local "create table t2(i int index, foreign key(i) references t1(i) on delete cascade on update cascade)"
/bb/bin/cdb2sql nctdb local "insert into t1 values(1)"
/bb/bin/cdb2sql nctdb local "insert into t2 select 1 from generate_series(1, 10000)"
```

prepare_large.sh
```
/bb/bin/cdb2sql nctdb local "drop table if exists t2"
/bb/bin/cdb2sql nctdb local "drop table if exists t1"
/bb/bin/cdb2sql nctdb local "create table t1(i int index)"
/bb/bin/cdb2sql nctdb local "create table t2(i int index, foreign key(i) references t1(i) on delete cascade on update cascade)"
for i in `seq 1 100`; do
    /bb/bin/cdb2sql nctdb local "insert into t1 values($i)"
    /bb/bin/cdb2sql nctdb local "insert into t2 select $i from generate_series(1, 10000)"
done
```

repeat.sh
```
for i in `seq 1 $1`; do
    /bb/bin/cdb2sql nctdb local "update t1 set i=i+1 where i=$i"
    echo $i
done
```

master branch:
```
bash-4.2$ time ./prepare_small.sh > /dev/null

real    0m0.183s
user    0m0.006s
sys     0m0.006s
bash-4.2$ time ./repeat.sh 100 > /dev/null

real    0m20.944s
user    0m0.096s
sys     0m0.098s
bash-4.2$ time ./prepare_large.sh > /dev/null

real    0m16.116s
user    0m0.129s
sys     0m0.233s
bash-4.2$ time ./repeat.sh 10 > /dev/null

real    0m12.915s
user    0m0.009s
sys     0m0.013s
```

pr branch (without hashed genids):
```
bash-4.2$ time ./prepare_small.sh > /dev/null

real    0m0.189s
user    0m0.006s
sys     0m0.006s
bash-4.2$ time ./repeat.sh 100 > /dev/null

real    0m21.595s
user    0m0.090s
sys     0m0.104s
bash-4.2$ time ./prepare_large.sh > /dev/null

real    0m16.539s
user    0m0.157s
sys     0m0.217s
bash-4.2$ time ./repeat.sh 10 > /dev/null

real    0m13.377s
user    0m0.011s
sys     0m0.012s

```

PR branch (with hashed genids)
```
bash-4.2$ time ./prepare_small.sh > /dev/null

real    0m0.184s
user    0m0.004s
sys     0m0.008s
bash-4.2$ time ./repeat.sh 100 > /dev/null

real    0m20.344s
user    0m0.076s
sys     0m0.107s
bash-4.2$ time ./prepare_large.sh > /dev/null

real    0m16.134s
user    0m0.178s
sys     0m0.198s
bash-4.2$ time ./repeat.sh 10 > /dev/null

real    0m12.828s
user    0m0.009s
sys     0m0.013s
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9b15e09/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/381 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sql_func_mem_leak</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9b15e09/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9b15e09/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=1860'>Resubmit</a></p>

**Comment by nirbhayc** [comment]
repeat2.sh
```
for i in `seq 1 $1`; do
    /bb/bin/cdb2sql nctdb local "delete from t1 where i=$i"
    echo $i
done
```

master branch:
```
bash-4.2$ time ./prepare_small.sh > /dev/null
real    0m0.183s
user    0m0.006s
sys     0m0.005s
bash-4.2$ time ./repeat2.sh 100 > /dev/null
real    0m0.340s
user    0m0.049s
sys     0m0.112s

bash-4.2$ time ./prepare_large.sh > /dev/null
real    0m16.216s
user    0m0.138s
sys     0m0.227s
bash-4.2$ time ./repeat2.sh 100 > /dev/null
real    0m17.936s
user    0m0.076s
sys     0m0.107s
```

PR branch:
```
bash-4.2$ time ./prepare_small.sh > /dev/null
real    0m0.183s
user    0m0.006s
sys     0m0.004s
bash-4.2$ time ./repeat2.sh 100 > /dev/null
real    0m0.345s
user    0m0.055s
sys     0m0.105s

bash-4.2$ time ./prepare_large.sh > /dev/null
real    0m16.152s
user    0m0.163s
sys     0m0.210s
bash-4.2$ time ./repeat2.sh 100 > /dev/null
real    0m18.283s
user    0m0.070s
sys     0m0.125s
```

**Review by mponomar — APPROVED** [review]
Looks good.  Update case is improved with hash, no noticeable regression in deletes.

**Pull request merged**
