### PR TITLE
net mem

### PR DESCRIPTION
**Pull request by akshatsikarwar**
Remove `akq`.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
.

**Review by roborivers — CHANGES_REQUESTED** [review]
.

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/481 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>sc_transactional_rowlocks_generated<br>phys_rep_tiered<br>queuedb_rollover<br>prepare</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/482 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>sc_truncate<br>queuedb_rollover<br>sc_timepart_logicalsc_generated</p>

**Review by riverszhang89 — APPROVED** [review]

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/482 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>sc_transactional_rowlocks_generated<br>queuedb_rollover<br>sc_timepart_logicalsc_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/482 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>sc_timepart_logicalsc_generated<br>prepare</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/484 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sc_timepart</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/485 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>queuedb_rollover_noroll1_generated<br>lostwrite<br>sc_datacopy_logicalsc_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/485 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>sc_truncate<br>incoh_remsql<br>sc_transactional_rowlocks_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net_evbuffer.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/485 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>sc_transactional_rowlocks_generated<br>queuedb_rollover</p>

**Review by mponomar — APPROVED** [review]

**Pull request merged**
