### PR TITLE
Comment out CTAS syntax in the parser.

### PR DESCRIPTION
**Pull request by nirbhayc**

### CODE REVIEW

**Comment by dorinhogea** [comment]
are there any other unsupported SQLite syntax we want to block?

**Comment by nirbhayc** [comment]
> are there any other unsupported SQLite syntax we want to block?

None, I think. I have already removed/disabled quite a few over time. (grep for COMDB2_UNSUPPORTED)

**Comment by dorinhogea** [comment]
This looks good, thank you

**Comment by nirbhayc** [comment]
@dorinhogea Thank you.

**Pull request merged**
