### PR TITLE
Better fix for the trigger issue

### PR DESCRIPTION
**Pull request by riverszhang89**
(DRQS 169791301)

### CODE REVIEW

**Review by akshatsikarwar — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>11/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>sc_resume<br>sc_truncate_lockorder_generated<br>sc_truncate<br>sql_datetime_interval_arithmetic_leak<br>phys_rep<br>trigger<br>ignore_bad_table<br>socksql_master_swings<br>load_cache</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>socksql_master_swings<br>sc_truncate<br>siasof<br>phys_rep<br>trigger<br>ignore_bad_table<br>load_cache_autocache_generated<br>tunables<br>sc_downgrade</p>

**Comment by riverszhang89** [comment]
Looks like it doesn't pass the trigger test. Looking at it now.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_downgrade [core dumped]<br>socksql_master_swings<br>sc_truncate<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>sc_downgrade</p>

**Pull request closed without merging**
