### PR TITLE
{172584364}: Honoring gbl_ssl_allow_remsql

### PR DESCRIPTION
**Pull request by riverszhang89**
This gives us an option to disable remote-sql over SSL.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/484 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>phys_rep<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>transchunk_manyins</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/484 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>phys_rep_tiered<br>sc_timepart_logicalsc_generated<br>op_makerecord</p>

**Review by dorinhogea — APPROVED** [review]
This looks good to me! Thank you!

**Comment by riverszhang89** [comment]
@dorinhogea Thanks for the review, Dorin!

**Pull request merged**
