### PR TITLE
Do not keep views lock for the duration of a serial tpt schema change.

### PR DESCRIPTION
**Pull request by dorinhogea**
This is a rework of https://github.com/bloomberg/comdb2/pull/4472 for main branch.  It is more aggressive in releasing the view lock for every shard schema change.  

Re: 175478973

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/555 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>sc_transactional_rowlocks_generated<br>sc_downgrade<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/555 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_resume_logicalsc_generated<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>sc_downgrade<br>truncatesc_offline_generated</p>

**Comment by dorinhogea** [comment]
cdb2test   Jun 10 10:31:08 2024  in-comdb2db asyncserialtptm.R20240610.1

**Review by mponomar — APPROVED** [review]

**Comment by dorinhogea** [comment]
@mponomar

**Pull request merged**
