### PR TITLE
cdb2sql: @repeat command

### PR DESCRIPTION
**Pull request by nirbhayc**
The command can be used to repeatedly execute an SQL query via command prompt:
```
nctdb> select count(*) from t1 where i=1;
(count(*)=100000)
[select count(*) from t1 where i=1] rc 0

nctdb> @repeat 100
Repeating every query 100 times
[@repeat 100] rc 0

nctdb> @time
Timing mode ON

nctdb> @bind CDB2_INTEGER i 1

nctdb> select * from t1 where i=@i;
executing: [************************************************************] 100%
summary:
  total prep time  74 ms
  total run time   54381 ms
```
Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/94cc100c/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/94cc100c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/94cc100c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2663'>Resubmit</a></p>

**Comment by riverszhang89** [comment]
I'd prefer the word `"repeat"` instead of `"benchmark"`. I'd also take out the timing part as well, as it can be turned on via `"@time"`. It probably doesn't handle named parameters very well - `cdb2_clearbindings` is called on each execution therefore you'd get an error from the 2nd execution onward.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/064cb089/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/064cb089/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/064cb089/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2663'>Resubmit</a></p>

**Review by roborivers — COMMENTED** [review]
<p>Sysbench Transactions Per Second (commit: 064cb089):</p>

<pre lang=diff>
@@ sysbench/bulk_insert @@
+8.52%
@@ sysbench/select_random_ranges @@
+10.75%
@@ sysbench/oltp_read_only @@
+16.01%
@@ sysbench/oltp_point_select @@
+7.92%
@@ sysbench/oltp_update_non_index @@
+7.49%
@@ sysbench/oltp_update_index @@
+6.74%
</pre>

**Review by riverszhang89 — APPROVED** [review]

**Comment by nirbhayc** [comment]
Thank you @riverszhang89!

**Pull request merged**
