### PR TITLE
Fix max col name length off by 1 err

### PR DESCRIPTION
**Pull request by chands10**
8.0 https://github.com/bloomberg/comdb2/pull/4843

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/560 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_lotsoftables [setup failure]<br>sc_inserts [setup failure]<br>vutf8_dbstore_off_osql_odh_blob_generated [setup failure]<br>sc_truncate<br>sc_resume2<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/561 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_lotsoftables [setup failure]<br>incoh_remsql_rte_connect_generated [setup failure]<br>autoanalyze [setup failure]<br>writes_remsql_names_negativerowid_generated [setup failure]<br>sc_resume2<br>truncatesc_offline_generated</p>

**Comment by chands10** [comment]
in-comdb2db max_col_name_fix_8.0.R20241202.7

**Review by akshatsikarwar — APPROVED** [review]

**Pull request merged**
