### PR TITLE
Remove support for non-WITH_SSL build

### PR DESCRIPTION
**Pull request by riverszhang89**
It makes very little sense to continue supporting non-WITH_SSL build, as we already depend on OpenSSL for encryption, user authentication, etc. The patch removes all non-WITH_SSL code. Doing so will also simplify future SSL changes.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/410 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>genid48 [setup core dumped]<br>emit_timeout [setup core dumped]<br>logfill [core dumped]<br>sc_constraints<br>sc_constraints_logicalsc_generated<br>sc_resume_logicalsc_generated<br>comdb2sys_pagesize_generated<br>comdb2sys<br>comdb2sys_queueodh_generated<br>queueing_sql</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>selectv_rcode<br>sc_timepart<br>reorder_inserts_noreorder_generated</p>

**Review by chands10 — APPROVED** [review]

**Comment by riverszhang89** [comment]
@chands10 Thanks for the review!

**Pull request merged**
