### PR TITLE
Add integration tier

### PR DESCRIPTION
**Pull request by mohitkhullar**
Signed-off-by: mohitkhullar <mkhullar1@bloomberg.net>

### CODE REVIEW

**Review by nirbhayc — DISMISSED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/459 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_truncate<br>selectv_rcode<br>weighted_standing_queue<br>selectv_deadlock<br>phys_rep</p>

**Review by nirbhayc — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/459 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>timepart_trunc<br>phys_rep</p>

**Comment by mohitkhullar** [comment]
Thanks

**Pull request merged**
