### PR TITLE
Fix memory leak for fastsql queries with hints

### PR DESCRIPTION
**Pull request by riverszhang89**
Fix memory leak for fastsql queries with hints (e.g., `SELECT /*+ RUNCOMDB2SQL <hint> */ 1`), when statement caching is enabled.

(DRQS 165542478)

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/96e20be8/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill [core dumped]<br>simple_timepart_reptimeout_generated<br>sc_timepart<br>simple_timepart<br>datetime</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/96e20be8/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/96e20be8/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2768'>Resubmit</a></p>

**Review by mohitkhullar — APPROVED** [review]
Thanks, looks good

**Comment by riverszhang89** [comment]
@mohitkhullar Thank you for the review!

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>constraints_noreorder_generated<br>simple_timepart_reptimeout_generated<br>sc_timepart<br>simple_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/cbed0e01/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/cbed0e01/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2768'>Resubmit</a></p>

**Pull request merged**
