### PR TITLE
Pagesize: apply options in the lrl file for db filesizes

### PR DESCRIPTION
**Pull request by adizaimi**
* Have `pagesizedta` not be ignored for dta files.
* Add `pagesizeblob` option to set same for blobs.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

### CODE REVIEW

**Review by markhannum — APPROVED** [review]
Awesome - looks great!

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a66dc65f/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a66dc65f/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/395 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a66dc65f/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/a66dc65f/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2640'>Resubmit</a></p>

**Comment by adizaimi** [comment]
log fill seems to timeout sometimes because it waits for coherent cluster:
04:40:43> Fri Sep 11 04:40:43 EDT 2020 waiting for logfill19667 cluster to become coherent
04:40:43> + sleep 1
Duration 989 seconds
Test should really take no more than 3 min.

**Comment by adizaimi** [comment]
Thanks Mark!

**Pull request merged**
