### PR TITLE
Merge table feature

### PR DESCRIPTION
**Pull request by dorinhogea**
New syntax:

CREATE TABLE ... MERGE ...

Example:

create table t(a int, b int);
insert into t values (1,10), (2,20)
create table t2(a int) merge t
select * from t2
(a=1)
(a=2)

NOTE: table t is dropped atomically as part of the merge

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/434 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>sc_truncate<br>socksql_master_swings<br>auth_twofiles_generated<br>auth_queueodh_generated<br>auth<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys<br>sc_downgrade</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/434 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>selectv_rcode<br>socksql_master_swings</p>

**Comment by dorinhogea** [comment]
The rules of schema change alter applies. In your example, you drop table column 'a' and add new column 'b'.
Nothing changes there, the subsystem is not touched.

**Comment by mponomar** [comment]
Sure.  I'm saying maybe we should only allow merges if the schema matches, because people are going to find the above behavior surprising.  I understand what happens to the data.

**Review by mponomar — APPROVED** [review]

**Comment by dorinhogea** [comment]
thanks Mike.  We can review the compatibility old/new table rules in a separate PR

**Pull request merged**
