### PR TITLE
reqlog: Cherry-pick fixes from 7.0 branch

### PR DESCRIPTION
**Pull request by nirbhayc**
Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/newsql/newsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/newsql/newsql_sbuf.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>selectv_rcode_disable_svonly_nop_generated<br>ignore_bad_table<br>load_cache_autocache_generated<br>upsert</p>

**Review by markhannum — APPROVED** [review]
Good to merge!

**Comment by nirbhayc** [comment]
Thank you Mark!

**Pull request merged**
