### PR TITLE
do not leak unlinked tag schema

### PR DESCRIPTION
**Pull request by dorinhogea**
Simplicity is bliss

### CODE REVIEW

**Comment by dorinhogea** [comment]
The leak ref, is about this https://github.com/bloomberg/comdb2/blob/11569ac3a935ab773beaad86c6c56e4150ad867e/db/tag.c#L1547
If we recreate a client tag during cloning, the old tag schema is unlinked but not deleted.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by riverszhang89 — APPROVED** [review]

**Comment by dorinhogea** [comment]
Thank you Rivers!

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>485/485 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>maxtable [setup failure]<br>truncatesc [setup failure]<br>incremental_backup_load [setup failure]<br>systable_locking [setup failure]<br>verify_writes [setup failure]<br>incrementalcopy [setup failure]<br>cldeadlock [setup failure]<br>odh_blobs [setup failure]<br>sirace [setup failure]<br>incremental_backup_usenames [setup failure]</p>

**Pull request merged**
