### PR TITLE
Fail on init errors 8.0

### PR DESCRIPTION
**Pull request by mponomar**

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by riverszhang89 — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_repeated_updates_logicalsc_generated [setup failure]<br>sc_repeated_updates [setup failure]<br>lock_maxid [setup failure]<br>selectv_timepart [setup failure]<br>drop_tblnum [setup failure]<br>queuedb_rollover_noroll1_generated<br>tunables<br>truncatesc_offline_generated<br>truncatesc_ufid_on_generated</p>

**Comment by mponomar** [comment]
cdb2test   Mar 27 11:02:14 2024  in-comdb2db fail-on-init-errors-8.0.R20240327.2

**Comment by akshatsikarwar** [comment]
Do robor tests need fixing?

**Pull request merged**
