### PR TITLE
Simplify SSL session cache code

### PR DESCRIPTION
**Pull request by riverszhang89**
The patch changes the per-node SSL session cache in the client library to a per-cluster session cache. Nodes within the same cluster usually share a common SSL certificate, hence keeping a per-node session cache may be an overkill. Using a per-cluster session cache also means simpler code, that we need not to deal with memory allocation and edge cases such as migration. And perhaps most importantly, a per-cluster session cache doesn't need an extra dbinfo query to the database to figure out cluster nodes, therefore can co-exist with the skip-dbinfo optimization.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/451 tests failed</b> &#x26A0;.</p>

**Review by mohitkhullar — APPROVED** [review]
looks good

**Comment by riverszhang89** [comment]
@mohitkhullar Thanks for the review!

**Pull request merged**
