### PR TITLE
sp: SQL stmt introspection

### PR DESCRIPTION
**Pull request by akshatsikarwar**

### CODE REVIEW

**Comment by akshatsikarwar** [comment]
> ```diff
> @@ sysbench/oltp_read_write @@
> -17.34%
> ```

@nirbhayc What gives?

**Comment by adizaimi** [comment]
You merged or branched from master after my pr was checkedin.

**Comment by nirbhayc** [comment]
right.. https://github.com/bloomberg/comdb2/pull/1810 wasn't merged to the master.

**Pull request merged**
