### PR TITLE
Reduce time required to run queuedb_rollover by disabling the 'concurrency stress' portion.

### PR DESCRIPTION
**Pull request by mistachkin**
Also, add the 'queuedb_rollover_extended' test, which performs the 'concurrency stress' portion of the previous test.

Signed-off-by: mistachkin <joe@mistachkin.com>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/396 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>sc_truncate_lockorder_generated [core dumped]<br>logfill<br>queuedb_rollover<br>queuedb_rollover_noroll1_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b29d8db9/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b29d8db9/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2645'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/396 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/da8300f7/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/da8300f7/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2645'>Resubmit</a></p>

**Review by adizaimi — DISMISSED** [review]
LGTM! Thanks Joe.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/396 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>backup_logfiles<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/93e46084/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/93e46084/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2645'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/396 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_swapfields_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/93e46084/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/93e46084/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2645'>Resubmit</a></p>

**Review by markhannum — APPROVED** [review]
Very straightforward changes.  The test passed without any issues when I ran it.  Good to merge.

**Pull request merged**
