### PR TITLE
Track stringrefs in list, stack at runtime, exit-abort on tunable

### PR DESCRIPTION
**Pull request by markhannum**
This forces all string-references to be tracked in a linked-list at runtime- which allows us to print all outstanding stringrefs during clean_exit.  Additionally, introduces the 'abort_on_dangling_stringrefs' tunable.  We can toggle this for a specific database if the printed-list output doesn't provide enough information to clean-up.  This PR additionally creates the comdb2_stringrefs table, and the stringrefs test.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ util/string_ref.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>schemalk_extralock_generated<br>truncatesc_offline_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ util/string_ref.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_timepart<br>sc_resume_logicalsc_generated<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>truncatesc_offline_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ util/string_ref.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>schemalk<br>analyze_partial_index_off_generated<br>lostwrite<br>sc_downgrade<br>truncatesc<br>truncatesc_offline_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ util/string_ref.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by mponomar — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>logfill<br>sc_resume<br>schemalk<br>sc_transactional_rowlocks_generated<br>truncatesc<br>truncatesc_offline_generated</p>

**Pull request merged**
