### PR TITLE
parallel execution for "union all" of joins

### PR DESCRIPTION
**Pull request by dorinhogea**
Currently clients that do analytics over sharded databases rely on explicit union-all statements to bring together data from different shards. 
This benefits from parallel execution of  single-table union-all statements, allowing shards to process the data requests in parallel.
This PR allows union-all of joins to run in parallel as well.

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>277/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>siasof<br>sql_datetime_interval_arithmetic_leak<br>updater_latency<br>simple_timepart_reptimeout_generated<br>simple_timepart<br>sc_timepart_logicalsc_generated<br>sc_timepart<br>timepart_auth<br>selectv_timepart</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>siasof<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>socksql_master_swings<br>recover_ddlk_sp<br>sc_downgrade</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/439 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings [core dumped]<br>ixentry_order<br>siasof<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table</p>

**Review by mponomar — APPROVED** [review]

**Comment by dorinhogea** [comment]
Thank you Mike!

**Pull request merged**
