### PR TITLE
Eliminate appsock threads for SQL

### PR DESCRIPTION
**Pull request by akshatsikarwar**
/plugin-branch appsock-v3

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/409 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>phys_rep<br>reorder_inserts_noreorder_generated<br>sc_truncate_lockorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/409 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: Success &#10003;.</p>

**Review by mponomar — APPROVED** [review]
Reviewed with Akshat, good to merge.

**Comment by riverszhang89** [comment]
SSL-libevent patch will soon follow.

**Pull request merged**
