### PR TITLE
pglogs-recovery -> out-of-band

### PR DESCRIPTION
**Pull request by markhannum**
Recover pglogs for PIT snapshot out-of-band

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ bdb/cursor.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/481 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>maxtable<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sc_timepart_logicalsc_generated<br>limitsortingtbl<br>transchunk_manyins</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ bdb/cursor.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/481 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ bdb/cursor.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Comment by markhannum** [comment]
Morgan pointed out some edge-cases that I hadn't thought of (thanks Morgan!) .. going to close for now ..

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/482 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated</p>

**Pull request closed without merging**
