### PR TITLE
net: Clean up more unused code

### PR DESCRIPTION
**Pull request by akshatsikarwar**
/silent

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/573 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_redo [setup failure]<br>siasof [setup failure]<br>sc_resume_logicalsc_generated<br>sc_resume</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>12/573 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts_deletes_logicalsc_generated [setup failure]<br>scupdates [setup failure]<br>writes_remsql_names [setup failure]<br>vutf8_rowlocks_off_osql_odh_blob_generated [setup failure]<br>fdb_push_redirect_generated [setup failure]<br>basic_ssl_generated [setup failure]<br>basic_rowset_generated [setup failure]<br>biginplace [setup failure]<br>sc_truncate_lockorder_generated<br>sc_transactional_rowlocks_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/573 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_dups_logicalsc_generated [setup failure]<br>basic_rowlocks_generated [setup failure]<br>sc_resume<br>truncatesc_ufid_on_generated<br>auth</p>

**Comment by akshatsikarwar** [comment]
```
cdb2test   Aug 22 10:11:43 2024  in-comdb2db net-clean.R20240822.2
```

**Review by markhannum — APPROVED** [review]

**Pull request merged**
