### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by riverszhang89**
Fix a few memory leaks from averager, time_metric, and handle_buf modules.

(DRQS 166788819)

### CODE REVIEW

**Review by mponomar — APPROVED** [review]
Add a test?  Otherwise looks good to go.

**Review by aakash10292 — DISMISSED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/409 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_changeretention</p>

**Comment by riverszhang89** [comment]
Sure, I can add a test.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/410 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_changeretention<br>clientstats_leaks<br>recover_ddlk_sp</p>

**Review by nirbhayc — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/410 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_changeretention<br>reorder_inserts_noreorder_generated</p>

**Comment by riverszhang89** [comment]
@nirbhayc Thank you for the review!

**Pull request merged**
