### PR TITLE
Ignore failure to install various service files

### PR DESCRIPTION
**Pull request by akshatsikarwar**
Fix my usecase: PREFIX=$HOME make install
Remove duplicate pmux.service install
Remove obsolete svn info

### CODE REVIEW

**Comment by akshatsikarwar** [comment]
We could do that - Need to update path to binaries in the service file. Maybe separate PR if ever there is need.

**Comment by mponomar** [comment]
It's a recurring theme.  See #15 - I'd say there's a need.  This is ok as a bandaid.

**Comment by akshatsikarwar** [comment]
Deb smoketest passes. RPM fails with:
`File not found: /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/opt/bb/lib/systemd/system/pmux.service`

But file was installed to:
`/root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/lib/systemd/system/pmux.service`

**Comment by akshatsikarwar** [comment]
From #15: 

> This is by design. They are files needed by other systems, and get installed outside the default $PREFIX. 

And I agree. Non-root installs won't have much use for these files.

**Comment by akshatsikarwar** [comment]
Why do we require installing `pmux.service` at two different locations? My change to remove that is failing rpm smoketest looks like.

**Comment by akshatsikarwar** [comment]
Have both:
https://github.com/bloomberg/comdb2/blob/master/rpmbuild/comdb2.spec#L39
and
https://github.com/bloomberg/comdb2/blob/master/rpmbuild/comdb2.spec#L46

I guess we don't need 46.

**Comment by akshatsikarwar** [comment]
Rivers points out that:
https://github.com/bloomberg/comdb2/blob/master/rpmbuild/comdb2.spec#L74

cp /opt/bb/lib/systemd/system/pmux.service /etc/systemd/system

How many locations do we need to install the service file?

**Comment by mponomar** [comment]
Just the one.  Why don't we just copy it to $(DESTDIR)/$(PREFIX), and install it in postinstall scripts?

**Comment by akshatsikarwar** [comment]
There is no post-install. I don't have root. Thats why I'm doing a PREFIX install in the first place. I don't need these services running at boot.

**Comment by mponomar** [comment]
@nirbhayc made the argument that someone installing to a directory to build an install tarball will still need the files in place.  I don't really have an opinion.  I'm ok with skipping them entirely from a build with a set PREFIX.

**Comment by akshatsikarwar** [comment]
Thats fair. I didn't think of tarball installs.

**Pull request merged**
