### PR TITLE
Set replicant to specific node for comdb2sys tests

### PR DESCRIPTION
**Pull request by LiSodium**
Fixes https://github.com/bloomberg/comdb2/issues/4386

### CODE REVIEW

**Review by morgando — DISMISSED** [review]
Looks good!!

**Review by morgando — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>11/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc<br>schemalk_logicalsc_generated<br>schemalk<br>sc_transactional_rowlocks_generated<br>electbug2<br>queuedb_rollover<br>sc_downgrade<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover<br>op_makerecord<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys<br>comdb2sys_pagesize_generated</p>

**Pull request merged**
