### PR TITLE
{172983130}: Limiting number of rows returned in comdb2_sc_history

### PR DESCRIPTION
**Pull request by riverszhang89**
It takes a whopping 75GiB memory to query the `comdb2_sc_history` table of 2.4 million records, against the database in the linked ticket. In this patch comdb2_sc_history and comdb2_sc_status are changed to return the most recent 10K records.

A memory leak in the comdb2_sc_status system table is also fixed, in this patch.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/525 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>analyze<br>diskspace_nollmeta_nostripe_generated<br>diskspace_nollmeta<br>pmux_sqlite_memory_generated<br>pmux_sqlite_file_generated<br>truncatesc<br>truncatesc_offline_generated</p>

**Review by mponomar — DISMISSED** [review]

**Review by aakash10292 — APPROVED** [review]

**Comment by riverszhang89** [comment]
This was passing robomark:
```
cdb2test   Mar 27 15:23:26 2024  in-comdb2db schistory.R20240327.6
```

**Comment by riverszhang89** [comment]
@aakash10292 Thanks for the review!

**Pull request merged**
