### PR TITLE
{175902854}: Fix segfault on tag api inserts

### PR DESCRIPTION
**Pull request by LiSodium**
To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/578 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_rte_connect_generated [setup failure]<br>sc_remsql_fdbpushredirect_generated [setup failure]<br>basic_snapshot_generated [setup failure]<br>comdb2api<br>tunables<br>truncatesc_ufid_on_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>365/577 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>replay_history [setup failure]<br>sc_resume_logicalsc_generated<br>truncatesc_ufid_on_generated<br>blkseq_snapiso_generated<br>truncatesc_offline_generated<br>analyze_partial_index_off_generated<br>serialstep<br>timepart_trunc<br>selectv_rcode_serialretry_generated<br>selectv_rcode_serialize_reads_like_writes_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>369/577 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>scupdates [setup failure]<br>sc_resume_logicalsc_generated<br>truncatesc_ufid_on_generated<br>truncatesc_offline_generated<br>blkseq_snapiso_generated<br>analyze_exit_immediately<br>serialstep<br>timepart_trunc<br>selectv_rcode_serialretry_generated<br>selectv_rcode_serialize_reads_like_writes_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>365/577 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_lotsoftables [setup failure]<br>comdb2sys [setup failure]<br>sc_resume_logicalsc_generated<br>blkseq_snapiso_generated<br>truncatesc<br>truncatesc_ufid_on_generated<br>truncatesc_offline_generated<br>serialstep<br>timepart_trunc_serialsc_generated<br>selectv_rcode_serialretry_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>11/577 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>leakcheck [setup failure]<br>comdb2sys_pagesize_generated [setup failure]<br>selectv_rcode [setup failure]<br>csvcopy [setup failure]<br>outofrange_queries [setup failure]<br>ddl_dryrun [setup failure]<br>phys_rep_tiered<br>timepart_trunc<br>lostwrite<br>ssl_remsql_fdbpushredirect_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/579 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_fdbpushredirect_generated [setup failure]<br>misstable_remsql_rte_connect_generated [setup failure]<br>analyze_exit_immediately<br>timepart_trunc<br>timepart_trunc_serialsc_generated<br>snap_ha_retry_newsi_generated<br>dbcreate</p>

**Review by mponomar — APPROVED** [review]

**Pull request merged**
