### PR TITLE
Authorizer callback for SQLite for use by the stored procedures subsystem

### PR DESCRIPTION
**Pull request by mistachkin**
These changes forbid any DDL statements from being executed via Lua stored procedures.

### CODE REVIEW

**Comment by mistachkin** [comment]
These changes are not quite complete.  The code in 'comdb2build.c' needs to be modified to call into the SQLite authorizer subsystem.

**Comment by akshatsikarwar** [comment]
I prefer to see this done a bit more surgically.
Enable authorizer only during `lua_prepare_sql_int`. That is the only site where user provided queries are run. Undo all changes in `exec_thread_int/exec_procedure_int`. This will also allow us to deny `SQLITE_CREATE_TEMP_TABLE` but only when done through user specified query.

**Comment by akshatsikarwar** [comment]
We want to use stmt caching if its enabled whether authorizer is active or not.

**Comment by akshatsikarwar** [comment]
Here is an alternate implementation which does not change the world:
https://github.com/akshatsikarwar/comdb2/commit/6d34550a315ebe5bff5cc5e84c45418ff9705cdd

**Pull request closed without merging**
