### PR TITLE
Support for external authentication

### PR DESCRIPTION
**Pull request by nirbhayc**
/plugin-branch port-externalauth

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/479 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>queuedb_rollover</p>

**Review by mohitkhullar — DISMISSED** [review]
Looks good, lets resolve merge conflicts and rerun tests before the final merge.

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by mohitkhullar — APPROVED** [review]

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/484 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>logfill_logput_window_generated<br>sc_truncate_lockorder_generated<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated</p>

**Comment by nirbhayc** [comment]
Thanks @mohitkhullar!

**Pull request merged**
