### PR TITLE
make the weighted_standing_queue test more reliable

### PR DESCRIPTION
**Pull request by riverszhang89**
Signed-off-by: Rivers Zhang <hzhang320@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_truncate<br>ignore_bad_table<br>load_cache_autocache_generated<br>basic_off_osql_odh_blob_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ufid_recovery [core dumped]<br>sc_truncate<br>analyze<br>ignore_bad_table<br>incremental_backup_usenames<br>weighted_standing_queue</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ufid_recovery [core dumped]<br>sc_truncate<br>ignore_bad_table</p>

**Review by mponomar — APPROVED** [review]

**Pull request merged**
