### PR TITLE
Some scripts to make development easier

### PR DESCRIPTION
**Pull request by mponomar**
Provides a 'cluster' script to create a cluster of comdb2 containers.

### CODE REVIEW

**Comment by akshatsikarwar** [comment]
init should also build?

**Comment by akshatsikarwar** [comment]
Error for missing `proxy.conf` should use `${dir}`

`${dir}` should be `comdb2` or `comdb2-util`?

**Comment by akshatsikarwar** [comment]
`cluster build` failed with:
Step 33/35 : COPY cluster    /home/asikarw1/bin/cluster
COPY failed: stat /var/lib/docker/tmp/docker-builder615846446/cluster: no such file or directory

**Comment by mponomar** [comment]
> Error message for missing `proxy.conf` should use `${dir}`
> 
> `${dir}` should be `comdb2` or `comdb2-util`?

`${dir}` is `comdb2-util`.  Script manages `comdb2-util`, which is transient.  `comdb2` is user settings, managed by user, and is persistent (we never write to it).

**Comment by mponomar** [comment]
> `init` should also `build` - no need for `build` anymore really.

Good point! I'll change that.

**Pull request merged**
