### PR TITLE
Cdb2 setinfo clean

### PR DESCRIPTION
**Pull request by markhannum**
Send some additional information to the server: the client's argv0, and the calling backtrace of the thread which called 'cdb2_open'.

### CODE REVIEW

**Comment by markhannum** [comment]
don't understand why there are 19 commits instead of 1 .. maybe i need to re-fork?

**Comment by markhannum** [comment]
Yup- you're right .. we should add to jdbc

**Comment by markhannum** [comment]
Yup- you're right .. we should add this to jdbc

**Comment by adizaimi** [comment]
Is there argv0 for orange?

**Comment by markhannum** [comment]
Reviewed with Mike today.  Fixed plenty- this should be okay to merge now.

**Comment by markhannum** [comment]
It was embarrassing that the review was as useful as it was ..

**Pull request merged**
