### PR TITLE
Dyrun for DDLs

### PR DESCRIPTION
**Pull request by aakash10292**
Work for first part of the ticket : 

https://jira.prod.bloomberg.com/browse/RDSICOMDB2-229

Built on top of initial work done by @nirbhayc

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by nirbhayc — CHANGES_REQUESTED** [review]
Now that parser allows DRYRUN to be used before all sorts of CREATEs & DROPs, I think we should check for `pParse->isDryrun` and appropriately throw prepare error `DRYRUN not supported` (or something similar) for commands that do not yet support dryrun mode.`

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>423/449 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>serial_randtest2<br>sirace<br>sicountbug<br>sicomplex<br>odh_blobs<br>sc_constraints<br>sc_constraints_logicalsc_generated<br>sidupidx3<br>sicomplex3</p>

**Review by nirbhayc — APPROVED** [review]
Looks great! Okay to merge.

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by nirbhayc — DISMISSED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>422/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>serial_randtest2<br>sirace<br>sicomplex<br>sicountbug<br>odh_blobs<br>sc_constraints<br>sc_constraints_logicalsc_generated<br>sidupidx3<br>sicomplex3</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>422/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sirace<br>serial_randtest2<br>sicomplex<br>sicountbug<br>odh_blobs<br>sc_constraints_logicalsc_generated<br>sc_constraints<br>sidupidx3<br>sicomplex3</p>

**Review by mponomar — APPROVED** [review]

**Pull request merged**
