### PR TITLE
"Drop table" extention to partitions

### PR DESCRIPTION
**Pull request by dorinhogea**
Extend 
DROP TABLE t
to partitions.  If t is a partition, the partition, including its shards and their data, is deleted.

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ db/views.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/410 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_trunc [core dumped]<br>timepart_retention1<br>upsert<br>reorder_inserts_noreorder_generated<br>ddl_no_csc2</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ db/views.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/411 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_trunc [core dumped]<br>logfill [core dumped]<br>lostwrite<br>comdb2sys<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>logfill</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ db/views.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/411 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>morestripe [core dumped]<br>logfill [core dumped]<br>sc_truncate_lockorder_generated<br>lostwrite<br>instant_sc_logicalsc_generated<br>logfill</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ db/views.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/411 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill [core dumped]<br>sc_truncate_lockorder_generated<br>sc_constraints<br>sc_constraints_logicalsc_generated<br>logfill</p>

**Review by mponomar — APPROVED** [review]
Thanks Dorin, looks good!

**Comment by dorinhogea** [comment]
Thank you Mike!

**Pull request merged**
