### PR TITLE
{175377342} Account for handle_buf_main passing in null frommach, will eventually…

### PR DESCRIPTION
**Pull request by chands10**
/plugin-branch from_crash_8.0

### CODE REVIEW

**Comment by chands10** [comment]
8 version of https://github.com/bloomberg/comdb2/pull/4463

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc_offline_generated<br>queuedb_rollover<br>sc_downgrade<br>truncatesc_ufid_on_generated</p>

**Comment by chands10** [comment]
cdb2test May 29 18:31:17 2024 in-comdb2db null_from_8.0.R20240529.7

**Review by aakash10292 — APPROVED** [review]
LGTM

**Pull request merged**
