### PR TITLE
Fix comdb2sys & auth tests

### PR DESCRIPTION
**Pull request by markhannum**
Fix comdb2sys & auth test outputs

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>225/580 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>blkseq_race [setup failure]<br>verify_error_partial_index_off_generated [setup failure]<br>verify_error [setup failure]<br>systable_locking<br>sc_resume_logicalsc_generated<br>sc_resume<br>sc_truncate_lockorder_generated<br>truncatesc<br>analyze_partial_index_off_generated<br>userschema_queueodh_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/580 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>autoanalyze [setup failure]<br>union_parallel [setup failure]<br>basic_sslnoproto_generated [setup failure]<br>timepart_trunc<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated<br>cdb2sql_queueodh_generated<br>cdb2sql<br>sc_downgrade</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/580 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_names_fdbpush_generated [setup failure]<br>verify_error_partial_index_off_generated [setup failure]<br>mismatch_class_remsql_fdbpushredirect_generated [setup failure]<br>sc_resume_logicalsc_generated<br>sc_transactional_rowlocks_generated<br>analyze<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated</p>

**Review by mponomar — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/580 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>blkseq_race [setup failure]<br>writes_remsql_names [setup failure]<br>basic_off_osql_odh_blob_generated [setup failure]<br>sc_resume_logicalsc_generated<br>sc_repeated_updates<br>snap_ha_retry_newsi_generated<br>truncatesc</p>

**Pull request merged**
