### PR TITLE
Disable dbq-admin on physreps, verify we dont allow writes from consumers

### PR DESCRIPTION
**Pull request by markhannum**
Stub out blkseq for physreps, verify in test.  Don't replicate queuedb to physrep.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>105/526 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>truncatesc<br>truncatesc_ufid_on_generated<br>truncatesc_offline_generated<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>load_cache<br>load_cache_autocache_generated<br>load_cache_dumpmax_generated<br>pmux_sqlite_file_generated</p>

**Review by riverszhang89 — DISMISSED** [review]

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/526 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>truncatesc<br>truncatesc_ufid_on_generated<br>truncatesc_offline_generated<br>load_cache_autocache_generated<br>load_cache_dumpmax_generated<br>load_cache<br>cdb2sql_queueodh_generated<br>cdb2sql</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/526 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>nightmare_recovery<br>queuedb_rollover_noroll1_generated<br>cdb2sql_queueodh_generated<br>cdb2sql<br>truncatesc_offline_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/526 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cdb2sql_queueodh_generated<br>cdb2sql<br>truncatesc_offline_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by mponomar — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/526 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sc_lotsoftables<br>sc_downgrade<br>truncatesc_offline_generated</p>

**Pull request merged**
