### PR TITLE
Send an dummy response for COMMIT/ROLLBACK for a failed tx

### PR DESCRIPTION
**Pull request by nirbhayc**
This fixes a regression where old client APIs expect a response from Comdb2.

### CODE REVIEW

**Comment by mohitkhullar** [comment]
Looks good

**Comment by akshatsikarwar** [comment]
What is the old client API?

**Comment by nirbhayc** [comment]
go-cdb2, IIUC it's implementation was based on R6's cdb2api.

**Comment by akshatsikarwar** [comment]
cdb2api should be the same regardless of which implementation, no?

**Comment by akshatsikarwar** [comment]
Sorry, when you say old client API, I think fastsql..

**Comment by nirbhayc** [comment]
> cdb2api should be the same regardless of which implementation, no?

yea, and also the wire protocol.

**Comment by nirbhayc** [comment]
This PR is about fixing a fairly recent change in the wire protocol (0fe3cb0 & 89fb44d). go-cdb2 API, since its inception, expected a response on COMMIT/ROLLBACK even for failed transactions. But, due to the regression, Comdb2 no longer sends one for failed transactions.

**Comment by nirbhayc** [comment]
Cherry-picked to 7.0

**Pull request merged**
