### PR TITLE
cleanup some of the remaining warnings

### PR DESCRIPTION
**Pull request by adizaimi**

### CODE REVIEW

**Comment by mohitkhullar** [comment]
looks good

**Comment by adizaimi** [comment]
Thanks Mohit

**Comment by riverszhang89** [comment]
It'd be great if you could format your change and let roborivers quickly verify it before merging.

**Comment by adizaimi** [comment]
Yes Rivers, I was too quick to press button. I checked in formatted changes in the next pr https://github.com/bloomberg/comdb2/pull/547. 
Thanks.

**Comment by riverszhang89** [comment]
Thanks for the clarification Adi.

**Pull request merged**
