### PR TITLE
block creating a partition with shards matching existing shards

### PR DESCRIPTION
**Pull request by dorinhogea**
Port https://github.com/bloomberg/comdb2/pull/4701 to main branch.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/577 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>vutf8_rowlocks [setup failure]<br>basic [setup failure]<br>simple_timepart_reptimeout_generated<br>simple_timepart<br>timepart_retention1<br>online_compaction<br>timepart_trunc<br>truncatesc_ufid_on_generated<br>dbcreate</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/577 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>blkseq_race [setup failure]<br>comdb2sys [setup failure]<br>writes_remsql_names_rte_connect_generated [setup failure]<br>misstable_remsql [setup failure]<br>timepart_trunc_serialsc_generated<br>timepart_trunc<br>dbcreate</p>

**Review by mponomar — APPROVED** [review]

**Comment by dorinhogea** [comment]
@mponomar thank you

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/577 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fdb_push [setup failure]<br>sc_transactional_rowlocks_generated<br>analyze_exit_immediately<br>truncatesc_ufid_on_generated<br>auth<br>dbcreate</p>

**Pull request merged**
