### PR TITLE
Fixes around log_delete tunables

### PR DESCRIPTION
**Pull request by nirbhayc**
* Change in logdeleteage semantics: tunable accepts unix epoch; log deletion pauses until the specified time, that is until logdeleteage > now.
* Tunables `log_delete_after_backup`, `log_delete_before_startup` and `log_delete_now` have all been made INTERNAL as they all backed to the same variable db->log_delete_age like `log_delete_age`. They can all still be set using PUT TUNABLE or sync command.
* Updated log deletion policy message displayed in stat command.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6516b58/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/372 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>autoanalyze</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6516b58/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/6516b58/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2496'>Resubmit</a></p>

**Review by markhannum — APPROVED** [review]
Looks great- good to merge!

**Comment by nirbhayc** [comment]
Cherry-picked to 7.0

**Comment by nirbhayc** [comment]
Thanks for the review @markhannum!

**Pull request merged**
