### PR TITLE
{175585634}: Do not fail too quickly for non-HA retry

### PR DESCRIPTION
**Pull request by riverszhang89**
The `min-retries` tunable in cdb2api is probably set too low: querying a cluster during leader change almost immediately errors out.

This pull requests bumps the default `min-retries` value to 16.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>16/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>cdb2api_retry<br>analyze_exit_immediately<br>comdb2sys_pagesize_generated<br>ruleset<br>pmux_secure_route<br>dbcreate<br>basic_snapshot_generated<br>basic_rowset_generated<br>basic_rowlocks_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>15/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>sc_truncate_lockorder_generated<br>cdb2api_retry<br>ruleset<br>pmux_secure_route<br>dbcreate<br>basic_snapshot_generated<br>basic_rowset_generated<br>basic_rowlocks_generated<br>basic_protobuf_connectmsg_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>15/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>timepart_trunc<br>ruleset<br>pmux_secure_route<br>dbcreate<br>basic_snapshot_generated<br>basic_rowset_generated<br>basic_rowlocks_generated<br>basic_protobuf_connectmsg_generated<br>basic_off_osql_odh_blob_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/560 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_transactional_rowlocks_generated<br>analyze_exit_immediately<br>dbcreate<br>queuedb_rollover_noroll1_generated<br>sc_downgrade<br>incoh_remsql<br>api_events</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/561 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>dbcreate<br>api_events</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/561 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>sc_resume_logicalsc_generated<br>api_events<br>dbcreate</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_trunc<br>timepart_trunc_serialsc_generated<br>dbcreate<br>truncatesc_offline_generated</p>

**Comment by riverszhang89** [comment]
```
cdb2test   Jul  5 18:46:06 2024  in-comdb2db apiretry.R20240705.7
```

@markhannum Thanks for the review, Mark!

**Pull request merged**
