### PR TITLE
Physrep: Use round-robin to access all metadb hosts specified in the lrl

### PR DESCRIPTION
**Pull request by nirbhayc**
There was a bug causing only the first host to be used from the comma-separated list of metadb hosts specified in the lrl file.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/phys_rep.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/phys_rep.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by markhannum — APPROVED** [review]

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/phys_rep.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/phys_rep.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/512 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover<br>incremental_backup_load<br>prepare<br>delfile_block_reproleak_generated<br>truncatesc</p>

**Comment by nirbhayc** [comment]
Thanks @markhannum!

**Pull request merged**
