### PR TITLE
Fix off by one line number in ddl error reports.

### PR DESCRIPTION
**Pull request by mponomar**
Signed-off-by: Mike Ponomarenko <mponomarenko@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/682b8bfd/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>8/399 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>yast<br>rawindex<br>constraints<br>guid<br>ddl_csc2<br>ddl_no_csc2<br>datetime</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/682b8bfd/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/682b8bfd/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2703'>Resubmit</a></p>

**Review by adizaimi — CHANGES_REQUESTED** [review]
Code change looks good. 
We already have lots of errors (that need fixing in the tests), and so the new test is probably redundant.

**Comment by mponomar** [comment]
There didn't seem to be a good test to add this too, but I'm open to suggestions.

**Comment by adizaimi** [comment]
> There didn't seem to be a good test to add this too, but I'm open to suggestions.

I mean the failing tests above are the result of your change. Fixing those tests is enough, ex the failure in raw index.test:
```
12:15:58> > diff /dedicated/db/rawindex.test/{t12.req.exp,t12.req.res}
12:15:58>  
12:15:58> 14c14
12:15:58> < [create table t12 {schema{int i cstring j[16]} keys{"I" = (int)"i" {where j < ''}'}}}] failed with rc 240 ERROR at line   0: syntax error: '
12:15:58> ---
12:15:58> > [create table t12 {schema{int i cstring j[16]} keys{"I" = (int)"i" {where j < ''}'}}}] failed with rc 240 ERROR at line   1: syntax error: '
```
So this test is already verifying your change by means of the line 0/1 difference.

**Pull request closed without merging**
