### PR TITLE
Add IAM user metrics

### PR DESCRIPTION
**Pull request by mohitkhullar**
/plugin-branch user_metrics

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/575 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts [setup failure]<br>serialstep [setup failure]<br>writes_remsql_names_fdbpush_generated [setup failure]<br>writes_remsql_fdbpushredirect_generated [setup failure]<br>sc_truncate<br>analyze_exit_immediately<br>timepart_trunc_serialsc_generated<br>timepart_trunc<br>tunables<br>auth</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/575 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>truncatesc<br>analyze_exit_immediately<br>tunables<br>truncatesc_ufid_on_generated<br>dbcreate</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/575 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_retention1 [setup failure]<br>simple_timepart_reptimeout_generated [setup failure]<br>verify_error [setup failure]<br>basic_rowset_generated [setup failure]<br>sc_resume<br>tunables<br>truncatesc<br>truncatesc_ufid_on_generated<br>dbcreate</p>

**Review by mponomar — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/577 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_retention1 [setup failure]<br>updcolsbug [setup failure]<br>sc_redo [setup failure]<br>comdb2sys_queueodh_generated [setup failure]<br>logfill<br>sc_resume<br>tunables<br>truncatesc_ufid_on_generated</p>

**Comment by mohitkhullar** [comment]
Thanks

**Pull request merged**
