### PR TITLE
option to ignore corrupted tables during start up

### PR DESCRIPTION
**Pull request by dorinhogea**
Currently, any table that has corrupted metadata or missing disk files prevents a server from coming up. 
The patch adds an option for the server comes up by ignoring the broken table, allowing access to the other tables.  The missing table can be recreated and the metadata will be overwritten and fixed.
Ported from R6 https://bbgithub.dev.bloomberg.com/comdb2/comdb2/pull/811

### CODE REVIEW

**Comment by nirbhayc** [comment]
@dorinhogea Could you also add a test for this new tunable?

**Comment by dorinhogea** [comment]
@nirbhayc :testcase added

**Comment by dorinhogea** [comment]
Thanks for the review

**Comment by nirbhayc** [comment]
Thank you!

**Comment by adizaimi** [comment]
FTR, this is the error in tests/62ebd7f950a2ba57816db7ad21e0d204065d147a/test_15970/logs/scindex15970.testcase:
21:54:17> ERROR: Verify failed.
21:54:17> Testcase failed.

**Pull request merged**
