### PR TITLE
Fix stat4

### PR DESCRIPTION
**Pull request by akshatsikarwar**
{174625959} sqlite: Build with SQLITE_64BIT_STATS
Also,
* Update stat4dump to print u64.
* Enable stat4dump in datacopy test.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/522 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>queuedb_rollover</p>

**Comment by akshatsikarwar** [comment]
`cdb2test   Mar 13 13:16:22 2024  in-comdb2db stat4dump.R20240313.4`

**Review by mponomar — APPROVED** [review]

**Pull request merged**
