### PR TITLE
Make page compaction tracing a runtime option

### PR DESCRIPTION
**Pull request by riverszhang89**
Currently page compaction tracing is a compile time option. Make it a runtime option so that it can be toggled at runtime.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ignore_bad_table<br>updater_latency<br>load_cache</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ignore_bad_table<br>blkseq_snapiso_generated<br>load_cache_dumpmax_generated<br>load_cache_autocache_generated<br>tunables<br>basic_snapshot_generated<br>basic_nolibevent_generated</p>

**Review by markhannum — APPROVED** [review]
Very straightforward- good to merge!

**Comment by riverszhang89** [comment]
@markhannum Thanks for the review!

**Pull request merged**
