### PR TITLE
Support SSL for newsql-libevent clients

### PR DESCRIPTION
**Pull request by akshatsikarwar**
${TITLE}

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>169/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sirace<br>recom_replay<br>simple_ssl<br>serialstep<br>selectv_recom_range<br>selectv_recom<br>op_makerecord<br>verify_error_partial_index_off_generated<br>verify_error<br>upsert</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ssl_rep [setup core dumped]<br>yast [core dumped]<br>multithd [core dumped]<br>simple_ssl<br>reorder_inserts_noreorder_generated<br>blob_size_limit<br>tunables<br>close_old_connections<br>lock_maxid</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>temp_table_truncate_leak [core dumped]<br>truncatesc [core dumped]<br>phys_rep<br>unionpar_maxqueue<br>mallocresize<br>reorder_inserts_noreorder_generated<br>blob_size_limit<br>tunables<br>close_old_connections<br>lock_maxid</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>constraints_noreorder_generated [core dumped]<br>sc_truncate_lockorder_generated<br>unionpar_maxqueue<br>reorder_inserts_noreorder_generated<br>blob_size_limit<br>tunables<br>bloballoc<br>lock_maxid</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>op_makerecord<br>nowritetimeout<br>reorder_inserts_noreorder_generated<br>blob_size_limit<br>tunables<br>bloballoc<br>lock_maxid</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>morestripe [core dumped]<br>phys_rep<br>reorder_inserts_noreorder_generated<br>blob_size_limit<br>recover_ddlk_sp<br>bloballoc<br>lock_maxid</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>reorder_inserts_noreorder_generated<br>blob_size_limit<br>lock_maxid</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>smartbeats<br>reorder_inserts_noreorder_generated<br>lock_maxid</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>reorder_inserts_noreorder_generated<br>recover_ddlk_sp<br>lock_maxid</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc [core dumped]<br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite<br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>reorder_inserts_noreorder_generated<br>recover_ddlk_sp<br>sc_swapfields_logicalsc_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc_offline_generated [core dumped]<br>morestripe [core dumped]<br>reorder_inserts_noreorder_generated</p>

**Review by riverszhang89 — APPROVED** [review]

**Pull request merged**
