### PR TITLE
Dedup req-all-reqs

### PR DESCRIPTION
**Pull request by markhannum**
Signed-off-by: Mark Hannum <mhannum72@gmail.com>

Only allow a single rep_all_req on the outgoing queue to master

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ignore_bad_table<br>incremental_backup_usenames<br>load_cache_dumpmax_generated<br>reorder_deletes_noreorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ignore_bad_table<br>load_cache</p>

**Review by mohitkhullar — APPROVED** [review]
Looks good

**Pull request merged**
