### PR TITLE
Allocate temptable resources based on the temptable type

### PR DESCRIPTION
**Pull request by riverszhang89**
"Only pay for what you need."

(DRQS 164136373)

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/375 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>tmptbl_leak_zeropool_generated [core dumped]<br>tmptbl_leak [core dumped]<br>tmptbl_leak_megapool_generated [core dumped]<br>tmptbl_leak_bigpool_generated [core dumped]<br>tmptbl_deadlock [core dumped]<br>tmptbl_starve [core dumped]<br>tmptbl_leak_starve_generated [core dumped]<br>fingerprints</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/563d86c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/563d86c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2538'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/375 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/21de003/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/21de003/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2538'>Resubmit</a></p>

**Comment by akshatsikarwar** [comment]
no cache no cash

**Review by adizaimi — APPROVED** [review]
Looks good to me.

**Comment by riverszhang89** [comment]
Thank you for the review, Adi!

**Pull request merged**
