### PR TITLE
json: Import latest json implementation from SQLite

### PR DESCRIPTION
**Pull request by akshatsikarwar**
/silent

### CODE REVIEW

**Comment by akshatsikarwar** [comment]
Note from [upstream](https://sqlite.org/src/doc/json-in-core/doc/json-enhancements.md):

> 3.0 JSON moved into the core
> 
> The JSON interface is now moved into the SQLite core.
> 
> When originally written in 2015, the JSON functions were an extension that could be optionally included at compile-time, or loaded at run-time. The implementation was in a source file named ext/misc/json1.c in the source tree. JSON functions were only compiled in if the -DSQLITE_ENABLE_JSON1 compile-time option was used.
> 
> After these enhancements, the JSON functions are now built-ins. The source file that implements the JSON functions is moved to src/json.c. No special compile-time options are needed to load JSON into the build. Instead, there is a new -DSQLITE_OMIT_JSON compile-time option to leave them out.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>124/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>updater_latency<br>yast_stat4scan_generated<br>yast<br>jsonify<br>auth_twofiles_generated<br>auth_queueodh_generated<br>auth<br>userschema_queueodh_generated<br>userschema<br>comdb2sys_queueodh_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ignore_bad_table<br>incremental_backup_usenames<br>yast_stat4scan_generated<br>yast<br>auth_twofiles_generated<br>auth_queueodh_generated<br>auth<br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ignore_bad_table<br>yast_stat4scan_generated<br>yast<br>auth_twofiles_generated<br>auth<br>auth_queueodh_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>200/451 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_truncate_lockorder_generated<br>sc_truncate<br>selectv_rcode<br>selectv_rcode_disable_svonly_nop_generated<br>yast_stat4scan_generated<br>yast<br>load_cache<br>auth_twofiles_generated<br>auth_queueodh_generated</p>

**Comment by akshatsikarwar** [comment]
This needs parser changes as well for new operators. Will defer this for now.

**Pull request closed without merging**
