### PR TITLE
Add a knob to control subquery flattening optimization

### PR DESCRIPTION
**Pull request by nirbhayc**
Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

### CODE REVIEW

**Comment by riverszhang89** [comment]
I think appending "LIMIT -1" to a sub-query also disables the flattening optimization.

**Comment by nirbhayc** [comment]
> I think appending "LIMIT -1" to a sub-query also disables the flattening optimization.

Yes, that it right. However, the problem looks general enough (see the included test) I thought it will be good it we have an option to control this specific optimization on the server side.

**Comment by nirbhayc** [comment]
Thanks for the review @mistachkin !

**Comment by nirbhayc** [comment]
Cherry-picked to master branch.

**Pull request merged**
