### PR TITLE
Test and fix for stat4dump crash

### PR DESCRIPTION
**Pull request by markhannum**
This branch reproduces and fixes the stat4dump crash.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/535 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables<br>truncatesc_offline_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ db/sqlglue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>88/535 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>lock_views<br>sp_twofiles_generated<br>sp_snapshot_generated<br>sp<br>sp_queueodh_generated<br>sql<br>sc_transactional_rowlocks_generated<br>comdb2expert<br>manual_partition</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ db/sqlglue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by aakash10292 — DISMISSED** [review]
LGTM

**Review by aakash10292 — APPROVED** [review]

**Pull request merged**
