### PR TITLE
Increase linux performance

### PR DESCRIPTION
**Pull request by mohitkhullar**
by 5-10% for linux server, extra 5-10%  if client is also on linux

### CODE REVIEW

**Comment by jmleddy** [comment]
How do we know any of this improves performance?

**Comment by mohitkhullar** [comment]
I benchmarked it against queries with datetime/integer index & fields.

**Comment by jmleddy** [comment]
Oh sorry I didn't see the first comment.

**Comment by dorinhogea** [comment]
please collapse those commits into one

**Pull request merged**
