### PR TITLE
net: Fix incorrect buffer in user_msg_callback

### PR DESCRIPTION
**Pull request by akshatsikarwar**
/silent

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/411 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill [core dumped]<br>phys_rep<br>sc_constraints<br>sc_constraints_logicalsc_generated<br>sc_resume<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys<br>logfill</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/411 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/411 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_constraints<br>sc_resume<br>comdb2sys_queueodh_generated<br>comdb2sys<br>comdb2sys_pagesize_generated<br>recover_ddlk_sp</p>

**Comment by akshatsikarwar** [comment]
We were matching user_msg_info with incorrect buffer from akq_buf, after it was freed during disable_read (disconnect). The fix is to stop freeing akq_buf, as we no longer make a copy of the user messages.

**Comment by akshatsikarwar** [comment]
This fixes the logfill testcase.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/411 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>scindex_deadlock [setup failure]<br>logfill<br>sc_constraints<br>sc_resume<br>comdb2sys_pagesize_generated<br>comdb2sys<br>comdb2sys_queueodh_generated</p>

**Pull request closed without merging**
