### PR TITLE
cdb2sql: option to connect to master

### PR DESCRIPTION
**Pull request by riverszhang89**
This patch adds a `-m` option to cdb2sql which conveniently connects to the master node.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>ignore_bad_table<br>weighted_standing_queue<br>load_cache<br>allow_incoherent_sql</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ignore_bad_table</p>

**Review by nirbhayc — APPROVED** [review]
LGTM

**Comment by riverszhang89** [comment]
@nirbhayc thanks for the review!

**Pull request merged**
