### PR TITLE
Correctly handle unix time of -1

### PR DESCRIPTION
**Pull request by riverszhang89**
db_struct2time() returns -1 on error, as well as for "1969-12-31T23:59:59". There's no way to tell the two cases apart and we wind up treating "1969-12-31T23:59:59" as an error.

To fix it, errno is set if there's an actual failure. When db_struct2time() returns -1, if errno is 0, it's "1969-12-31T23:59:59"; otherwise it's an error.

(DRQS 166367318)

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/42b3460c/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/42b3460c/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_swapfields_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/42b3460c/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/42b3460c/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2873'>Resubmit</a></p>

**Comment by akshatsikarwar** [comment]
I think an out-param would be clearner:
`if (db_struct2time(actualtzname, &tm, &sdt.sec)`
instead of 
`if ((sdt.sec = db_struct2time(actualtzname, &tm)) && errno)`

**Comment by riverszhang89** [comment]
I wanted the function to be consistent with system date/time functions in terms of return value and error handling. For instance, `man 2 time` states that "on error, ((time_t) -1) is returned, and errno is set appropriately". Similarly, if the time since the Epoch cannot be represented, `mktime` returns -1 and set errno.

**Comment by akshatsikarwar** [comment]
> I wanted the function to be consistent with system date/time functions

OK - that's fair..

**Review by mponomar — APPROVED** [review]
Thanks Rivers, looks good!

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c04bf3ad/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c04bf3ad/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/c04bf3ad/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2873'>Resubmit</a></p>

**Comment by riverszhang89** [comment]
@akshatsikarwar @mponomar Thank you for the review!

**Pull request merged**
