### PR TITLE
Tests: use common restart node function from cluster_utils.sh

### PR DESCRIPTION
**Pull request by adizaimi**
Use common function from cluster_utils.sh in the tests which
call kill_restart_node().

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/397 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>op_makerecord</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ae8ddafd/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ae8ddafd/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2674'>Resubmit</a></p>

**Review by roborivers — COMMENTED** [review]
<p>Sysbench Transactions Per Second (commit: ae8ddafd):</p>

<pre lang=diff>
@@ sysbench/bulk_insert @@
+9.04%
@@ sysbench/oltp_read_only @@
+16.02%
@@ sysbench/oltp_point_select @@
+8.28%
@@ sysbench/oltp_update_non_index @@
+7.12%
@@ sysbench/oltp_delete @@
+4.26%
@@ sysbench/oltp_update_index @@
+7.69%
@@ sysbench/oltp_read_write @@
+5.65%
</pre>

**Review by markhannum — APPROVED** [review]
Very simple- removes duplicate code- good to merge

**Comment by adizaimi** [comment]
Thank you Mark!

**Pull request merged**
