### PR TITLE
Bitemporal

### PR DESCRIPTION
**Pull request by ldennis**
Bi-Temporal Tables: https://ldennis.github.io/comdb2docs/bitemporal.html
Non-Overlapping Constraints: https://ldennis.github.io/comdb2docs/table_schema.html#no-overlapping-constraints

### CODE REVIEW

**Comment by adizaimi** [comment]
Can you merge master and I can try to take a look and review. We should get this in soon.

**Comment by ldennis** [comment]
closing for now, I will wait until #145 is in and I want to adapt schemachange of temporal tables to my refactored sc code.

**Comment by ldennis** [comment]
rebased and refactored sc code according to #145

**Comment by pbowyer** [comment]
I found the documentation at https://ldennis.github.io/comdb2docs/bitemporal.html while Googling for bi-temporal supporting database and got _very excited_. Only to find it hasn't made it into Comdb2 - yet.

Is it planned to add this to the database?

**Comment by mponomar** [comment]
Yep.  It won’t make it into 7.0, but will be in 7.1.

**Pull request closed without merging**
