### PR TITLE
Fewer temptables for new snapshot

### PR DESCRIPTION
**Pull request by riverszhang89**
We allocate one temptable per log file for pglogs. When the database accumulates a large number of log files (a long running snapshot transaction, node crashed, etc.), many temptables will be created and it may eventually cause the system to run out of memory.

This patch reduces the number of temptables needed: only a fixed number of temptables are created, and are shared among log files in a round-robin fashion.

(DRQS 168188318)

### CODE REVIEW

**Comment by riverszhang89** [comment]
#### Temptable usage of 500 log files ####

On master:
```
Object pool [temp table] stats
   Type                 : LIFO
   Status               : running
   Current load         : 99%
   # total objects      : 1002
   # peak               : 1002
```

This PR:
```
Object pool [temp table] stats
  Type                 : LIFO
  Status               : running
  Current load         : 50%
  # total objects      : 14
  # peak               : 14
  # active             : 7
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>analyze_partial_index_off_generated [core dumped]<br>dohsql_leaks<br>sc_repeated_updates<br>guid<br>reorder_inserts_noreorder_generated<br>selectv_rcode</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ bdb/cursor.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/423 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>blkseq [core dumped]<br>incremental_backup_usenames<br>reorder_inserts_noreorder_generated</p>

**Review by mponomar — APPROVED** [review]

**Review by mponomar — CHANGES_REQUESTED** [review]
Looks like there's no way to age out old entries yet.

**Pull request closed without merging**
