### PR TITLE
Add 'class' to the comdb2_sysinfo() SQL function

### PR DESCRIPTION
**Pull request by mistachkin**
These changes permit easier programmatic introspection of the class associated with a particular running database instance.

### CODE REVIEW

**Comment by adizaimi** [comment]
I think this should be in plugins if possible, and only exposed to bb.

**Comment by mistachkin** [comment]
> 
> 
> I think this should be in plugins if possible, and only exposed to bb.

Even though the core functionality behind this is in the core itself?  There are certain use cases where being able to introspect this information could be very important.

**Comment by adizaimi** [comment]
I guess others can use functionality or not, as long as we have a default, this is ok.

**Comment by mohitkhullar** [comment]
looks good, thanks

**Pull request merged**
