### PR TITLE
eventlog: Add carray support

### PR DESCRIPTION
**Pull request by akshatsikarwar**
/silent

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/492 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover<br>analyze_partial_index_off_generated<br>replay_eventlog<br>eventlog<br>queuedb_rollover_noroll1_generated<br>truncatesc<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
.

**Review by roborivers — CHANGES_REQUESTED** [review]
.

**Review by roborivers — CHANGES_REQUESTED** [review]
.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/2 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>eventlog</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/2 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>eventlog</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>14/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>schemalk<br>sc_transactional_rowlocks_generated<br>queuedb_rollover<br>replay_eventlog<br>transchunk_manyins<br>eventlog<br>pmux_sqlite_memory_generated<br>sc_swapfields_logicalsc_generated<br>sc_lotsoftables_logicalsc_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>387/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>yast_stat4scan_generated<br>yast<br>analyze_recover_deadlock<br>autoanalyze<br>analyze_partial_index_off_generated<br>analyze<br>temp_table_truncate_leak</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/534 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk_logicalsc_generated<br>phys_rep_tiered_nosource_generated<br>phys_rep_tiered<br>sc_downgrade<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys<br>comdb2sys_pagesize_generated</p>

**Review by mponomar — APPROVED** [review]

**Pull request merged**
