### PR TITLE
RDSICOMDB2-294

### PR DESCRIPTION
**Pull request by aakash10292**
Don't return error on u_longlong fields during dryrun sql for operations that don't change the schema (rebuild, rebuild index)

### CODE REVIEW

**Review by mponomar — DISMISSED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ddl_dryrun [setup failure]<br>queuedb_rollover_noroll1_generated<br>incoh_remsql</p>

**Review by nirbhayc — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ddl_dryrun [setup failure]<br>sc_transactional_rowlocks_generated<br>incremental_backup_usenames<br>queuedb_rollover<br>prepare<br>incoh_remsql</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ddl_dryrun [setup failure]<br>systable_locking<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sc_timepart<br>incoh_remsql</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>incremental_backup_usenames<br>queuedb_rollover<br>prepare<br>incoh_remsql</p>

**Review by nirbhayc — APPROVED** [review]
LGTM

**Pull request merged**
