### PR TITLE
Remove AIX + HPUX code

### PR DESCRIPTION
**Pull request by morgando**
The changes in this PR remove code for the AIX and HPUX operating systems since Comdb2 no longer supports them.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ util/comdb2_pthread_create.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>analyze_exit_immediately<br>selectv_rcode<br>guid<br>truncatesc</p>

**Review by mponomar — DISMISSED** [review]

**Comment by morgando** [comment]
`cdb2test   Jul 31 15:11:32 2024  in-comdb2db rm_aix_hpux.R20240731.8`

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>analyze_exit_immediately<br>sys_cmd_access<br>truncatesc_ufid_on_generated</p>

**Review by riverszhang89 — APPROVED** [review]

**Pull request merged**
