### PR TITLE
Add bounce_connection support to hasql snapshot test

### PR DESCRIPTION
**Pull request by RohanNankani**

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/578 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>largecsc2 [setup failure]<br>analyze_exit_immediately<br>snap_ha_retry_newsi_generated<br>truncatesc<br>truncatesc_ufid_on_generated</p>

**Comment by morgando** [comment]
`mdouglas47 Sep 19 15:29:20 2024  in-comdb2db rohan/add-disconnect-hasql.R20240919.5`

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>11/578 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>unionpar_maxqueue [setup failure]<br>sc_inserts_logicalsc_generated [setup failure]<br>autoanalyze [setup failure]<br>basic_ssl_generated [setup failure]<br>verify_db_parallel_generated [setup failure]<br>sc_resume_logicalsc_generated<br>sc_transactional_rowlocks_generated<br>truncatesc<br>timepart_trunc<br>timepart_trunc_serialsc_generated</p>

**Review by morgando — APPROVED** [review]
LGTM! Thank you Rohan 😄

**Pull request merged**
