### PR TITLE
Fix use of deprecated function

### PR DESCRIPTION
**Pull request by riverszhang89**
Easy fix for upgraded compiler: `cdb2sockpool.c:1118:5: error: 'sigignore' is deprecated: Use the signal function instead [-Werror=deprecated-declarations]`

### CODE REVIEW

**Review by markhannum — DISMISSED** [review]
Good to merge!

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/444 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ignore_bad_table<br>weighted_standing_queue<br>selectv_rcode_disable_svonly_nop_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/443 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ignore_bad_table<br>load_cache_dumpmax_generated<br>load_cache<br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/443 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>ignore_bad_table<br>timepart_trunc<br>load_cache</p>

**Review by markhannum — APPROVED** [review]
Good to merge

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/443 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep<br>ignore_bad_table<br>load_cache_dumpmax_generated<br>load_cache</p>

**Review by markhannum — APPROVED** [review]
good to merge!

**Comment by riverszhang89** [comment]
@markhannum Thank you for the review!

**Pull request merged**
