### PR TITLE
Changes to the cluster script

### PR DESCRIPTION
**Pull request by mogarg**
Making some changes to the cluster script while trying it on macOS. Currently, it assumes tmux to be located at 
`/usr/bin/tmux` so I changed it to picking it up using `command`. Also, cluster script is not necessarily located at "${HOME}/bin/cluster" though it would be located at "${PWD}/cluster" so I changed that as well. Made some other cleanup changes.

### CODE REVIEW

**Review by roborivers — DISMISSED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ea92aa9a/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/ea92aa9a/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2878'>Resubmit</a></p>

**Comment by akshatsikarwar** [comment]
https://github.com/roborivers/cheatsheet

**Comment by akshatsikarwar** [comment]
comdb3dumpcsc?

**Pull request closed without merging**
