### PR TITLE
{176446246}: Fixing read-committed updates behind sc-cursor

### PR DESCRIPTION
**Pull request by riverszhang89**
Do not pass an empty blob token to the types system, which treats such a blob as an error, causing schema change to fail.  An empty blob token does not participate in the update, so it makes no sense to convert it anyways.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Comment by riverszhang89** [comment]
```
cdb2test   Sep 23 11:47:12 2024  in-comdb2db sc_fix.R20240923.1
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/578 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>copyschema_timepart [setup failure]<br>sc_resume_logicalsc_generated<br>analyze_exit_immediately<br>snap_ha_retry_newsi_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/579 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>replay_history [setup failure]<br>sc_tableversion_logicalsc_generated [setup failure]<br>writes_remsql_fdbpushredirect_generated [setup failure]<br>writes_remsql [setup failure]<br>vutf8_rowlocks_off_osql_odh_blob_generated [setup failure]<br>fdb_push_rte_connect_generated [setup failure]<br>sc_resume_logicalsc_generated<br>snap_ha_retry_newsi_generated<br>truncatesc</p>

**Comment by riverszhang89** [comment]
```
cdb2test   Sep 25 10:45:25 2024  in-comdb2db sc_fix.R20240925.2
```

**Review by markhannum — APPROVED** [review]

**Comment by riverszhang89** [comment]
@markhannum Thank you very much for the review!

**Pull request merged**
