### PR TITLE
net: Reduce jitter, suspend only when exceeding limit

### PR DESCRIPTION
**Pull request by akshatsikarwar**
/silent

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Failed to compile.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ignore_bad_table<br>sc_timepart<br>load_cache_autocache_generated<br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ignore_bad_table<br>datacopy</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sql_datetime_interval_arithmetic_leak<br>phys_rep<br>ignore_bad_table<br>load_cache_dumpmax_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>sc_resume_logicalsc_generated<br>sc_truncate<br>ignore_bad_table<br>load_cache<br>load_cache_autocache_generated<br>selectv_rcode_disable_svonly_nop_generated</p>

**Review by riverszhang89 — APPROVED** [review]
Looks great! Okay to merge!

**Pull request merged**
