### PR TITLE
Enable fdb_push_redirect by default

### PR DESCRIPTION
**Pull request by chands10**
Let client talk to fdb directly instead of bothering us

Requires that fdb push be enabled

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Comment by dorinhogea** [comment]
Can we have a SET option to opt in per sql handle? I imagine some slow client machines that require single records will prefer to avoid bouncing through client, but still want this for large dataset retrievals.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>532/532 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc [setup failure]<br>maxtable [setup failure]<br>systable_locking [setup failure]<br>verify_writes [setup failure]<br>rebuild_table_options [setup failure]<br>cldeadlock [setup failure]<br>incremental_backup_load [setup failure]<br>incremental_backup_usenames [setup failure]<br>sc_force [setup failure]<br>sc_downgrade [setup failure]</p>

**Comment by riverszhang89** [comment]
The test machine ran out of disk drive. Please try again.

**Pull request closed without merging**
