### PR TITLE
Inline functions that are called a lot to gain performance

### PR DESCRIPTION
**Pull request by adizaimi**
Running basic.test in callgrind, shows that functions such as getdatsize(), is_raw(), getdata(), is_remote(), get called hundreds of times for each query (every sqlite3step) and as such it would be much more efficient to inline them.

### CODE REVIEW

**Comment by akshatsikarwar** [comment]
How much difference did this make?

**Comment by adizaimi** [comment]
I think optimization needs to be enabled to see the effects of this, however judging from the profiler percentages, each of these functions weighs about 0.1% of cpu -- any savings can't be that much. [While looking for something else,] I noticed these functions were called 270k times for 3400 sqlite_step(), and that they were not inlined, and thought this seems useful (at least harmless).

**Comment by dorinhogea** [comment]
What was the optimization mode you tested in callgrind initially?

**Comment by akshatsikarwar** [comment]
I'm fine with everything except `db/sqlglue_vdbe.h`

**Comment by dorinhogea** [comment]
If we test this without optimization, it will be misleading.  Compiler should inline some calls already.

**Comment by adizaimi** [comment]
Dorin, agreed. However some of these functions (is_raw, is_remote) are cross library so compiler can not possibly inline them as it needs to export the symbols.

**Comment by adizaimi** [comment]
yep, you are right. pushing fix.

**Comment by adizaimi** [comment]
Thank you Akshat.

**Pull request merged**
