### PR TITLE
Fix sc throttle edge case

### PR DESCRIPTION
**Pull request by riverszhang89**
A convert thread throttles itself when the number of log bytes that have been generated so far is above a threshold. However multiple convert threads can check the current number of log bytes at the same time, all thinking that they need not throttle. The total number of log bytes from all these convert threads, as a result, can be way over the threshold (rebuilding lengthy blob records, for instance).

This patch attempts to fix it. We estimate how much future log traffic an sc tran will generate, and throttle if the number is above the threshold.

### CODE REVIEW

**Comment by riverszhang89** [comment]
The following schema change causes replicants to quickly fall behind
```
create table t(b blob)
insert into t values select randomblob(267386880) from generate_series(1, 20)
rebuild t
```

but is able to throttle and finish nicely on this branch.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Failed to compile.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Failed to compile.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>selectv_rcode<br>ignore_bad_table<br>load_cache_autocache_generated<br>load_cache</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/440 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_resume<br>sc_truncate_lockorder_generated<br>ignore_bad_table<br>load_cache</p>

**Review by markhannum — APPROVED** [review]
Looks great!  Good to merge!

**Comment by riverszhang89** [comment]
@markhannum Thank you so much for the review!

**Pull request merged**
