### PR TITLE
Master version of fix_new_sc_7

### PR DESCRIPTION
**Pull request by markhannum**
Signed-off-by: Mark Hannum <mhannum72@gmail.com>

This is the master version of https://github.com/bloomberg/comdb2/pull/3219

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ schemachange/sc_records.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ util/walkback.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/432 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>socksql_master_swings<br>sc_truncate_lockorder_generated<br>recover_deadlock<br>selectv_rcode</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ schemachange/sc_records.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ util/walkback.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/432 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>recover_ddlk_sp<br>lostwrite<br>selectv_rcode_disable_svonly_nop_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/438 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>logfill<br>sc_truncate<br>phys_rep<br>ignore_bad_table<br>updater_latency<br>sc_downgrade</p>

**Review by riverszhang89 — APPROVED** [review]

**Pull request merged**
