### PR TITLE
Add partial datacopy support through csc2

### PR DESCRIPTION
**Pull request by chands10**
Only copy a subset of fields for datacopy rather than all of them.
Phase 1 includes csc2 support and partial_datacopies system table.
Syntax for csc2 is datacopy(comma separated list of columns to add in datacopy)

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/428 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>instant_sc_logicalsc_generated [core dumped]<br>instant_sc [core dumped]<br>socksql_master_swings<br>sc_partial_datacopy_logicalsc_generated<br>sc_partial_datacopy<br>partial_datacopy</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/428 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>instant_sc_logicalsc_generated [core dumped]<br>instant_sc [core dumped]<br>socksql_master_swings<br>sc_partial_datacopy_logicalsc_generated<br>sc_partial_datacopy<br>partial_datacopy<br>recover_ddlk_sp</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>1/428 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

**Review by mponomar — APPROVED** [review]
Went over changes with Salil.  Looks good to merge.  Would be good to do a couple of 'explain query plan' queries to assert that we're using partial datacopy as a covering index, but those can follow in other PRs.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/433 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_truncate<br>sp_twofiles_generated<br>sp_snapshot_generated<br>sp_queueodh_generated<br>sp<br>recover_ddlk_sp</p>

**Pull request merged**
