### PR TITLE
Fix reqlog logbytes accounting

### PR DESCRIPTION
**Pull request by markhannum**
And don't wait-for-seqnum for a verify-error.  This needs a test still, but I want to run under rr.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>27/479 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_ddl_backout_rowlocks_generated<br>rowlock_update<br>vutf8_rowlocks_off_osql_odh_blob_generated<br>vutf8_rowlocks<br>sc_transactional_rowlocks_generated<br>basic_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>sc_timepart_logicalsc_generated<br>sc_constraints_logicalsc_generated<br>sc_constraints</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>23/479 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>outofrange_queries [setup failure]<br>sc_truncate<br>lostwrite<br>sc_constraints_logicalsc_generated<br>sc_constraints<br>sc_fieldlarger_logicalsc_generated<br>unionpar_maxqueue<br>sc_versmismatch_logicalsc_generated<br>sc_versmismatch<br>sc_repeated_updates_logicalsc_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>23/480 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock<br>sc_timepart_logicalsc_generated<br>queuedb_rollover<br>sc_constraints_logicalsc_generated<br>sc_constraints<br>sc_fieldlarger_logicalsc_generated<br>unionpar_maxqueue<br>sc_versmismatch_logicalsc_generated<br>sc_versmismatch<br>sc_force</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/480 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>lostwrite</p>

**Comment by markhannum** [comment]
I'm letting RR run this again, but this is ready for review.  It addresses an issue that Shruti pointed out earlier this week where the reported 'logbytes' for certain transactions seemed artificially low.  The punchline is that we only ever reported the log bytes of the parent transaction, not the child.

I additionally changed this to account for the logbytes written for aborted transactions.  Although these will have minimal effect on the replicants, it should make the longreqs file a little more readable.  A new testcase, reqlog_logbyte, verifies this logic.

**Review by chands10 — APPROVED** [review]
LGTM

**Pull request merged**
