### PR TITLE
consumer: Fix handling of client controlled txn

### PR DESCRIPTION
**Pull request by akshatsikarwar**
/silent

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/92a1945b/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/340 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>datetime</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/92a1945b/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/92a1945b/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2755'>Resubmit</a></p>

**Review by nirbhayc — APPROVED** [review]
Looks good

**Comment by akshatsikarwar** [comment]
> Looks good

Thank you!

**Comment by akshatsikarwar** [comment]
Also passed robomark:
`cdb2test   Mar 16 20:31:54 2021  in-comdb2db consumer-clnt-txn.R20210316.4`

**Pull request merged**
