### PR TITLE
Fix timepartition tests 

### PR DESCRIPTION
**Pull request by dorinhogea**
A few simple items:
Fix simple_timepartition test (wrong time calculation) 
Example: if you are on Feb 20, and you schedule something 365 days ago, it will happen either on Feb 20 or 21, depending if previous year is leap or not.  So if you test something following a leap year, you get different number of rollouts when you test before the extra day vs after extra day (i.e. if today is March 1, 365 days ago is still March 1 irrespective if the previous year is leap or not; but if it is Feb 5, we get one less rollout following a leap year, since rollout will be scheduled on Feb 6).  Fix for the test is simple, just look 364 days ago so that last rollout always happen after the current testing day. Yes,  datetime math can be hard.

Fix sc_timepart test (regression in tpt sc resume)
There is a 30 min window (in production configuration) between creating the next shard and the time when this shard becomes officially part of a partition.  If there is a schema change scheduled during this time, the next shard needs to be processed too.  When this was fixed, a regression was introduced: since the next shard is not part of the partition yet, a master bounce during schema will require a resume that does not recognized this shard as part of a partition.  Since it is the first shard to be processed during the partition schema change, the current partition shards are not schema changed (in effect, failing to resume the schema change and breaking the partition schema).  Fix is simple, make sure the next shard knows about the future partition, even though it is not part of the partition configuration yet.

Faster "is this table a shard, and if so, what is the partition name" answer
Before this patch, answering the question requires checking the name among all the partition shard names.   Since a shard does not change its partition membership, it makes sense to cache the time partition info inside the shar.   This makes the check instantaneous and allow us to remove a bunch of redundant C&P code that was trying to do the same thing.

Last thing:
During a schema change, we generate a large amount of debug info tracking how old btree files are deleted.  Added a new tunable that stops that spew by default, since we do not have a bug in that code anymore.

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

### CODE REVIEW

**Comment by dorinhogea** [comment]
NOTE: the sc_timepart regression needs to be ported to 7.0

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9ef56526/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/401 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>sc_timepart<br>timepart_auth<br>datetime</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9ef56526/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/9ef56526/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2760'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7538a78/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>datetime<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7538a78/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7538a78/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2760'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7538a78/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7538a78/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>1/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7538a78/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e7538a78/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2760'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/900cf0b7/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>skipscan<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/900cf0b7/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/900cf0b7/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2760'>Resubmit</a></p>

**Review by adizaimi — APPROVED** [review]
Changes look good. I hit resubmit to get another go at the tests, but the last failures seem unrelated to the changes here.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/900cf0b7/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/900cf0b7/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/900cf0b7/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2760'>Resubmit</a></p>

**Comment by riverszhang89** [comment]
but sc_timpart_logicalsc_generated still fails?

**Pull request merged**
