### PR TITLE
Tunable to serialize schema change object in 7.0 format

### PR DESCRIPTION
**Pull request by dorinhogea**
This will allow us to deploy the backward incompatible format in 8.0 to clusters with 7.0.
Details:
When 'sc_7format' is enabled, the wire and disk serialized schema change object is identical with 7.0 code.  The 8.0 replicant sends a 7.0 format and a 8.0 master reads a 7.0 format, but doing the rest of the work with updated structure.
Meanwhile, 7.0 replicants and masters will be able to process the objects with the old code.
Idea is to enable this only on for 7.0 clusters; existing 8.0 clusters need to run with this disabled during the patch deployment.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>495/528 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>rebuild_table_options<br>cldeadlock<br>sc_constraints<br>sc_constraints_logicalsc_generated<br>selectv_deadlock<br>sc_inserts_deletes_partial_index_off_generated<br>sc_inserts_deletes_logicalsc_generated<br>sc_inserts_deletes<br>truncatesc_ufid_on_generated<br>truncatesc</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc_offline_generated<br>sc_downgrade<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables</p>

**Comment by dorinhogea** [comment]
cdb2test   May 28 13:38:50 2024  in-comdb2db save_sc_in_7format.R20240528.2

**Review by mponomar — APPROVED** [review]

**Review by mponomar — APPROVED** [review]

**Comment by dorinhogea** [comment]
@mponomar thank you

**Pull request merged**
