### PR TITLE
Rename struct db to dbtable

### PR DESCRIPTION
**Pull request by adizaimi**

### CODE REVIEW

**Comment by nirbhayc** [comment]
What not rename to 'table'?

**Comment by adizaimi** [comment]
Thought to keep at least some old resemblance. 
Is this ok?

**Comment by nirbhayc** [comment]
Renaming it to table should not need any old resemblance. :) Anyway, that was just an opinion. I am ok with renaming it to dbtable as well. Thank you for taking care of this.

**Comment by adizaimi** [comment]
Thanks Nirbhay. The reason dbtable might be more useful is to allow us to still understand (until fixed) all the references that now look like this:
struct *dbtable db;
somevar->usedb = db;

**Comment by nirbhayc** [comment]
I agree.

**Pull request merged**
