### PR TITLE
Add pmux load test with many queries in parallel

### PR DESCRIPTION
**Pull request by adizaimi**
Add a load-test which performs simple queries in parallel to pmux and
verifies that we get the correct responses within designated timeout.
Also move portmux.py here from [presently removed] portmux test directory
(which was disabled from the time event net was added).

For reference, new parallel query output looks as follows:

```
17:39:33> time /dev/shm/master/build/tests/tools//pmux_queries --pmuxport 19500 --numthreads 10 --iterations 100000 --sp
eedtest

17:39:40> real  0m6.561s
17:39:40> user  0m1.947s
17:39:40> sys   0m5.651s
```
And portmux.py test output looks as follows:
```
17:39:40> + PMUXPORT=19500
17:39:40> + START_PORT=30000
17:39:40> + NUM_PORTS=100
17:39:40> + UNIX_PATH=/tmp/pmux.19500
17:39:40> + portmux.py --failfast --verbose
17:39:40> test_already_active (__main__.Pmux) ... ok
17:39:40> test_empty_cmd (__main__.Pmux) ... ok
17:39:40> test_large_cmd (__main__.Pmux) ... ok
17:39:40> test_max_ports (__main__.Pmux) ... pmux: alloc_port -- exhausted free ports
17:39:40> pmux: alloc_port -- exhausted free ports
17:39:40> ok
17:39:40> test_open_close (__main__.Pmux) ... ok
17:40:03> test_parallel_route (__main__.Pmux) ... ok
17:40:03> test_req_many (__main__.Pmux) ... ok
17:40:05> test_route (__main__.Pmux) ... ok
17:40:05> test_skip_reading_reply (__main__.Pmux) ... ok
17:40:05> test_slow_writer (__main__.Pmux) ... ok
17:40:05> test_svc_not_found (__main__.Pmux) ... ok
17:40:05> test_tcp (__main__.Pmux) ... ok
17:40:05> 
17:40:05> ----------------------------------------------------------------------
17:40:05> Ran 12 tests in 24.798s
17:40:05> 
17:40:05> OK
```

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8193e73a/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/8193e73a/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2804'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>sc_remsql<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dcff02c2/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dcff02c2/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2804'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/cf93fcfe/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/cf93fcfe/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/cf93fcfe/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2804'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/99faec32/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>op_makerecord<br>pmux_sqlite_file_generated<br>pmux_sqlite_memory_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/99faec32/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/99faec32/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2804'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/77ca0125/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/77ca0125/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/77ca0125/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2804'>Resubmit</a></p>

**Review by akshatsikarwar — APPROVED** [review]

**Comment by adizaimi** [comment]
Thank you for review and suggestions Akshat!

**Pull request merged**
