### PR TITLE
Fix startup/replication race

### PR DESCRIPTION
**Pull request by markhannum**
Master version of https://github.com/bloomberg/comdb2/pull/3309

Signed-off-by: Mark Hannum <mhannum72@gmail.com>

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>435/435 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc [setup core dumped]<br>sirace [setup core dumped]<br>maxtable [setup core dumped]<br>incremental_backup_load [setup core dumped]<br>systable_locking [setup core dumped]<br>verify_writes [setup core dumped]<br>socksql_master_swings [setup core dumped]<br>incrementalcopy [setup core dumped]<br>incremental_backup [setup core dumped]<br>odh_blobs [setup core dumped]</p>

**Review by mponomar — APPROVED** [review]

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/435 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>socksql_master_swings<br>reorder_inserts_noreorder_generated<br>sc_downgrade<br>init_sc_race</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/435 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>socksql_master_swings<br>ignore_bad_table<br>load_cache_autocache_generated<br>load_cache_dumpmax_generated<br>load_cache<br>recover_ddlk_sp<br>sc_downgrade</p>

**Review by nirbhayc — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/435 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_downgrade [core dumped]<br>socksql_master_swings<br>sc_truncate<br>ignore_bad_table<br>ddl_no_csc2<br>sc_downgrade</p>

**Pull request merged**
