### PR TITLE
Validate database directory on --create

### PR DESCRIPTION
**Pull request by morgando**
The changes in this PR fail a `--create` if the database directory has an entry that does not fall into one of these categories:
1. Has a name ending with an [accepted extension](https://github.com/bloomberg/comdb2/pull/4376/files#diff-91454b1e6e0271e4ab1900d4829d866b37f219f943ed9864fe0f2f23e4cc91e2R265).
2. Has a name that was explicitly whitelisted with the [`extra_direntries` tunable](https://github.com/bloomberg/comdb2/pull/4376/files#diff-c6ffbd9fb3d6b94c5143be665b399991db0791d8b00bf2c3209a3d210daf2c7aR2148)
3. Has a name that is one of '.' or '..'

The motivation for disallowing preexisting direntries on initialization is to remove ambiguity as to whether files in a database directory were created by the running db or by a previous db that lived in the same directory.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>254/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>schemalk_logicalsc_generated<br>schemalk_extralock_generated<br>phys_rep_tiered_nosource_generated<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>repopulate_queues_twofiles_generated<br>repopulate_queues<br>copyschema_timepart</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>12/529 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>mem_be_nice [setup failure]<br>phys_rep_tiered_nosource_generated<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>sc_repeated_updates<br>repopulate_queues_twofiles_generated<br>repopulate_queues<br>copyschema_timepart<br>qcopy<br>sc_lotsoftables</p>

**Comment by morgando** [comment]
Using #4392 instead

**Pull request closed without merging**
