### PR TITLE
Remove nodeix

### PR DESCRIPTION
**Pull request by markhannum**
This PR removes nodeix, and replaces it with structures hung off of the intern'd strings.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ bdb/rep.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/clienthost.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/509 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>phys_rep_tiered<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover_noroll1_generated<br>lostwrite<br>tunables</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ bdb/rep.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/clienthost.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by mponomar — APPROVED** [review]

**Pull request merged**
