### PR TITLE
Reinstate t10 test, disable t04 for now

### PR DESCRIPTION
**Pull request by adizaimi**
* Reinstating t10 accidentally removed in https://github.com/bloomberg/comdb2/pull/139
* t06 has timing issue so disabling for now.

### CODE REVIEW

**Comment by riverszhang89** [comment]
We probably want to find out why t04 is failing intermittently.

**Comment by ldennis** [comment]
LGTM

**Comment by ldennis** [comment]
Robo test output:
```
16:45:11> > t06_01.sh "" analyze20482 > t06_01.req.res 2>&1
16:45:11> + t06_01.sh '' analyze20482
16:45:12> + [[ -f t06.post ]]
16:45:12> ++ cat t06_01.req.res
16:45:12> + testcase_output='1c1
16:45:12> < (out='\''[ERROR] Analyze is not running [or not running on this node].'\'')
16:45:12> ---
16:45:12> > (out='\''Abort ongoing analyze'\'')
16:45:12> FAILED abort output'
16:45:12> ++ cat t06_01.req.out
16:45:12> + expected_output=SUCCESS
16:45:12> + [[ 1c1
16:45:12> < (out='[ERROR] Analyze is not running [or not running on this node].')
16:45:12> ---
16:45:12> > (out='Abort ongoing analyze')
16:45:12> FAILED abort output != \S\U\C\C\E\S\S ]]
```

Looks like I was wrong and the test failure does not seem to be related to t04

**Comment by adizaimi** [comment]
Yeah, in t04 we do put back the parameters. I have seen this failure in clustered test, but never in standalone. Will look more.

**Comment by akshatsikarwar** [comment]
OH WOW

**Pull request merged**
