### PR TITLE
Fix race between dbqueue_admin thread and perform_trigger_update_int

### PR DESCRIPTION
**Pull request by markhannum**
I am seeing this crash occur periodically in the sp test:

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fa734408859 in __GI_abort () at abort.c:79
#2  0x0000562c5cb66145 in __db_check_txn (dbp=0x7fa72b8c41a8, txn=0x0, assoc_lid=0, read_op=1) at ../berkdb/common/db_err.c:599
#3  0x0000562c5cb768c0 in __db_cursor_pp_real (dbp=0x7fa72b8c41a8, txn=0x0, txn_clone=0x0, dbcp_old=0x0, lid_clone=0, dbcs=0x0, dbcp=0x7fa729dddb98, flags=0, countmein=1) at ../berkdb/db/db_iface.c:570
#4  0x0000562c5cb765a1 in __db_cursor_ser_pp (dbp=0x7fa72b8c41a8, txn=0x0, dbcs=0x0, dbcp=0x7fa729dddb98, flags=0) at ../berkdb/db/db_iface.c:440
#5  0x0000562c5cb767d4 in __db_cursor_pp (dbp=0x7fa72b8c41a8, txn=0x0, dbcp=0x7fa729dddb98, flags=0) at ../berkdb/db/db_iface.c:528    
#6  0x0000562c5cab5ce3 in bdb_queuedb_get (bdb_state=0x562c61737d80, consumer=0, prevcursor=0x0, fnd=0x7fa729dddde8, fnddtalen=0x7fa729ddddf0, fnddtaoff=0x7fa729ddddf8, fndcursor=0x0, epoch=0x0, bdberr=0x7fa729dddd84) at ../bdb/queuedb.c:567
#7  0x0000562c5cab313a in bdb_queue_get (bdb_state=0x562c61737d80, consumer=0, prevcursor=0x0, fnd=0x7fa729dddde8, fnddtalen=0x7fa729ddddf0, fnddtaoff=0x7fa729ddddf8, fndcursor=0x0, epoch=0x0, bdberr=0x7fa729dddd84) at ../bdb/queue.c:1712
#8  0x0000562c5c8454af in dbq_get (iq=0x7fa729ddde20, consumer=0, prevcursor=0x0, fnddta=0x7fa729dddde8, fnddtalen=0x7fa729ddddf0, fnddtaoff=0x7fa729ddddf8, fndcursor=0x0, epoch=0x0) at ../db/glue.c:5470
#9  0x0000562c5c9b52dc in dbqueue_get_front_genid (table=0x562c61782350, consumer=0) at ../plugins/dbqueuedb/dbqueuedb.c:395       
#10 0x0000562c5c9b548e in dbqueue_check_inactivity (consumer=0x7fa728b9ee98) at ../plugins/dbqueuedb/dbqueuedb.c:429
#11 0x0000562c5c9b5859 in admin (dbenv=0x562c5eefc490, tran=0x0, type=4) at ../plugins/dbqueuedb/dbqueuedb.c:497
#12 0x0000562c5c816d3c in dbqueuedb_admin (dbenv=0x562c5eefc490, tran=0x0) at ../db/dbqueuedb.c:31
#13 0x0000562c5c7eaed6 in purge_old_blkseq_thread (arg=0x562c5eefc490) at ../db/comdb2.c:1202
#14 0x00007fa7345e0609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007fa734505163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

  The “punchline” is that dbp->lid is not in transaction range in the core: this queue was just added, and the queue-add code on the master adds the queue to thedb->qdbs array before this transaction is committed.  So there’s a period of time that the table in thedb->qdbs will be part of an uncommitted transaction, and will therefore have a dbp->lid in the transactional range.  Fix is to introduce a flag that tells admin thread to skip this while it's being added

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Comment by akshatsikarwar** [comment]
Is it possible to delay adding to the array?

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: Success &#10003;.</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
@@ db/appsock_handler.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/handle_buf.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/fdb_bend.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/prefault_helper.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/sqlglue.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ schemachange/sc_global.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/logmsg.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ util/walkback.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ berkdb/rep/rep_record.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/btree/bt_rec.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ csc2/macc_so.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlinterfaces.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/osqlcheckboard.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/dohsql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/eventlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/appsock_handler.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/trigger.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/fdb_boots.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_metrics.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/db_fingerprint.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/sqlglue.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ net/net.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ schemachange/sc_global.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/glue.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/353 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk_logicalsc_generated [core dumped]<br>updater_latency<br>selectv_rcode_fcommit_dselectv_generated</p>

**Pull request merged**
