### PR TITLE
Only add to clntlru if ref > 0 initially

### PR DESCRIPTION
**Pull request by chands10**
Used to be possible to add to this list if got to < 0, which means that it could be added twice, once at 0, once at < 0

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/520 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>prepare</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/525 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>op_makerecord<br>cdb2sql_queueodh_generated<br>cdb2sql<br>sc_swapfields_logicalsc_generated<br>truncatesc_offline_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/525 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>truncatesc_offline_generated<br>truncatesc_ufid_on_generated</p>

**Review by mponomar — APPROVED** [review]

**Review by morgando — APPROVED** [review]
Approved -- It makes sense to not add a record to the lru list multiple times when its refcount somehow becomes negative. Let's also investigate to make sure that these records never have a negative refcount.

**Comment by chands10** [comment]
Thanks Mike and Morgan!!

**Pull request merged**
