### PR TITLE
Initialize newsqlheader and other structures with zero bytes

### PR DESCRIPTION
**Pull request by adizaimi**
Initialize newsqlheader and other structures with zero bytes

### CODE REVIEW

**Comment by riverszhang89** [comment]
Let's preserve the authorship of the original commit.

**Comment by riverszhang89** [comment]
For example: https://github.com/bloomberg/comdb2/commit/3c22c64357da402c92f1c345515a1ab10c447798

**Comment by adizaimi** [comment]
Good point. Entered separate PR https://github.com/bloomberg/comdb2/pull/1452. 
Thanks Rivers.

**Pull request merged**
