### PR TITLE
fix mem leak in fdb_sqlite_get_schema

### PR DESCRIPTION
**Pull request by mohitkhullar**
Use xFree until we share schemas in fdb_sqlite_get_schema

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/525 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>cdb2sql<br>cdb2sql_queueodh_generated<br>truncatesc<br>truncatesc_offline_generated<br>truncatesc_ufid_on_generated</p>

**Review by dorinhogea — APPROVED** [review]
lgtm! thank you

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>11/527 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>sc_truncate<br>schemalk_logicalsc_generated<br>schemalk<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>pmux_sqlite_memory_generated<br>pmux_sqlite_file_generated<br>sc_downgrade<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/528 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>schemalk_extralock_generated<br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>transchunk_manyins<br>truncatesc_offline_generated</p>

**Pull request merged**
