### PR TITLE
Stat4 updates {DRQS 170024958}

### PR DESCRIPTION
**Pull request by akshatsikarwar**
Cherrypick various upstream improvements.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
/silent

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>verify_writes<br>ignore_bad_table<br>yast_stat4scan_generated<br>yast<br>load_cache_dumpmax_generated<br>load_cache<br>load_cache_autocache_generated<br>reorder_inserts_noreorder_generated<br>basic_rowset_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ignore_bad_table<br>yast_stat4scan_generated<br>yast<br>load_cache<br>sc_downgrade</p>

**Review by markhannum — DISMISSED** [review]
Good to merge!

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/442 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sql_func_mem_leak<br>ignore_bad_table<br>weighted_standing_queue<br>load_cache_autocache_generated<br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by markhannum — APPROVED** [review]

**Pull request merged**
