### PR TITLE
create directory in test setup for mac builds

### PR DESCRIPTION
**Pull request by RohanNankani**

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/559 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>schemalk<br>selectv_rcode<br>timepart_trunc<br>dbcreate<br>truncatesc_offline_generated</p>

**Comment by morgando** [comment]
Passes our test suite -- `cdb2test   Jul  3 10:42:20 2024  in-comdb2db rohan/create-directory.R20240703.4`

**Review by morgando — APPROVED** [review]
The `realpath` mac implementation fails if the path passed to it doesn't exist. This was causing the setup script to fail. The change in this PR fixes this issue. LGTM!

**Pull request merged**
