### PR TITLE
block partitioning a table that is the target of a constraint

### PR DESCRIPTION
**Pull request by dorinhogea**
Per title.

### CODE REVIEW

**Comment by chands10** [comment]
Maybe add a test starting with a time partition t21 and normal table t22 and try adding a constraint in t22 on t21 as well?

**Comment by dorinhogea** [comment]
That case is already blocked, it fails with " A foreign key cannot refer to a time partition",
Here:
https://github.com/bloomberg/comdb2/blob/122334353ff59c80f88d372d814c21bfa8a73281/db/constraints.c#L2203

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/580 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>autoanalyze [setup failure]<br>snap_ha_retry_newsi_generated<br>auth<br>dbcreate</p>

**Comment by chands10** [comment]
Sounds good!

**Review by chands10 — APPROVED** [review]

**Comment by dorinhogea** [comment]
@chands10 thank you!

**Pull request merged**
