### PR TITLE
Msg subsystem v4

### PR DESCRIPTION
**Pull request by jmleddy**

### CODE REVIEW

**Comment by riverszhang89** [comment]
What's the secret change to fix bulk_overflow crash?

**Comment by jmleddy** [comment]
No secret, just better build and tests.

**Comment by jmleddy** [comment]
> Needs utility to dump/(replay?) $dbname.sqllog

less?

**Comment by mponomar** [comment]
$dbname.sqllog is a binary log (protobuf events).  Your sql log is text, less is great there.  I was wondering if we need the text log.

**Comment by jmleddy** [comment]
Well we have replay and a viewer for the text log, so it's more featureful at this point. If redundancy is the issue, I don't think we need the sqllog.

**Comment by jmleddy** [comment]
Since the tests passed, I'm going to merge this for now. If we need to, we can revisit the conversation about getting text output of the sqlllog and whether it's worth it to keep one or the other.

**Comment by mponomar** [comment]
We wanted logging for a couple of reasons.  One is the ability to replay queries (for testing, for QA, for performance tests, whatever).  That's easy to do with the protobuf log.  It's perfectly possible with a text log, but it needs more work (eg: need a clean way to log bound parameter values, escape things, etc.).  Another is to track performance metrics (per query and overall) and pass them to other systems for analysis.  Again, easier with a structured log.  Up to you.  I know binary logs aren't well liked, but if we had an easy utility to dump the data, I think we'd do better.

**Comment by jmleddy** [comment]
I hate structured logs personally, but if you insist I can transition over to them. I think we ought to be consistent though, moving trc.c and statsreqs over too. In any case, escaping sql should not be an issue today, as it starts at `sql=` and ends at `\n`. Everything in between is literal. I admit I haven't tried bound parameters yet.

**Comment by jmleddy** [comment]
Also I don't think it's easier to track performance metrics with a structured log.

**Comment by mponomar** [comment]
trc.c is a debugging log.  statreqs would go away if we log the same information in your log.

>> Also I don't think it's easier to track performance metrics with a structured log.

Fair enough.  I was stretching my point a bit.  It's easier to pass them to another system.  Arguably.

**Comment by mponomar** [comment]
(longreqs also goes away)

**Comment by mponomar** [comment]
Also I don't insist.  As long as we're able to identify which metrics go with which events, and have some consistent format that's easy to parse, text is fine.  My only argument is that structured log gets you that for free (yay, no parsing).

**Comment by adizaimi** [comment]
Can we have a setting, and the log can be structured or text as user wishes based on that?

**Pull request merged**
