### PR TITLE
sqlwriter: Direct write for small messages

### PR DESCRIPTION
**Pull request by akshatsikarwar**
/silent

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>481/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sirace [setup failure]<br>cldeadlock [setup failure]<br>truncatesc [setup failure]<br>socksql_master_swings [setup failure]<br>maxtable [setup failure]<br>systable_locking [setup failure]<br>incremental_backup_load [setup failure]<br>verify_writes [setup failure]<br>sc_force [setup failure]<br>sc_downgrade [setup failure]</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>481/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock [setup failure]<br>sirace [setup failure]<br>truncatesc [setup failure]<br>socksql_master_swings [setup failure]<br>maxtable [setup failure]<br>systable_locking [setup failure]<br>incremental_backup_load [setup failure]<br>verify_writes [setup failure]<br>sc_force [setup failure]<br>sc_downgrade [setup failure]</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>481/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sirace [setup failure]<br>truncatesc [setup failure]<br>cldeadlock [setup failure]<br>socksql_master_swings [setup failure]<br>maxtable [setup failure]<br>systable_locking [setup failure]<br>incremental_backup_load [setup failure]<br>verify_writes [setup failure]<br>sc_force [setup failure]<br>sc_downgrade [setup failure]</p>

**Comment by akshatsikarwar** [comment]
Temporarily disable perf and mark robots

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>22/22 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock [setup failure]<br>sirace [setup failure]<br>truncatesc_ufid_on_generated [setup failure]<br>truncatesc [setup failure]<br>truncatesc_offline_generated [setup failure]<br>socksql_master_swings [setup failure]<br>maxtable [setup failure]<br>systable_locking [setup failure]<br>incremental_backup_load [setup failure]<br>verify_writes [setup failure]</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>22/22 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sirace [setup failure]<br>cldeadlock [setup failure]<br>truncatesc_ufid_on_generated [setup failure]<br>truncatesc [setup failure]<br>truncatesc_offline_generated [setup failure]<br>socksql_master_swings [setup failure]<br>maxtable [setup failure]<br>systable_locking [setup failure]<br>incremental_backup_load [setup failure]<br>verify_writes [setup failure]</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>22/22 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sirace [setup failure]<br>cldeadlock [setup failure]<br>truncatesc_ufid_on_generated [setup failure]<br>truncatesc [setup failure]<br>truncatesc_offline_generated [setup failure]<br>socksql_master_swings [setup failure]<br>maxtable [setup failure]<br>systable_locking [setup failure]<br>incremental_backup_load [setup failure]<br>verify_writes [setup failure]</p>

**Comment by akshatsikarwar** [comment]
Opening a new pr with all robots enabled

**Pull request closed without merging**
