### PR TITLE
pmux.cpp: Remove duplicate if check.

### PR DESCRIPTION
**Pull request by levinem**
This is a logic check improvement/change.
Rather than running `if (c.writable && svc != nullptr)` followed immediately by the already verified `if (svc != nullptr)`, this PR removes the 2nd check and merges the code into the main `if (c.writable && svc != nullptr)` block.
The current behavior involves doing a 2nd check on the 2nd half of a previously if statement's compound boolean check. Removing this 2nd already verified check should help simplify the code and perhaps even speed up the processing.

### CODE REVIEW

**Comment by levinem** [comment]
@markhannum , what command should I run in my local comdb2 directory to run the test suite?  I tried `./runtests` but it may not be working for me.

**Comment by levinem** [comment]
I found the tests/README f

**Comment by adizaimi** [comment]
The /runtests flag is for our internal testsuite runner. 
You can just go to your comdb2 src dir and make the project and test-tools:
```path_to_comdb2_src > mkdir build; cd build; cmake ../ ; make ; make test-tools ```
and then go to the tests directory and run any of the tests, such as basic:
```path_to_comdb2_src/tests > make basic```

**Comment by adizaimi** [comment]
It passes manually the test for me too. If you don't have anything else to add to this pull request, I will merge it. Let me know. Thanks.

**Comment by levinem** [comment]
I ran clang-format on it, no other changes though.  Thanks @adizaimi , @markhannum , and @roborivers !

**Comment by levinem** [comment]
No problem, glad I could help!

**Pull request merged**
