### PR TITLE
Fix ufid abort in rep-verify-match

### PR DESCRIPTION
**Pull request by riverszhang89**
See the newly added test for an explanation of the issue.

(DRQS 170183635)

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep<br>ignore_bad_table<br>ufid_recovery</p>

**Review by markhannum — DISMISSED** [review]
Approved!  Thanks Rivers!

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>ufid_recovery<br>load_cache_dumpmax_generated<br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>9/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts<br>sql_datetime_interval_arithmetic_leak<br>phys_rep<br>ignore_bad_table<br>weighted_standing_queue<br>ufid_recovery<br>load_cache_dumpmax_generated<br>load_cache<br>load_cache_autocache_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>ignore_bad_table<br>ufid_recovery<br>load_cache<br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ berkdb/dbreg/dbreg_util.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/441 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>ignore_bad_table<br>downgrade<br>selectv_rcode<br>selectv_rcode_disable_svonly_nop_generated</p>

**Review by markhannum — APPROVED** [review]
good to merge!

**Comment by riverszhang89** [comment]
@markhannum Thank you for the review!

**Pull request merged**
