### PR TITLE
fix comdb2_tables to respect table aliasing

### PR DESCRIPTION
**Pull request by dorinhogea**
Currently if we have a lightweight renamed file (i.e. sql aliased), comdb2_tables displays the old name.

$ c "select * from comdb2_tables"
(tablename='sqlite_stat1')
(tablename='sqlite_stat4')
(tablename='t')
$ c "select name from sqlite_master"
(name='sqlite_stat1')
(name='sqlite_stat4')
(name='t2')

Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>instant_sc<br>upsert</p>

**Review by mponomar — DISMISSED** [review]

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
```

**Review by mponomar — APPROVED** [review]

**Comment by dorinhogea** [comment]
Thank you Mike!

**Pull request merged**
