### PR TITLE
Tunables refactoring: 2nd iteration

### PR DESCRIPTION
**Pull request by nirbhayc**
- Move config-related code to db/config.c
- Cleanup pre- & dynamic tunables
- More tests

### CODE REVIEW

**Comment by ldennis** [comment]
Overall it looks good. Do you mind moving the int switches to a better place as well? And another thing is that I am not sure how many internal users are depending on LRLs like "disable_\*"/"enable_\*". We may want to check with DBAs in the future to further refactor those into switches (or whatever cleaner).

**Comment by nirbhayc** [comment]
@ldennis Right. Switches are, more or less, already implemented in a separate unit, and in order to be backward compatible - allow the use of "on/off <switch-name>" in lrl and in sys.cmd.send() at runtime - I think, for the time being, it's ok to leave them as is. We should replace/deprecate enable/disable/do/dont tunables in favor of single boolean tunable, so that they can be removed in some future version.

**Comment by riverszhang89** [comment]
You forgot to adjust analyze test output. Please make sure all tests are passing before merging.

**Comment by nirbhayc** [comment]
@riverszhang89 Thanks for the fix.

**Comment by riverszhang89** [comment]
No problem!

**Pull request merged**
