### PR TITLE
{171831761}: Fixing remsql and chunk-txn

### PR DESCRIPTION
**Pull request by riverszhang89**
A remote write in a chunk transacion would hang the source database. This patch fixes it.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/472 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep<br>sc_timepart_logicalsc_generated<br>remsql<br>ddl_analyze</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/472 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock<br>logfill_logput_window_generated<br>sc_timepart_logicalsc_generated</p>

**Review by dorinhogea — APPROVED** [review]
Looks good to me! Thank you

**Comment by riverszhang89** [comment]
@dorinhogea Thanks for the review, Dorin!

**Pull request merged**
