### PR TITLE
Collect transaction before acquiring locks

### PR DESCRIPTION
**Pull request by markhannum**
Signed-off-by: Mark Hannum <mhannum72@gmail.com>

Collect a transaction before acquiring locks

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by mponomar — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>419/452 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>odh_blobs<br>scindex_logicalsc_generated<br>sc_constraints<br>scindex<br>systable_locking<br>incremental_backup_usenames<br>sc_inserts_deletes_logicalsc_generated<br>sc_inserts_deletes_partial_index_off_generated<br>incremental_backup<br>sc_inserts_deletes</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/452 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>updater_latency<br>selectv_rcode</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>11/452 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>maxtable [core dumped]<br>updcolsbug<br>sc_truncate<br>sc_transactional_rowlocks_generated<br>yast<br>maxtable<br>triggersc_latency<br>tmptbl<br>sc_repeated_updates<br>sc_lotsoftables_logicalsc_generated</p>

**Review by mponomar — DISMISSED** [review]

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/454 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>yast_stat4scan_generated<br>yast</p>

**Pull request merged**
