### PR TITLE
Add set_snapshot_impl tunable

### PR DESCRIPTION
**Pull request by morgando**
Depends on #4575

The changes in this PR add the tunable `set_snapshot_impl`, which allows database owners to set their preferred snapshot implementation.

After these changes, database owners should configure snapshot by:
1. Setting the snapshot implementation to a non-default with `set_snapshot_impl <implname>`.
2. Enabling snapshot isolation with `enable_snapshot_isolation`.

The changes in this PR also remove the `use_modsnap_for_snapshot` tunable since this tunable is not currently used and `set_snapshot_impl` should be preferred over it.

### CODE REVIEW

**Comment by morgando** [comment]
Add tunable to docs.

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>selectv_rcode<br>truncatesc</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/402 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>replay_history<br>analyze_exit_immediately<br>op_makerecord<br>truncatesc</p>

**Review by markhannum — DISMISSED** [review]

**Review by markhannum — APPROVED** [review]

**Comment by morgando** [comment]
`cdb2test   Jul 31 14:59:33 2024  in-comdb2db refactor_snapshot_tunables.R20240731.7`

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>sc_resume_logicalsc_generated<br>sc_resume<br>sc_transactional_rowlocks_generated<br>analyze_partial_index_off_generated<br>sys_cmd_access</p>

**Pull request merged**
