### PR TITLE
Don't expose appsock error code 8.0

### PR DESCRIPTION
**Pull request by chands10**
8.0 version of https://github.com/bloomberg/comdb2/pull/4803

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/558 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>mem_protobuf<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/559 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fdb_push [setup failure]<br>truncatesc_offline_generated<br>dbcreate</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/558 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_inserts_logicalsc_generated [setup failure]<br>fdb_push [setup failure]<br>analyze_fastinit_race<br>phys_rep_tiered_nosource_generated<br>sp_queueodh_generated<br>op_makerecord<br>truncatesc_offline_generated<br>dbcreate</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/558 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_lotsoftables_logicalsc_generated [setup failure]<br>union_parallel<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/558 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite<br>sc_downgrade<br>truncatesc_offline_generated<br>ssl_remsql_fdbpush_generated</p>

**Comment by chands10** [comment]
cdb2test   Nov 11 15:48:34 2024  in-comdb2db appsock_error_code_2_8.0.R20241111.0

**Review by morgando — APPROVED** [review]

**Pull request merged**
