### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by akshatsikarwar**

### CODE REVIEW

**Comment by riverszhang89** [comment]
Does the pull request fix up all compiler warnings?

**Comment by akshatsikarwar** [comment]
> Does the pull request fix up all compiler warnings?
Depends on compiler and compile time options. Reduces quite a bit.

**Comment by akshatsikarwar** [comment]
Feels like last two commits introduced as many warnings as this one fixes.

**Comment by riverszhang89** [comment]
woah

**Pull request closed without merging**
