### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by mponomar**
Change the sqlloging system.  Log in JSON instead of protobufs, so it's usable without filter programs

### CODE REVIEW

**Comment by mponomar** [comment]
Work in progress.  Pull request for comments.  Needs:

- Change params to have the same format as consumer JSON format
- Compute fingerprints for other statement types (only SELECT for now)

**Comment by jmleddy** [comment]
Roborivers hasn't picked up yet

**Comment by mponomar** [comment]
Everything is definitely not built optimized.  At least cson wasn't.

**Comment by jmleddy** [comment]
My mistake, Akshat enabled `OPT_CFLAGS` but forgot to add this to `CFLAGS`

**Comment by mponomar** [comment]
We wanted to not compile everything optimized until we're ready to slap a release number on it, no?

**Comment by akshatsikarwar** [comment]
Optimization was disabled.

**Comment by jmleddy** [comment]
Why?

**Comment by akshatsikarwar** [comment]
Some clustered tests were failing.

**Comment by jmleddy** [comment]
Oh okay. My only thing with white-listing optimizations like this is it makes it harder for users to control the optimization level for the project. But I guess as long as we keep track of this it shouldn't be hard to remove later once we optimize everything.

**Comment by akshatsikarwar** [comment]
Remove for now. No need to keep track. We can enable once for everything when ready.

**Comment by jmleddy** [comment]
No I mean remove the per-file optimizations once we're optimizing everything.

**Comment by akshatsikarwar** [comment]
Saying the same thing. No need to have per file optimization. Remove it.

**Comment by mponomar** [comment]
Sure, why not.  It's premature.

**Comment by riverszhang89** [comment]
```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64
error: Installed (but unpackaged) file(s) found:
   /opt/bb/bin/cdb2_sqlreplay
    File listed twice: /opt/bb/include/cdb2api.h
    Installed (but unpackaged) file(s) found:
   /opt/bb/bin/cdb2_sqlreplay

RPM build errors:
make: *** [rpm-current] Error 1
The command '/bin/sh -c make rpm-current && rpm -i ${HOME}/rpmbuild/RPMS/*/comdb2*.rpm' returned a non-zero code: 2
Makefile:12: recipe for target 'build-rpm' failed
make: *** [build-rpm] Error 2
```

**Comment by jmleddy** [comment]
What that mean?

**Comment by riverszhang89** [comment]
smokey and cloudy

**Comment by mponomar** [comment]
I removed cdb2_sqlreplay from the spec (because it was part of the multicall binary, and got linked into place).  But then I removed it from multicall, but didn't add it back to the spec.  Last commit fixes `this.`

 ```
./testdbs rpmtest
Getting config
Getting config
Getting config
Trying db1
Ok.
Trying db2
Ok.
Trying db3
Ok.
Trying db4
Ok.
Trying db5
Ok.
```

**Comment by jmleddy** [comment]
Huh:

```
install -D contrib/comdb2admin/supervisord_cdb2.conf /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/opt/bb/etc/supervisord_cdb2.conf
install -D contrib/comdb2admin/comdb2admin /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/opt/bb/bin/comdb2admin
[ -z "/root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64" ] && . db/installinfo || true
make[1]: Leaving directory `/root/rpmbuild/BUILD/comdb2-7.0.0pre'
[91m+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /root/rpmbuild/BUILD/comdb2-7.0.0pre
[0mextracting debug info from /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/opt/bb/bin/cdb2_sqlreplay
extracting debug info from /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/opt/bb/bin/pmux
extracting debug info from /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/opt/bb/bin/comdb2ar
extracting debug info from /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/opt/bb/bin/comdb2
extracting debug info from /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/opt/bb/lib/libcdb2api.so
/usr/lib/rpm/sepdebugcrcfix: Updated 5 CRC32s, 0 CRC32s did match.
[91mcpio: comdb2-7.0.0pre/<stdout>: Cannot stat: No such file or directory
[0m[91mcpio: comdb2-7.0.0pre/y.tab.c: Cannot stat: No such file or directory
[0m[91m40197 blocks
[0m[91m+ /usr/lib/rpm/check-buildroot
[0m[91m+ /usr/lib/rpm/redhat/brp-compress
[0m[91m+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
[0m[91m+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
[0m[91m+ /usr/lib/rpm/redhat/brp-python-hardlink
[0m[91m+ /usr/lib/rpm/redhat/brp-java-repack-jars
[0mProcessing files: comdb2-7.0.0pre-1.el7.centos.x86_64
[91merror: File not found: /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/lib/systemd/system/pmux.service
error: File not found: /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/lib/systemd/system/cdb2sockpool.service
error: File not found: /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/lib/systemd/system/supervisor_cdb2.service
error: File not found: /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/usr/local/lib/pkgconfig/cdb2api.pc
    File not found: /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/lib/systemd/system/pmux.service
    File not found: /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/lib/systemd/system/cdb2sockpool.service
    File not found: /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/lib/systemd/system/supervisor_cdb2.service
    File not found: /root/rpmbuild/BUILDROOT/comdb2-7.0.0pre-1.el7.centos.x86_64/usr/local/lib/pkgconfig/cdb2api.pc
[0m

RPM build errors:
[91mmake: *** [rpm-current] Error 1
[0mThe command '/bin/sh -c make rpm-current && rpm -i ${HOME}/rpmbuild/RPMS/*/comdb2*.rpm' returned a non-zero code: 2
Makefile:12: recipe for target 'build-rpm' failed
make: *** [build-rpm] Error 2
```

**Comment by jmleddy** [comment]
Should we rebase without `acc859f` and my apply/revert and try again? Undoing multicall is proving to be more effort than its worth, and it isn't even related to logging.

**Comment by mponomar** [comment]
Ok - this needs more work before merging.  James and I are working on it still, so no reason to keep this open.

**Pull request closed without merging**
