### PR TITLE
Add more info in anonymous access

### PR DESCRIPTION
**Pull request by mohitkhullar**
Signed-off-by: mohitkhullar <mkhullar1@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/444 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sp_queueodh_generated<br>sql_datetime_interval_arithmetic_leak<br>ignore_bad_table<br>weighted_standing_queue<br>datacopy</p>

**Review by markhannum — APPROVED** [review]
Good to merge

**Comment by mohitkhullar** [comment]
"identity=bpi:anonymous:argv0:comdb2sql"

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/444 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>ignore_bad_table<br>reorder_inserts_noreorder_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/444 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ignore_bad_table<br>updater_latency<br>load_cache_autocache_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/444 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ignore_bad_table<br>load_cache_dumpmax_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/444 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>ignore_bad_table<br>updater_latency<br>weighted_standing_queue<br>basic_off_osql_odh_blob_generated</p>

**Pull request merged**
