### PR TITLE
ALTER: Add syntax to change table properties

### PR DESCRIPTION
**Pull request by nirbhayc**

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by dorinhogea — APPROVED** [review]
LGTM!

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/468 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>tunables</p>

**Comment by nirbhayc** [comment]
Thanks for looking @dorinhogea !

**Pull request merged**
