### PR TITLE
Delete sbuf net

### PR DESCRIPTION
**Pull request by akshatsikarwar**
/plugin-branch del-sbuf-net

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/569 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_fdbpush_generated [setup failure]<br>vutf8_rowlocks_off_osql_odh_blob_generated [setup failure]<br>sc_transactional_rowlocks_generated<br>truncatesc</p>

**Comment by akshatsikarwar** [comment]
```
cdb2test   Aug 16 15:27:21 2024  in-comdb2db del-sbuf-net.R20240816.3
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/565 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>basic_sslnoproto_generated [setup failure]<br>biginplace [setup failure]<br>sc_transactional_rowlocks_generated<br>analyze_exit_immediately<br>auth</p>

**Review by markhannum — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/571 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_redo_step [setup failure]<br>leakcheck [setup failure]<br>sc_resume<br>auth</p>

**Pull request merged**
