### PR TITLE
Add system table to track table activity.

### PR DESCRIPTION
**Pull request by mponomar**
Track basic operation counts on per-table basis.  Presents comdb2_table_hits system table as an interface.

### CODE REVIEW

**Comment by akshatsikarwar** [comment]
Does this track queues and/or queuedbs?

**Comment by mponomar** [comment]
Nope, just plain old boring tables.

**Comment by akshatsikarwar** [comment]
can haz?

**Comment by akshatsikarwar** [comment]
maybe just queuedb?

**Comment by mponomar** [comment]
Sure, but it should probably be a different table.  Operations are different (put/consume).

**Comment by akshatsikarwar** [comment]
meh - insert/delete conveys same information

**Comment by mponomar** [comment]
Fair enough.  Also going to move the tracking inside record.c.  Originally wanted it here so we wouldn't double-count on transaction replays.  Don't know how important an accurate count should be.

**Comment by akshatsikarwar** [comment]
inaccurate count seems work fine for autoanalyze so far..

**Comment by adizaimi** [comment]
But who tracks the trackers?

**Pull request closed without merging**
