### PR TITLE
Remove deprecated bdb_sqlstat1.h

### PR DESCRIPTION
**Pull request by adizaimi**
Remove deprecated bdb_sqlstat1.h and the corresponding
deprecated implementations of same funcitons in llmeta.c

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/397 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume [core dumped]<br>sc_timepart_logicalsc_generated<br>backup_logfiles</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dd8a7814/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dd8a7814/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2675'>Resubmit</a></p>

**Review by roborivers — COMMENTED** [review]
<p>Sysbench Transactions Per Second (commit: dd8a7814):</p>

<pre lang=diff>
@@ sysbench/bulk_insert @@
-4.77%
</pre>

**Review by roborivers — APPROVED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dd8a7814/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/dd8a7814/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2675'>Resubmit</a></p>

**Review by roborivers — COMMENTED** [review]
<p>Sysbench Transactions Per Second (commit: dd8a7814):</p>

<pre lang=diff>
@@ sysbench/select_random_points @@
-6.98%
</pre>

**Review by akshatsikarwar — APPROVED** [review]

**Comment by adizaimi** [comment]
Thank you Akshat!

**Pull request merged**
