### PR TITLE
Store query data in cache

### PR DESCRIPTION
**Pull request by mohitkhullar**
/plugin-branch fix_hint_queries

Signed-off-by: Mohit Khullar <mohit.khullar@gmail.com>

### CODE REVIEW

**Review by roborivers — APPROVED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/85de68d/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/85de68d/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2482'>Resubmit</a></p>

**Comment by mohitkhullar** [comment]
reviewed here https://github.com/bloomberg/comdb2/pull/2438

**Comment by mohitkhullar** [comment]
Candidate fix_hint_queries_2.R20200914.3 test  params               ibm   from ibm     host -> success.
Candidate fix_hint_queries_2.R20200914.3 test  params               linux from ibm     host -> success.
Candidate fix_hint_queries_2.R20200914.3 test  params               sundev1 from ibm     host -> success.

**Pull request merged**
