### PR TITLE
Fix cmake warnings

### PR DESCRIPTION
**Pull request by nirbhayc**
Also add check for 'tinfo' library.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

### CODE REVIEW

**Comment by adizaimi** [comment]
Does this fix the linux warnings, and works in macos?

**Comment by nirbhayc** [comment]
> Does this fix the linux warnings, and works in macos?

Yes, it fixes linux cmake warnings. Not sure about macos.

**Comment by akshatsikarwar** [comment]
Where do you see the warnings?

**Comment by nirbhayc** [comment]
Cherry-picked to 7.0.

**Comment by nirbhayc** [comment]
@adizaimi @akshatsikarwar thank you guys!

**Pull request merged**
