### PR TITLE
fix bound param fdb push

### PR DESCRIPTION
**Pull request by dorinhogea**
Attempt 100?

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>7/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>sc_transactional_rowlocks_generated<br>phys_rep_tiered<br>incremental_backup_usenames<br>queuedb_rollover_noroll1_generated<br>sc_repeated_updates<br>sys_cmd_access</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered<br>queuedb_rollover</p>

**Review by chands10 — APPROVED** [review]
LGTM

**Comment by dorinhogea** [comment]
Thank you Salil!

**Pull request merged**
