### PR TITLE
Honor watchthreshold

### PR DESCRIPTION
**Pull request by riverszhang89**
Use a tunable rather than a hard-coded value for the watchdog timer of bdb rep watcher thread.

(DRQS 164795546)

### CODE REVIEW

**Review by nirbhayc — DISMISSED** [review]
Looks good Rivers! Could you also add a line to the tunable's description https://github.com/bloomberg/comdb2/blob/master/db/db_tunables.h#L1205?

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5d0da671/smoketest.log'>Error &#x26A0; </a>.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/394 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>timepart_auth<br>logfill</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5d0da671/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5d0da671/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2629'>Resubmit</a></p>

**Comment by nirbhayc** [comment]
timepart_auth failure must be linked to 2020 -> 2021.

**Review by nirbhayc — APPROVED** [review]

**Comment by riverszhang89** [comment]
Thank you for the review, Nirbhay!

**Pull request merged**
