### PR TITLE
build update

### PR DESCRIPTION
**Pull request by akshatsikarwar**
minimal changes to build 8.0 on bcc ubuntu 24

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by aakash10292 — APPROVED** [review]

**Review by mponomar — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/550 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>truncatesc_ufid_on_generated<br>truncatesc_offline_generated</p>

**Pull request merged**
