### PR TITLE
Enable typessql by default on main

### PR DESCRIPTION
**Pull request by chands10**
Typessql tries to find out all column types in a query by looping through the first n rows until all of them are found, or a maximum number of rows is reached.

Ex: select NULL union select 1

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/521 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fdb_push<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>sc_timepart<br>datetime<br>api_events</p>

**Comment by akshatsikarwar** [comment]
I don't think we can enable this safely. This needs to go though the campaign like we did with `old_column_name`

**Comment by chands10** [comment]
Ok sounds good! Closing

**Pull request closed without merging**
