### PR TITLE
Create datacopy array on bulk import

### PR DESCRIPTION
**Pull request by chands10**
Fix schema->datacopy being NULL when using bulk import on table with datacopy enabled

### CODE REVIEW

**Review by roborivers — DISMISSED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p>

**Comment by chands10** [comment]
Changed back to initial commit from 12/17

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>reorder_inserts_noreorder_generated</p>

**Comment by chands10** [comment]
Ready for review

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>upsert</p>

**Review by akshatsikarwar — APPROVED** [review]

**Pull request merged**
