### PR TITLE
R8 -- comdb2_files: skip watchdog and tmpdir contents

### PR DESCRIPTION
**Pull request by morgando**
Port of #4591

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>scupdates [setup failure]<br>init_sc_race [setup failure]<br>mismatch_class_remsql_fdbpush_generated [setup failure]<br>sc_truncate_lockorder_generated<br>sc_downgrade<br>truncatesc_ufid_on_generated<br>truncatesc_offline_generated<br>dbcreate</p>

**Review by riverszhang89 — APPROVED** [review]
Looks good to merge. Though would `basename(3)` be more concise?

**Comment by morgando** [comment]
`cdb2test   Sep 20 11:51:08 2024  in-comdb2db 8_comdb2_files_exclude.R20240920.3`

**Comment by morgando** [comment]
Thanks Rivers!

**Pull request merged**
