### PR TITLE
macOS

### PR DESCRIPTION
**Pull request by akshatsikarwar**

### CODE REVIEW

**Comment by akshatsikarwar** [comment]
Files changed 520
+3,431 −14,012

Sorry

**Comment by akshatsikarwar** [comment]
Code walkthrough probably more effective for this.

**Comment by mponomar** [comment]
One minor issue:
[mponomar@ip-1-71-86-12 src]$ make clean
/bin/sh: line 0: cd: build: No such file or directory

Make clean only works if you already tried a build

**Comment by akshatsikarwar** [comment]
> Make clean only works if you already tried a build

I can address that.

Just FTR, I don't envision anything other than the test suite to this Makefile. Once we can run test from within build dir, top-level Makefile will go.

**Pull request merged**
