### PR TITLE
cdb2api event handling

### PR DESCRIPTION
**Pull request by riverszhang89**
An event is an action taken by the API, such as when the API connects to the server, sends a query to the server, or reads back the results from the server.

The pull request provides an interface to register an event with a callback routine. The callback is invoked when the event is fired. This allows an application to be notified of and respond to API actions, or even modify API behavior if desired.

The pull request also implements dynamic library loading in cdb2api. Dynamic library loading and event handling combined will give the API a lot of extensibility.

### CODE REVIEW

**Comment by ldennis** [comment]
👍 👍 🥇

**Comment by adizaimi** [comment]
I think this is crashing in robomark:
```
#0  0x0000000000718cd6 in refresh_gbl_events_on_hndl (hndl=0x0, type=CDB2_BEFORE_SEND_QUERY, e=0x0) at /bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/cdb2api/cdb2api.c:6003 
#1  cdb2_next_hook (hndl=0x0, type=CDB2_BEFORE_SEND_QUERY, e=0x0) at /bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2btda1/R20181102.17/comdb2/cdb2api/cdb2api.c:5915 
#2  0x000000000071a16f in cdb2_send_query (hndl=0x0, sb=0x7c66e30, dbname=0x7f2e8039bc60 "comdb2db", sql=0x7f2e80398cb0 "select M.name, D.dbnum, M.room from machines M join databases D where M.cluster IN (select cluster_machs from clusters where name=@dbname and cluster_name=@cluster) and 
D.name=@dbname order by (room ="..., n_set_commands=0, n_set_commands_sent=0, 
set_commands=0x0, n_bindvars=3, bindvars=0x7c66eb0, ntypes=0, types=0x0, 
is_begin=0, skip_nrows=0, retries_done=0, do_append=0, fromline=4775) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/cdb2api/cdb2api.c:2558 
#3  0x000000000071cba7 in comdb2db_get_dbhosts (hndl=0x7c330a0, 
comdb2db_name=0x7f2e8039bc60 "comdb2db", comdb2db_num=32432, 
host=0x7f2e8039bfe0 "c2gnpg-rr-003", port=19002, hosts=0x7c33160, 
num_hosts=0x7c35574, dbname=0x7c330a0 "comdb2db", cluster=0x7c330e0 "prod", 
dbnum=0x7c35570, num_same_room=0x7c35578, num_retries=0) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/cdb2api/cdb2api.c:4774 
#4  0x000000000071d95e in cdb2_get_dbhosts (hndl=0x7c330a0) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/cdb2api/cdb2api.c:5162 
#5  0x00000000007256a0 in cdb2_open (handle=0x7f2e803a0028, dbname=0xae82c2 
"comdb2db", type=0xadd6d8 "prod", flags=Unhandled dwarf expression opcode 
0xf3 
) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/cdb2api/cdb2api.c:5715 
#6  0x0000000000535758 in _discover_remote_db_nodes (dbname=0x7a42728 
"cdbtst02", loc=0x7a42750) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/fdb_boots.c:368 
#7  _fdb_refresh_location (dbname=0x7a42728 "cdbtst02", loc=0x7a42750) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/fdb_boots.c:87 
#8  0x0000000000535b34 in fdb_locate (dbname=0x7a42728 "cdbtst02", 
class=CLASS_ALPHA, refresh=Unhandled dwarf expression opcode 0xf3 
) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/fdb_boots.c:149 
#9  0x000000000053c996 in sqlite3AddAndLockTable (db=0x7a1ff50, 
dbname=0x7a23bc0 "cdbtst02", table=<value optimized out>, 
version=0x7f2e803a084c, in_analysis_load=0) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/fdb_fend.c:1285 
#10 0x00000000008631ba in sqlite3FindTable_int (db=0x7a1ff50, zName=0x7a20558 
"t", czDatabase=Unhandled dwarf expression opcode 0xf3 
) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/sqlite/build.c:401 
#11 0x000000000086422c in sqlite3FindTable (pParse=0x7f2e803a0cd0, flags=0, 
zName=0x7a20558 "t", zDbase=0x7a23bc0 "cdbtst02") at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/sqlite/build.c:468 
#12 sqlite3LocateTable (pParse=0x7f2e803a0cd0, flags=0, zName=0x7a20558 "t", 
zDbase=0x7a23bc0 "cdbtst02") at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/sqlite/build.c:520 
#13 0x000000000086446a in sqlite3LocateTableItem (pParse=0x7f2e803a0cd0, 
flags=0, p=0x7a23b38) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/sqlite/build.c:597 
#14 0x00000000008773de in sqlite3SrcListLookup (pParse=0x7f2e803a0cd0, 
pSrc=0x7a23b28) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/sqlite/delete.c:38 
#15 0x0000000000889562 in sqlite3Insert (pParse=0x7f2e803a0cd0, 
pTabList=0x7a23b28, pSelect=0x0, pColumn=0x0, onError=0, pUpsert=0x0) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/sqlite/insert.c:572 
#16 0x00000000008e0c3d in yy_reduce (yyp=0x7a22e80, yymajor=1, yyminor=<value 
optimized out>, pParse=Unhandled dwarf expression opcode 0xf3 
) at parse.y:906 
#17 sqlite3Parser (yyp=0x7a22e80, yymajor=1, yyminor=<value optimized out>, 
pParse=Unhandled dwarf expression opcode 0xf3 
) at parse.c:5422 
#18 0x00000000008a2dd8 in sqlite3RunParser (pParse=0x7f2e803a0cd0, 
zSql=0x7f2e903a9ff0 "insert into cdbtst02.t values (0, x'DEADBEAF')", 
pzErrMsg=0x7f2e803a0cc8) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/sqlite/tokenize.c:549 
#19 0x0000000000893cb5 in sqlite3Prepare (db=0x7a1ff50, zSql=0x7f2e903a9ff0 
"insert into cdbtst02.t values (0, x'DEADBEAF')", nBytes=Unhandled dwarf 
expression opcode 0xf3 
) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/sqlite/prepare.c:704 
#20 0x0000000000893e59 in sqlite3LockAndPrepare (db=0x7a1ff50, 
zSql=0x7f2e903a9ff0 "insert into cdbtst02.t values (0, x'DEADBEAF')", 
nBytes=-1, saveSqlFlag=1, pOld=0x0, ppStmt=0x7f2e803a3858, 
pzTail=0x7f2e803a3728, flags=Unhandled dwarf expression opcode 0xfa 
) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/sqlite/prepare.c:799 
#21 0x0000000000894906 in sqlite3_prepare_v2 (db=Unhandled dwarf expression 
opcode 0xf3 
) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/sqlite/prepare.c:932 
#22 0x00000000005d8ffc in get_prepared_stmt_int (thd=0x7f2e803a3a60, 
clnt=0x7f2e804e4cd0, rec=0x7f2e803a3850, err=0x7f2e803a38f0, recreate=Unhandled 
dwarf expression opcode 0xf3 
) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/sqlinterfaces.c:2659 
#23 0x00000000005d978c in get_prepared_stmt (thd=0x7f2e803a3a60, 
clnt=0x7f2e804e4cd0, rec=0x7f2e803a3850, err=0x7f2e803a38f0) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/sqlinterfaces.c:2696 
#24 0x00000000005daa83 in get_prepared_bound_stmt (thddata=0x7f2e803a3a60, 
work=0x7f2e804e4cd0) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/sqlinterfaces.c:2827 
#25 handle_sqlite_requests (thddata=0x7f2e803a3a60, work=0x7f2e804e4cd0) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/sqlinterfaces.c:3321 
#26 execute_sql_query (thddata=0x7f2e803a3a60, work=0x7f2e804e4cd0) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/sqlinterfaces.c:3427 
#27 sqlengine_work_appsock (thddata=0x7f2e803a3a60, work=0x7f2e804e4cd0) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/sqlinterfaces.c:3713 
#28 0x00000000005dbfa8 in sqlengine_work_appsock_pp (pool=Unhandled dwarf 
expression opcode 0xf3 
) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/db/sqlinterfaces.c:3745 
#29 0x0000000000711b6e in thdpool_thd (voidarg=0x7f2e903d5b60) at 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/comdb2/util/thdpool.c:723 
#30 0x0000003666a07aa1 in start_thread () from /lib64/libpthread.so.0 
#31 0x00000036662e8aad in clone () from /lib64/libc.so.6 
* * END   ACTIVE THREAD WALKBACK: 
/bb/comdb2a/op/api_events.R20181102.17/comdb22.linux_64.tsk 
**** END   walkback for 
/bb/comdb2a/op/api_events.R20181102.17/comdb22.linux_64.tsk 
/bb/cores/core.comdb22.linux_6.103258.1541255251 
**** Task pwhat information for 
/bb/comdb2a/op/api_events.R20181102.17/comdb22.linux_64.tsk 
        plink [comdb2] BBDISTRO: big2018.44-981113-20181029T141101 
        plink [comdb2] BRANCH_TAG: api_events 
        plink [comdb2] BUILD_DIR: 
/bb/bigstorn/systems/gitbuilds/comdb2/opencomdb2/cdb2test_build_root/pnj-comdb2b
tda1/R20181102.17/build/linux 
        plink [comdb2] HOSTNAME: bldlnx-rr-008 
        plink [comdb2] LOG0001 : Formatting. 
        plink [comdb2] LOG0002 : add llops (#42) 
        plink [comdb2] LOG0003 : R6 compatible version strings 
        plink [comdb2] LOGNAME : cdb2test 
        plink [comdb2] MAKEFILE: CMakeLists.txt 
        plink [comdb2] OSARCH  : x86_64 
        plink [comdb2] OSLEVEL : 6.6 
        plink [comdb2] OSNAME  : Linux 
        plink [comdb2] OSPLATFORM: x86_64 
        plink [comdb2] OSRELEASE: 2.6.32-504.38.1.el6.x86_64 
        plink [comdb2] SVNINFO : https://github.com/riverszhang89/comdb2.git 
(api_events) tag R20181102.17

**Comment by riverszhang89** [comment]
/silent because in Java land, folks do it differently - they extend the driver class.

**Comment by riverszhang89** [comment]
The pull request has passed robomark:

```
cdb2test   Nov 16 15:58:43 2018  in-comdb2db api_events.R20181116.12
```

**Pull request merged**
