### PR TITLE
when downgrading, respect bdblock desired to avoid watchdog

### PR DESCRIPTION
**Pull request by dorinhogea**
Fixes issue: https://github.com/bloomberg/comdb2/issues/465
In a nutshell, when downgrading, transactions on master node, which are about to wait for data replication, don't wait for replicants anymore.  Transactions caught in phase 1 (determining a minimum wait time) will loop continuously for rep_timeout_maxms (which is 5 minutes by default);  while looping the bdb lock is kept, so the downgrade cannot make progress.  In 60 seconds the node aborts due to watchdog trap.

The fix is to detect this scenario and jump out of the initial phase.
The jepsen test should catch this scenario.

### CODE REVIEW

**Comment by ldennis** [comment]
block processor has bdb locks?

**Comment by dorinhogea** [comment]
There is one bdb lock, and any access to underlying berkdb subsystem acquire it in read-only mode.

**Comment by ldennis** [comment]
add_dummy?

**Comment by dorinhogea** [comment]
yes; but it can be any pending transaction; add_dummy will do for a quiet db

**Pull request merged**
