### PR TITLE
Add support for sequences on existing column

### PR DESCRIPTION
**Pull request by chands10**
null=yes should not be needed in this case (see first commit)
Adds csc2 and ddl support

Provided that:
* The col the sequence is added on is the leftmost field in some key
  * The key can be added in the same schema change as adding nextsequence
  * Or, an existing valid key can even be removed in the same schema change as adding nextsequence 
* It is not a partial key
* Nullsort low is enabled
* The key is ascending
* If the key is empty or the highest value in the key is NULL, start sequence from 0

Also note: in strict mode you can convert a column from `int b` to `longlong b dbstore=nextsequence` and this is fine even though the old column is only an int

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>4/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>timepart_trunc_serialsc_generated<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>online_compaction<br>dbcreate<br>sc_downgrade<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_resume<br>dbcreate<br>sc_downgrade<br>sc_lotsoftables_logicalsc_generated<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>dbcreate<br>sc_downgrade<br>incoh_remsql<br>truncatesc_offline_generated</p>

**Comment by chands10** [comment]
cdb2test   Jun 25 15:22:45 2024  in-comdb2db existing_auto_inc.R20240625.4

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>analyze<br>dbcreate<br>sc_downgrade<br>sc_lotsoftables<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>dbcreate<br>sc_lotsoftables<br>truncatesc_offline_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/556 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>timepart_trunc_serialsc_generated<br>dbcreate<br>sc_lotsoftables_logicalsc_generated<br>sc_lotsoftables<br>truncatesc_offline_generated<br>selectv_rcode</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/563 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated<br>socksql_master_swings<br>sc_redo_logicalsc_generated<br>analyze_exit_immediately<br>occ_selectv<br>truncatesc_ufid_on_generated</p>

**Review by markhannum — APPROVED** [review]

**Comment by chands10** [comment]
THANK YOU MARK!!

**Pull request merged**
