### PR TITLE
Don't update seqnum from recover-pglogs in recovery

### PR DESCRIPTION
**Pull request by markhannum**
Don't update master's seqnum from recover_logfile_pglogs

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ bdb/cursor.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/481 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>queuedb_rollover<br>sc_timepart_logicalsc_generated<br>transchunk_manyins<br>queuedb_rollover_noroll1_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/481 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>queuedb_rollover_noroll1_generated</p>

**Comment by markhannum** [comment]
Test seems reliable- this can be reviewed

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/482 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>sc_truncate<br>basic_rowset_generated</p>

**Review by mponomar — APPROVED** [review]

**Pull request merged**
