### PR TITLE
Exit immediately if requested during analyze on master

### PR DESCRIPTION
**Pull request by chands10**
Also noticed that there was no return code error if analyze database exits

To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
* What are the current behavior and expected behavior, if this is a bugfix ?
* What are the steps required to reproduce the bug, if this is a bugfix ?
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/462 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart [core dumped]<br>sc_truncate<br>sc_transactional<br>sc_timepart</p>

**Review by markhannum — APPROVED** [review]
good to merge!

**Comment by chands10** [comment]
Thanks Mark!

**Pull request merged**
