### PR TITLE
FK: cascaded deletes could fail for child tables with partial indices

### PR DESCRIPTION
**Pull request by nirbhayc**
After deleting the record from the data file in the child table, the cascade delete logic attempts to delete the keys for matching record from all its indices. This operation, however, could fail if the key does not exist in any of the partial indices. This is perfectly fine and should not result in error.

The fix populates the 'del_keys' bitmap to ensure we don't attempt to delete the key from partial indices that do not have the key in first place.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/record.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d7057b93/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/403 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_repeated_updates</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d7057b93/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d7057b93/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2793'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/018f016f/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/018f016f/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/018f016f/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2793'>Resubmit</a></p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/record.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

**Review by adizaimi — APPROVED** [review]
Looks good to me!

**Comment by akshatsikarwar** [comment]
I'm wondering if we should be checking `gbl_partial_indexes`? That should permit/deny partial index during schemachange. But once index is part of schema, shouldn't it always be processed?

**Comment by nirbhayc** [comment]
> I'm wondering if we should be checking `gbl_partial_indexes`? That should permit/deny partial index during schemachange. But once index is part of schema, shouldn't it always be processed?

Totally. I'll drop that part of the check.

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/record.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4f62e69f/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_logicalsc_generated</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4f62e69f/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4f62e69f/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2793'>Resubmit</a></p>

**Review by akshatsikarwar — APPROVED** [review]

**Pull request merged**
