### PR TITLE
[8.0] {172983130}: Limiting number of rows returned in comdb2_sc_history

### PR DESCRIPTION
**Pull request by riverszhang89**
8.0 port of https://github.com/bloomberg/comdb2/pull/4318

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ cdb2api/cdb2api.c @@
+ Please port the change to cdb2jdbc if necessary.
+ If you add any internal configuration state to this file, please update the reset_the_configuration() function as well to include it.
@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ berkdb/db/trigger_subscription.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/env/env_method.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reqlog.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ plugins/reversesql/reversesql.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/527 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>truncatesc_offline_generated<br>sc_downgrade</p>

**Review by aakash10292 — APPROVED** [review]
okay to merge (once robomark says yes)

**Comment by riverszhang89** [comment]
@aakash10292 Thanks for the review! test in progress now ...

**Comment by riverszhang89** [comment]
Just made it in!
```
cdb2test   May 14 11:35:35 2024  in-comdb2db schistory_8.R20240514.2
```

**Comment by aakash10292** [comment]
go go go go

**Pull request merged**
