### PR TITLE
Make partition-by work

### PR DESCRIPTION
**Pull request by riverszhang89**
SQLite resets a table's rowid to 0, if the table has no rows. Make our temptable behave in the same way.

### CODE REVIEW

**Comment by riverszhang89** [comment]
On the master branch, executing ```select count(i) over (partition by i) from t1``` will yield an error:

```
[select count(i) over (partition by i) from t1] failed with rc -5 unknown error
```

The pull request fixes it. See the updated window function test for more detail.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/377 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>fingerprints</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/cc461d4/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/cc461d4/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2551'>Resubmit</a></p>

**Review by nirbhayc — APPROVED** [review]
Ok to merge.

**Comment by riverszhang89** [comment]
@nirbhayc Thank you for the review!

**Pull request merged**
