### PR TITLE
Show byte array values in stat4dump

### PR DESCRIPTION
**Pull request by riverszhang89**
(DRQS 166741103)

### CODE REVIEW

**Review by roborivers — APPROVED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p>

**Comment by akshatsikarwar** [comment]
```
int main() {
    char buf [] = {0xde, 0xad, 0xbe, 0xef};
    for (int i = 0; i < sizeof(buf); ++i) printf("%02X ", buf[i]);
}
FFFFFFDE FFFFFFAD FFFFFFBE FFFFFFEF
```
Is this the expected output?

**Comment by riverszhang89** [comment]
> ```
> int main() {
>     char buf [] = {0xde, 0xad, 0xbe, 0xef};
>     for (int i = 0; i < sizeof(buf); ++i) printf("%02X ", buf[i]);
> }
> FFFFFFDE FFFFFFAD FFFFFFBE FFFFFFEF
> ```
> 
> Is this the expected output?

No. I think you would need to explicitly cast the value to an unsigned type because any char greater than `CHAR_MAX` would overflow.

**Review by akshatsikarwar — APPROVED** [review]
OK that works

**Comment by riverszhang89** [comment]
@akshatsikarwar Thank you for the review!

**Pull request merged**
