### PR TITLE
when uuid talks to non-uuid clusters, downgrade properly

### PR DESCRIPTION
**Pull request by dorinhogea**
Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

Replacement for https://github.com/bloomberg/comdb2/pull/2443

The remote sql has a built-in protocol downgrade feature, and uuid addition should be treated similarly.  We did fault the initial R7 design and broke this, but luckily the fix is straightforward and follow the same design goals: any time a uuid-only cluster talks to a non-uuid cluster, the latter will ask for a downgrade and the first switches to rqid-based protocol.  We could add the option to block the downgrade in a future iteration if so desired (for example, int the case when we remove the rqid code completely).

### CODE REVIEW

**Comment by dorinhogea** [comment]
The beauty of this is a uuid cluster can talk uuid to siblings, but rqid to older clusters, at the same time.

**Review by mponomar — APPROVED** [review]
Looks great.  Thanks Dorin.

**Comment by dorinhogea** [comment]
Thank you Mike

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b3ddac7/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b3ddac7/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b3ddac7/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2468'>Resubmit</a></p>

**Pull request merged**
