### PR TITLE
sp: Fetch column-value by column-index

### PR DESCRIPTION
**Pull request by akshatsikarwar**
sp: Fetch column-value by column-index

- Save `dbstmt` in Lua-table instead of meta-table.
- Skip array values when iterating over dbrow using `pairs`.
- `lua_lock`/`lua_unlock` for completeness - these are NOP.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/579 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>sc_inserts_deletes_partial_index_off_generated [setup failure]<br>basic_sslnoproto_generated [setup failure]<br>sc_truncate_lockorder_generated<br>snap_ha_retry_newsi_generated<br>truncatesc_ufid_on_generated</p>

**Comment by akshatsikarwar** [comment]
Converting to draft. This can break apps which use `pairs(dbrow)` to iterate over the row. Unlikely, since that order is undefined and hard to imagine someone does that. But this will introduce twice the number of items. Once with column-name and then same values with column-number.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/579 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>siasofupdate [setup failure]<br>sc_resume_logicalsc_generated<br>phys_rep_tiered<br>commit_lsn_map_delete_generated<br>snap_ha_retry_newsi_generated<br>truncatesc_ufid_on_generated<br>auth</p>

**Comment by akshatsikarwar** [comment]
`cdb2test   Sep 26 15:01:19 2024  in-comdb2db dbrow-index.R20240926.4`

**Review by mponomar — APPROVED** [review]

**Pull request merged**
