### PR TITLE
Fix leaks in comdb2_files

### PR DESCRIPTION
**Pull request by morgando**

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/574 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>selectv_recom_range [setup failure]<br>selectv_recom [setup failure]<br>sc_newuniq [setup failure]<br>sc_remsql_fdbpushredirect_generated [setup failure]<br>fdb_push_redirect_generated [setup failure]<br>sc_transactional_rowlocks_generated<br>analyze_exit_immediately<br>truncatesc_ufid_on_generated<br>dbcreate</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/574 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>writes_remsql_rte_connect_generated [setup failure]<br>sc_resume_logicalsc_generated<br>sc_resume<br>analyze_exit_immediately<br>truncatesc</p>

**Review by LiSodium — APPROVED** [review]

**Review by markhannum — APPROVED** [review]

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/574 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_dups_logicalsc_generated [setup failure]<br>writes_remsql_names_negativerowid_generated [setup failure]<br>blob_sanity [setup failure]<br>sc_resume_logicalsc_generated<br>truncatesc_ufid_on_generated<br>dbcreate</p>

**Comment by morgando** [comment]
`cdb2test   Sep  7 06:06:32 2024  in-comdb2db fix_comdb2_files_leak.R20240907.2`

**Pull request merged**
