### PR TITLE
Option to disallow Anonymous ID over pmux secure port

### PR DESCRIPTION
**Pull request by riverszhang89**
This patch adds options to disallow foreign-db queries and the Anonymous Identity, over client connections forwarded from the pmux secure port.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Comment by riverszhang89** [comment]
`cdb2test   May  9 11:23:32 2024  in-comdb2db auth3.R20240509.2`

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/533 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume<br>schemalk<br>sc_transactional_rowlocks_generated<br>phys_rep_tiered_nosource_generated<br>phys_rep_tiered<br>truncatesc_offline_generated<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>12/533 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>schemalk_extralock_generated<br>schemalk<br>phys_rep_tiered<br>phys_rep_tiered_nosource_generated<br>sc_downgrade<br>incoh_remsql<br>truncatesc_offline_generated<br>truncatesc_ufid_on_generated<br>comdb2sys_queueodh_generated</p>

**Review by mohitkhullar — APPROVED** [review]
looks good

**Comment by riverszhang89** [comment]
@mohitkhullar Thanks for the review!

**Pull request merged**
