### PR TITLE
comdb2ar: Refactor modes_enum into an enum class.

### PR DESCRIPTION
**Pull request by levinem**
To help us review your pull request, please consider providing an overview of the following:
* What is the type of the change (bug fix, feature, documentation and etc.) ?
It is a refactoring.
* What are the current behavior and expected behavior, if this is a bugfix ?
It is not a bugfix.
* What are the steps required to reproduce the bug, if this is a bugfix ?
It is not a bugfix.
* What is the current behavior and new behavior, if this is a feature change or enhancement ?
The behavior should be largely the same.
* [Optional] Why is the new behavior better than the current behavior, if this is a feature change ?
Modern C++ recommends using enum classes over regular enums to help minimize the possibility of traditional enums being converted to ints unintentionally.  Also, I made all the enum class elements lower case to avoid potential clashes with current/future macros.

### CODE REVIEW

**Comment by levinem** [comment]
I was able to build comdb2 with my changes.  Please let me know if you want me to run clang_format on the entire file, parts of the file, etc.  Thanks!

**Comment by riverszhang89** [comment]
Thank you for the patch!

**Comment by levinem** [comment]
No problem @riverszhang89 , glad I could help!

**Pull request merged**
