### PR TITLE
Fix reverse-conn / tranlog

### PR DESCRIPTION
**Pull request by markhannum**
Fixes the reverse-connection early timeout issue that caused the excess recovery bug.  Additionally fixes the null-generation bug in the travelog table.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/588 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart_multiddl_generated [setup failure]<br>unionpar_maxqueue [setup failure]<br>selectv_range [setup failure]<br>writes_remsql_names_negativerowid_generated [setup failure]<br>timepart_trunc<br>snap_ha_retry_newsi_generated<br>phys_rep_tiered_nosource_generated<br>ssl_remsql_fdbpush_generated<br>auth</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>20/589 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_lotsoftables_logicalsc_generated [setup failure]<br>sc_lock_inversion [setup failure]<br>mismatch_class_remsql_fdbpushredirect_generated [setup failure]<br>sc_transactional_rowlocks_generated<br>simple_timepart_reptimeout_generated<br>simple_timepart<br>commit_delay_on_copy<br>snap_ha_retry_newsi_generated<br>yast_stat4scan_generated<br>yast</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/589 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>updcolsbug [setup failure]<br>writes_remsql_names [setup failure]<br>verify_error_partial_index_off_generated [setup failure]<br>sc_remsql [setup failure]<br>snap_ha_retry_newsi_generated<br>auth</p>

**Review by mponomar — APPROVED** [review]

**Pull request merged**
