### PR TITLE
writecb: no mo akbufferevent

### PR DESCRIPTION
**Pull request by akshatsikarwar**
This fixes performance problems I saw in the `logfill` test. Following is a concurrent run of this branch and master:
```
root@c0:~/src/comdb2/writecb/tests# time make logfill
TESTID=63378 running in /opt/bb/tmp/testdir logfill 2/1
!logfill: creating db logfill63378
!logfill: copying to cluster
!logfill: starting
!logfill: waiting until ready
!logfill: started running with timeout 20m at 2021-12-03 20:56:05
!logfill: finished running with timeout 20m at 2021-12-03 21:01:04
!logfill: success (logs in /opt/bb/tmp/testdir/logs/logfill63378.testcase)
!logfill: stopping

real    6m7.679s
user    0m3.498s
sys     0m4.256s
```
vs
```
root@c0:~/src/comdb2/master/tests# time make logfill
TESTID=25578 running in /opt/bb/tmp/testdir logfill 1/1
!logfill: creating db logfill25578
!logfill: copying to cluster
!logfill: starting
!logfill: waiting until ready
!logfill: started running with timeout 20m at 2021-12-03 20:56:05
!logfill: finished running with timeout 20m at 2021-12-03 21:03:19
!logfill: success (logs in /opt/bb/tmp/testdir/logs/logfill25578.testcase)
!logfill: stopping

real    8m0.503s
user    0m4.119s
sys     0m4.315s
```

Clearly, the master branch was slower, but also I have seen it time out frequently.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/411 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>socksql_master_swings<br>sc_constraints<br>sc_resume_logicalsc_generated<br>recover_ddlk_sp</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/411 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>sc_constraints<br>sc_constraints_logicalsc_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p>The first 10 failing tests are: <br>phys_rep</p>

**Review by riverszhang89 — APPROVED** [review]

**Pull request merged**
