### PR TITLE
Protect fdb writes with mutex if hbeats are enabled

### PR DESCRIPTION
**Pull request by markhannum**
Lock around the fdb-write functions if heartbeats are enabled.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ plugins/remsql/fdb_comm.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ plugins/remsql/fdb_comm.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Comment by akshatsikarwar** [comment]
That is a lot of places where mutex has to be unlocked. Wrapper function which calls this under lock would be cleaner:
```
lock
fdb_msg_write_message
unlock
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>sc_transactional_rowlocks_generated<br>phys_rep_tiered<br>queuedb_rollover<br>transchunk_manyins</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ plugins/remsql/fdb_comm.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Comment by markhannum** [comment]
> That is a lot of places where mutex has to be unlocked. Wrapper function which calls this under lock would be cleaner.

Tx Akshat!  I've revised this to call 'fsb_msg_write_message_lk' with the mutex held.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>phys_rep_tiered</p>

**Review by dorinhogea — APPROVED** [review]
Looks good to me!

**Pull request merged**
