### PR TITLE
sqlite: Fix an OP_NoConflict optimization

### PR DESCRIPTION
**Pull request by nirbhayc**
Skip an OP_NoConflict optimization in sqlite for non-UNIQNULLS indexes that assumes NULLs are unique.

Signed-off-by: Nirbhay Choubey <nchoubey@bloomberg.net>

### CODE REVIEW

**Review by roborivers — APPROVED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e9d87ba9/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/e9d87ba9/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2625'>Resubmit</a></p>

**Review by roborivers — COMMENTED** [review]
<p>Sysbench Transactions Per Second (commit: e9d87ba9):</p>

<pre lang=diff>
@@ sysbench/bulk_insert @@
-6.43%
@@ sysbench/oltp_delete @@
+6.11%
</pre>

**Review by riverszhang89 — APPROVED** [review]

**Review by mponomar — APPROVED** [review]
Looks good to merge, thanks!

**Comment by nirbhayc** [comment]
Cherry-picked to 7.0

**Pull request merged**
