### PR TITLE
{173200134}

### PR DESCRIPTION
**Pull request by aakash10292**
sc dryrun: fix null ptr reference to iq during ix length validation

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>phys_rep<br>sc_transactional_rowlocks_generated<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>sc_timepart<br>tunables<br>ddl_dryrun</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>phys_rep_tiered<br>queuedb_rollover<br>tunables<br>ddl_dryrun</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>8/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>systable_locking<br>sc_truncate<br>phys_rep<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>tunables<br>ddl_dryrun</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>5/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>tunables<br>ddl_dryrun</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>6/487 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>phys_rep_tiered<br>queuedb_rollover_noroll1_generated<br>queuedb_rollover<br>lostwrite<br>tunables</p>

**Review by riverszhang89 — APPROVED** [review]

**Comment by aakash10292** [comment]
Thanks Rivers!

**Pull request merged**
