### PR TITLE
Fix byte-maxkey bug, add simple testcase

### PR DESCRIPTION
**Pull request by markhannum**
Revise maxkey fix, add simple testcase.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>2/477 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>sc_truncate</p>

**Review by akshatsikarwar — APPROVED** [review]
Thank you!

**Comment by akshatsikarwar** [comment]
Also, if possible refactor so we don't have `BDB_KEY_MAX`, `MAX_KEY_SIZE`, and `MAXKEYLEN`. Also, need to see what `MAXKEYSZ` is and why is it 1024.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/477 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated<br>sc_truncate<br>sc_transactional_rowlocks_generated</p>

**Pull request merged**
