### PR TITLE
README instructions also give successful "make test" on Ubuntu 20.04, Debian 10

### PR DESCRIPTION
**Pull request by danshearer**
all-tests takes a *very* long time :)

### CODE REVIEW

**Comment by adizaimi** [comment]
Thanks for verifying and the PR. In fact all my local testing is done in Debian : ).
all-tests do indeed take very long, and longer as we add more tests.
We were considering to include a smaller subset for quicker basic testing.

**Comment by danshearer** [comment]
> We were considering to include a smaller subset for quicker basic testing.

Many tests could be done in parallel with very little work.

**Comment by adizaimi** [comment]
> > We were considering to include a smaller subset for quicker basic testing.
> 
> Many tests could be done in parallel with very little work.

That's what we do -- we may need to update docs to make things more clear.
How do you run tests currently? 

We simply 
```
cd tests/
make -j 8 -k 
```
Will run all tests in 8-way parallel. Currently should take abount 1.5hrs, depending on hardware.

**Comment by mponomar** [comment]
You'll want to run `make test-tools` in the build directory first.

**Comment by mponomar** [comment]
The test suite expects some of the tests to have a cluster, since we rarely run Comdb2 standalone. If you want a somewhat friendlier way to run tests,

- Copy contrib/dev-util/cluster somewhere in your PATH
- run `cluster init`.  You can leave defaults for all the prompts except the path to source.
- run `cluster build`, `cluster run`
- run `cluster test` to kick off tests

This works on ubuntu, with limited success on other distributions.  We use a similar procedure to run our tests (ie: docker + make test -j ...).

**Pull request merged**
