### PR TITLE
Cherry-pick SQLite patchs from 7.0

### PR DESCRIPTION
**Pull request by riverszhang89**
This is a cherry pick from 7.0 to port a few SQLite patches to master.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>370/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_lotsoftables [setup core dumped]<br>sirandtest2 [setup core dumped]<br>sc_inserts_logicalsc_generated [setup failure]<br>unionpar_maxqueue [core dumped]<br>maxtable [core dumped]<br>selectv_deadlock [core dumped]<br>sc_repeated_updates_logicalsc_generated [core dumped]<br>sc_repeated_updates [core dumped]<br>sc_lotsoftables_logicalsc_generated [core dumped]<br>yast [core dumped]</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/vdbeInt.h @@
+ If the order of members in struct Mem is changed, columnNullValue (defined in sqlite/vdbeapi.c) needs to be reordered accordingly.
@@ sqlite/src/vdbeaux.c @@
+ If a new fixed-length serial type is introduced, sqlite3IsFixedLengthSerialType (defined in sqlite/vdbeInt.h) needs to be changed accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/421 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_constraints</p>

**Review by nirbhayc — APPROVED** [review]
LGTM

**Comment by riverszhang89** [comment]
@nirbhayc Thanks for the review!

**Pull request merged**
