### PR TITLE
Install comdb2ar and cdb2_sqlreplay from debian package

### PR DESCRIPTION
**Pull request by markhannum**
They were being removed by the postrm package script

### CODE REVIEW

**Comment by nirbhayc** [comment]
Why not delete those files? postrm is supposed to run after 'apt-get remove'.

**Comment by markhannum** [comment]
I think I misunderstood this then.  When I install a new package on my AWS cluster these files are missing, while the other utilities (comdb2, cdb2sql, etc) are intact.. changing this allows re-installs to work (comdb2ar is installed) after two additional installs.

**Comment by nirbhayc** [comment]
Strange. While these 2 files are in deb package, could it be that somehow they aren't getting installed?
```
nirbhay@nirbhay-vbox:~/project/git-repo/comdb2/tmp$ dpkg -c comdb2_7.0.0pre-20170405131110_amd64.deb | grep "comdb2ar\|sqlreplay"
-rwxr-xr-x root/root   1866824 2017-06-14 11:35 ./opt/bb/bin/comdb2ar
-rwxr-xr-x root/root    564016 2017-06-14 11:35 ./opt/bb/bin/cdb2_sqlreplay
```

**Comment by markhannum** [comment]
I have a slightly better answer now:  this script is intended to cleanup things that aren't explicitly installed by dpkg.  We use it to remove things that are hard-linked to comdb2 (see the logic in the postinst script).  comdb2ar and cdb2_sqlreplay are actual standalone programs, not hard-links to comdb2, which means that it's explicitly installed and removed by dpkg.  Listing them here causes them to be uninstalled twice.

Enabling debug trace on dpkg -i shows comdb2ar getting installed, and then subsequently deleted by the postrm code:
  399 D000100: setupvnamevbs main='/opt/bb/bin/comdb2ar' tmp='/opt/bb/bin/comdb2ar.dpkg-tmp' new='/opt/bb/bin/comdb2ar.dpkg-new'                                                                                                       
  400 D000100: deferred extract needs fsync                                                                                                                                                                                            
  401 D000100: deferred extract needs rename                                                                                                                                                                                           
  402 D000100: deferred extract done and installed     
...
  435 D000002: fork/exec /var/lib/dpkg/info/comdb2.postrm ( upgrade 7.0.0pre-20170405131110 )                                                                                                                                          
  436 + echo rm -f /opt/bb/bin/cdb2_dump /opt/bb/bin/cdb2_printlog /opt/bb/bin/cdb2_sqlreplay /opt/bb/bin/cdb2_stat /opt/bb/bin/cdb2_verify /opt/bb/bin/comdb2ar                                                                       
  437 rm -f /opt/bb/bin/cdb2_dump /opt/bb/bin/cdb2_printlog /opt/bb/bin/cdb2_sqlreplay /opt/bb/bin/cdb2_stat /opt/bb/bin/cdb2_verify /opt/bb/bin/comdb2ar                                                                              
  438 + rm -f /opt/bb/bin/cdb2_dump /opt/bb/bin/cdb2_printlog /opt/bb/bin/cdb2_sqlreplay /opt/bb/bin/cdb2_stat /opt/bb/bin/cdb2_verify /opt/bb/bin/comdb2ar

**Comment by nirbhayc** [comment]
Since the 2 binaries are no longer link but standalone executables, it's logical to take them off postrm script. @markhannum thank you for clarifying this.

The patch looks good to me.

**Comment by nirbhayc** [comment]
post-mortem:  1st (fresh) install would have gone ok. The subsequent, install, however, would have failed while postrm-ing these files from the previous install.

**Pull request merged**
