### PR TITLE
Revert "ssl for cross-database sql"

### PR DESCRIPTION
**Pull request by mponomar**
Reverts bloomberg/comdb2#736

Let's revert this until we've discussed it internally.

### CODE REVIEW

**Comment by dorinhogea** [comment]
The changes are a step forward, not backward.  It improves on the existing situation when remsql is only possible in clear text.  I don't think this should be reverted.

**Comment by adizaimi** [comment]
I agree with Dorin, ftr.

**Comment by akshatsikarwar** [comment]
Seems reasonable - this is similar to Mike's first cut implementation between client-server?

**Comment by mponomar** [comment]
Ok, fair enough.  Let's leave the current code until we have a better model in place for passing identity between databases.

**Comment by riverszhang89** [comment]
> The changes are a step forward, not backward. It improves on the existing situation when remsql is only possible in clear text. I don't think this should be reverted.

I disagree. First of all, an incomplete implementation with known security weakness isn't a step forward from not implementing it. Second of all, your patch doesn't improve anything - it doesn't change the fact that a trusted network is still required between the server and the remote to prevent MITM attacks.

If you insist to keep the code there, you should at least disable it by default or warn users about the security risk.

**Pull request closed without merging**
