### PR TITLE
re-engineer manual partitions to use new partition implementation

### PR DESCRIPTION
**Pull request by dorinhogea**
Example syntax:
"CREATE TABLE t(a int) PARTITIONED BY MANUAL RETENTION '2' START 1"
Uses the new "truncate" rollout.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/469 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>physrep_ignore_table<br>auth_twofiles_generated<br>auth_queueodh_generated<br>auth<br>ddl_analyze<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated<br>comdb2sys<br>tunables</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/469 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock<br>sc_truncate<br>selectv_deadlock<br>ddl_analyze</p>

**Review by mponomar — APPROVED** [review]

**Comment by dorinhogea** [comment]
Thank you Mike!

**Pull request merged**
