### PR TITLE
build: Fix build warnings with GCC 10

### PR DESCRIPTION
**Pull request by akshatsikarwar**
Also,
* Fix cyclical dependency between bdb and berkdb due to os_namemangle.c
* Clean up dead-code dealing with later versions for berkdb
* Fix a few false-positive warnings (string-overflow and return-local-addr)

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>3/422 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>comdb2sys_pagesize_generated [setup failure]<br>logfill<br>reorder_inserts_noreorder_generated</p>

**Comment by akshatsikarwar** [comment]
Looks like `count_db` is still used. I'll get that back in..

**Review by dorinhogea — APPROVED** [review]
LGTM!

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>2/422 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep<br>reorder_inserts_noreorder_generated</p>

**Pull request merged**
