### PR TITLE
Address some files with inconsistent indentation

### PR DESCRIPTION
**Pull request by morgando**
The changes in this PR convert tabs to spaces in files that use both in the bbinc, bdb, csc2, db, and sqlite subsystems.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/560 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_resume_logicalsc_generated<br>sc_timepart<br>sc_resume<br>osql_cleanup<br>recover_deadlock<br>dbcreate<br>truncatesc_offline_generated</p>

**Review by LiSodium — APPROVED** [review]

**Review by riverszhang89 — APPROVED** [review]

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/src/parse.y @@
+ Custom tokens and rules must be defined after SQLite's.
+ Please update SQL documentation and bubble diagrams to reflect the changes you've made, if necessary.
@@ bbinc/bb_stdint.h @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ csc2/macc_so.c @@
+ Please remove debugging statements, and replace fprintf/printf with logmsg.
@@ db/reverse_conn.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ db/reverse_conn.c @@
+ Please replace any pthread_xxx() function in your diff with corresponding Pthread_xxx() wrapper.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>dbcreate</p>

**Comment by morgando** [comment]
`cdb2test   Jul  5 15:05:58 2024  in-comdb2db consistent_indent.R20240705.4`

**Pull request merged**
