### PR TITLE
Prepare

### PR DESCRIPTION
**Pull request by markhannum**
This PR has changes to BerkleyDB required to facilitate participants for distributed 2pc transactions.

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_stat.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/lock/lock.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>127/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>timepart_trunc<br>auth_twofiles_generated<br>auth_queueodh_generated<br>auth<br>userschema_queueodh_generated<br>userschema<br>backup_logfiles<br>comdb2sys_queueodh_generated<br>comdb2sys_pagesize_generated</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_stat.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/lock/lock.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>8/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>reorder_inserts_noreorder_generated<br>backup_logfiles<br>cdb2sql_queueodh_generated<br>cdb2sql<br>logical_ops<br>logdelete<br>logdelete_snapshot_generated<br>logarchive</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_stat.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/lock/lock.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logfill_logput_window_generated<br>sc_truncate<br>phys_rep<br>ddl_analyze<br>cdb2sql_queueodh_generated<br>cdb2sql<br>logical_ops</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_stat.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/lock/lock.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>physrep_ignore_table</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_stat.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/lock/lock.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>10/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>truncatesc<br>deadlock_load_noreorder_generated<br>physrep_ignore_table<br>reorder_deletes_noreorder_generated<br>phys_rep<br>reorder_inserts_noreorder_generated<br>tunables<br>sc_downgrade<br>insert_lots</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_stat.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/lock/lock.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>9/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite<br>deadlock_load_noreorder_generated<br>physrep_ignore_table<br>reorder_deletes_noreorder_generated<br>phys_rep<br>reorder_inserts_noreorder_generated<br>tunables<br>sc_downgrade<br>insert_lots</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_stat.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/lock/lock.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>6/471 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>deadlock_load_noreorder_generated<br>physrep_ignore_table<br>blkseq_snapiso_generated<br>reorder_inserts_noreorder_generated<br>tunables<br>insert_lots</p>

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
@@ sqlite/ext/comdb2/tables.c @@
+ If a new system table is added, be sure to document it in docs/pages/programming/system_tables.md.
@@ berkdb/txn/txn_util.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/txn/txn_stat.c @@
+ Please make sure that a mutex is unlocked before returning.
@@ berkdb/lock/lock.c @@
+ Please make sure that a mutex is unlocked before returning.
```

**Comment by markhannum** [comment]
withdrawing this one - I submitted a new pr with squashed commits called 'participant'

**Pull request closed without merging**
