### PR TITLE
Fix reverse-conn / tranlog

### PR DESCRIPTION
**Pull request by markhannum**
Fixes the reverse-connection early timeout issue that caused the excess recovery bug.  Additionally fixes the null-generation bug in the travelog table.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/560 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sicomplex2 [setup failure]<br>nogen_full_recovery_disable_generated<br>truncatesc_offline_generated</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Error &#x26A0;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/0 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/563 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>vutf8_rowlocks [setup failure]<br>sc_transactional_rowlocks_generated<br>phys_rep_perf<br>phys_rep_via_comdb2_files_generated<br>truncatesc_offline_generated</p>

**Review by mponomar — APPROVED** [review]

**Pull request merged**
