### PR TITLE
Enable per-thread malloc for libevent net

### PR DESCRIPTION
**Pull request by riverszhang89**
Also rename THREAD_TYPE to ENABLE_PER_THREAD_MALLOC to better explain what the macro really does.

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4caf89d7/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4caf89d7/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>3/387 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_timepart<br>socksql_master_swings<br>netmem</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4caf89d7/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4caf89d7/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2608'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5fe3aed0/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5fe3aed0/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/5fe3aed0/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2608'>Resubmit</a></p>

**Comment by akshatsikarwar** [comment]
Fails `cbuild`?

**Review by akshatsikarwar — APPROVED** [review]
Check `cbuild`. LGTM otherwise.

**Comment by riverszhang89** [comment]
@akshatsikarwar Thank you for the review! The cbuild failure is due to the change of `dispatch_sql_query()`'s prototype and not related to this pull request.

**Pull request merged**
