### PR TITLE
Supporting blob-to-blob2 schema change

### PR DESCRIPTION
**Pull request by riverszhang89**
The patch also fixes a few edge cases in vutf8/blob schemachange. See the newly added `sc_vutf8_blob2_upd_behind_cursor' test for reproducers.

This is a rebase of #3162.

(DRQS 168467835)

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/452 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>triggersc_latency<br>reorder_inserts_noreorder_generated<br>datacopy</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/452 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate<br>incremental_backup_usenames<br>load_cache_dumpmax_generated<br>load_cache_autocache_generated</p>

**Review by markhannum — APPROVED** [review]
Good to merge!

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>0/452 tests failed</b> &#x26A0;.</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/452 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sql_datetime_interval_arithmetic_leak<br>phys_rep<br>load_cache</p>

**Comment by chands10** [comment]
Oh wow you found my other stag function

**Review by chands10 — APPROVED** [review]
LGTM

**Comment by riverszhang89** [comment]
@markhannum @chands10 Thanks for the review!

**Pull request merged**
