### PR TITLE
Genid48 unit test

### PR DESCRIPTION
**Pull request by markhannum**
I wrote this in an effort to understand some behavior that our Jepsen testing unearthed.  Genid48 code turned out not to be at fault.

### CODE REVIEW

**Comment by nirbhayc** [comment]
Runtime-only no? I did not find a use-case for that. The tunables not marked as READONLY can be set at start via lrl or, later, at runtime. Said that I can add the support for runtime-only if that's something we really need.

**Comment by mponomar** [comment]
It's more of a command to run, not a tunable (no persistent value to set).

**Comment by nirbhayc** [comment]
How about supporting arbitrary user variables using SET with connection life span? They can be used in such scenarios.
```
> SET user-var val;
```

**Comment by mponomar** [comment]
SET is for per-session settings.  PUT has been culturally appropriated for permanent settings.  This is neither.  It's fine for this to exist as a command since we're not likely to use this outside of testing (or if we ever have to reset a genid48 sequence because we run out)

**Pull request merged**
