### PR TITLE
Small refactor to print errors in cursor.c and portmuxusr.c

### PR DESCRIPTION
**Pull request by adizaimi**
* Print clear message for any errors in portmuxusr.c
* Print error if MERGE_DEBUG is enabled--useful while debugging
* Leave db running after test is done if $LEAVEDBRUNNING is set

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/af76cfdf/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/af76cfdf/robomark.txt'>Error &#x26A0; </a>.<br>Regression testing: <b>22/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>basic_singlenode_generated [setup core dumped]<br>datacopy [setup failure]<br>cdb2sql_auth [setup failure]<br>bloballoc [setup failure]<br>basic_snapshot_generated [setup failure]<br>basic_rte_generated [setup failure]<br>largeindex [setup failure]<br>blob_sanity [setup failure]<br>mem_be_nice<br>long_db_name</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/af76cfdf/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/af76cfdf/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2839'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/af76cfdf/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>13/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>lostwrite [setup failure]<br>ignore_bad_table [setup failure]<br>biginplace [setup failure]<br>basic [setup failure]<br>auth_dba [setup failure]<br>datetime [setup failure]<br>cdb2api_so [setup failure]<br>cancel_sql [setup failure]<br>basic_nogenid48_generated [setup failure]<br>index_deadlock_loop_print</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/af76cfdf/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/af76cfdf/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2839'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/af76cfdf/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>20/405 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>logical_sc_empty_blob [setup core dumped]<br>cancel_sql [setup core dumped]<br>ignore_bad_table [setup failure]<br>genid48 [setup failure]<br>datacopy [setup failure]<br>cdb2bind [setup failure]<br>cdb2api_so [setup failure]<br>biginplace [setup failure]<br>basic_snapshot_generated [setup failure]<br>basic_rowlocks_generated [setup failure]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/af76cfdf/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/af76cfdf/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2839'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/848ee3a4/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/848ee3a4/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/848ee3a4/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2839'>Resubmit</a></p>

**Review by riverszhang89 — APPROVED** [review]

**Comment by adizaimi** [comment]
Thank you Rivers!

**Pull request merged**
