### PR TITLE
Getting rid of premature ssl_shutdown optimization

### PR DESCRIPTION
**Pull request by riverszhang89**
Previously `cdb2_close()` did not send the "close_notify" alert, if a connection wasn't to be reused (an undrained cursor, for instance). This would undesirably result in `ECONNRESET` on the server.

This patch gets rid of the optimization.

(DRQS 171159124)
(JIRA RDSICDBDBA-914)

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/461 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_truncate<br>weighted_standing_queue<br>tunables</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>7/461 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>sc_truncate<br>sc_truncate_lockorder_generated<br>verify_error_partial_index_off_generated<br>sc_transactional_rowlocks_generated<br>tunables<br>read_committed_unique</p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/461 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sirace<br>tunables<br>basic_nolibevent_generated</p>

**Comment by akshatsikarwar** [comment]
What is the downside to keeping the optimization? We are already skipping the connection reset error trace.. 

Do check why basic_nolibevent_generated failed. And a few core dumps there as well.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>384/461 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>cldeadlock [core dumped]<br>truncatesc_offline_generated<br>sc_drop<br>incremental_backup_load<br>epochms_rollover<br>selectv_deadlock<br>sc_truncate_lockorder_generated<br>recom_replay<br>sc_resume_logicalsc_generated<br>sc_resume</p>

**Pull request closed without merging**
