### PR TITLE
Store query data in cache

### PR DESCRIPTION
**Pull request by mohitkhullar**
Signed-off-by: Mohit Khullar <mohit.khullar@gmail.com>

### CODE REVIEW

**Comment by mohitkhullar** [comment]
Opening new PR to preserve commits related to deadlock
https://github.com/bloomberg/comdb2/pull/2465

**Review by mponomar — APPROVED** [review]

**Comment by mohitkhullar** [comment]
added params test in robomark

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/368 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>selectv_rcode_serialretry_generated [core dumped]<br>ioerror_remsql [core dumped]<br>systbl_proc_leak</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7acccef/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/7acccef/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2438'>Resubmit</a></p>

**Comment by mohitkhullar** [comment]
opening new PR https://github.com/bloomberg/comdb2/pull/2482

**Pull request closed without merging**
