### PR TITLE
cdb2api: auto consume remaining rows with timeouts before cdb2_close

### PR DESCRIPTION
**Pull request by ldennis**
cdb2api: auto consume remaining rows with timeouts before cdb2_close

### CODE REVIEW

**Comment by mohitkhullar** [comment]
The code looks fine, can we have a test case where we run a long query and do cdb2_close after reading just 1 row, just so that it triggers this code logic.

**Comment by mohitkhullar** [comment]
looks good

**Comment by riverszhang89** [comment]
What problem does the pull request address?

**Comment by riverszhang89** [comment]
Cdb2jdbc consumes all rows on close. The patch does not need to be ported to cdb2jdbc.

**Comment by akshatsikarwar** [comment]
For jdbc - it doesn't really have to - there is no connection pool.

**Comment by ldennis** [comment]
Thanks.

**Pull request merged**
