### PR TITLE
Add verbose fdb push output under tunable

### PR DESCRIPTION
**Pull request by chands10**

### CODE REVIEW

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Error &#x26A0;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>5/509 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>phys_rep_tiered<br>sc_resume_logicalsc_generated<br>sc_resume<br>queuedb_rollover<br>lostwrite</p>

**Review by riverszhang89 — COMMENTED** [review]
Could you use the DEBUG level for these messages and get rid of the debug tunables?

**Comment by chands10** [comment]
Yep!

**Comment by chands10** [comment]
Done

**Review by riverszhang89 — APPROVED** [review]

**Comment by chands10** [comment]
Thanks Rivers!

**Pull request merged**
