### PR TITLE
pre_read_option: missing handle_lrl_tunable

### PR DESCRIPTION
**Pull request by ldennis**

### CODE REVIEW

**Comment by ldennis** [comment]
Can you be more specific? We fall through if the tunable wasnt registered, no?

**Comment by nirbhayc** [comment]
https://gist.github.com/nirbhayc/39610efdef03f46f3862db605bc4737e

**Comment by nirbhayc** [comment]
I haven't tested it though.

**Comment by nirbhayc** [comment]
See : https://github.com/bloomberg/comdb2/pull/262

**Pull request closed without merging**
