### PR TITLE
Specify versions for Docker and Compose

### PR DESCRIPTION
**Pull request by timmui**
Add docker and compose versions that are confirmed to be working to the docs. An older version was found to be incompatible. #skipbuild

### CODE REVIEW

**Comment by timmui** [comment]
@mponomar If you have a different version of Docker/Compose, can you also add it to the list of tested versions? @markhannum discovered that an earlier version of Docker didn't work.

**Comment by riverszhang89** [comment]
https://github.com/bloomberg/comdb2/blob/master/contrib/docker/docker-compose.yml#L2

The compose file is version 2 compliant. Simply change the version down to 2 and it will work on most versions of docker engine.

**Comment by riverszhang89** [comment]
For reference: https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix

**Comment by mponomar** [comment]
```
[mike@xps /home/mike]$ docker --version
Docker version 17.06.0-ce, build 3dfb8343
[mike@xps /home/mike]$ docker-compose --version
docker-compose version 1.14.0, build unknown
[mike@xps /home/mike]$ 
```

**Pull request merged**
