### PR TITLE
Fix crashes from acces to sqlquery after calling srs_tran_destroy

### PR DESCRIPTION
**Pull request by adizaimi**
We access sqlquery in reqlog_end_request() after we call srs_tran_destroy()
in codepaths where replicant replays query resulting (sometimes) crash.
This patch moves destroying after access.
Also initialize rc before using it in create_datacopy_arrays().
Also allow enough space for 'rollback' to compute fingerprint.

Signed-off-by: Adi Zaimi <azaimi@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>1/371 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>replay_eventlog</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d787f4b/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/d787f4b/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2492'>Resubmit</a></p>

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>4/371 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>socksql_master_swings<br>systbl_proc_leak<br>replay_eventlog<br>sc_truncate</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b13357a/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/b13357a/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2492'>Resubmit</a></p>

**Comment by adizaimi** [comment]
Ran selectv_rcode_serialretry_generated test in a loop for more than 24 hours and the crash [which happens in master branch currently] is no longer happening. Valgrind also reports no more 'Invalid access' with this change.

**Review by roborivers — APPROVED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4a6e2a5/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/4a6e2a5/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2492'>Resubmit</a></p>

**Review by nirbhayc — APPROVED** [review]
Good catch Adi! Could you also check if we need to backport this to 7.0?

**Comment by adizaimi** [comment]
Thanks Nirbhay.

**Comment by adizaimi** [comment]
Thanks Nirbhay.

**Comment by adizaimi** [comment]
Thanks Nirbhay.

**Comment by adizaimi** [comment]
Thanks Nirbhay.

**Comment by adizaimi** [comment]
Thanks Nirbhay.

**Comment by adizaimi** [comment]
Thanks Nirbhay.

**Comment by adizaimi** [comment]
Thanks Nirbhay.

**Pull request merged**
