### PR TITLE
Check auth for stored procedures? {176046512}

### PR DESCRIPTION
**Pull request by mohitkhullar**

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/562 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_transactional_rowlocks_generated<br>analyze_exit_immediately<br>truncatesc</p>

**Review by chands10 — APPROVED** [review]
LGTM. Only care about read access for sp?

**Comment by mohitkhullar** [comment]
> LGTM. Only care about read access for sp?
If its doing write on any table then that is already checked in db_access code, however for exec procedure ... just checking read access to procedure should be enough.

**Comment by mohitkhullar** [comment]
Thanks

**Pull request merged**
