### PR TITLE
Deny access to non-sql requests if authentication is enabled

### PR DESCRIPTION
**Pull request by mohitkhullar**
Signed-off-by: mohitkhullar <mkhullar1@bloomberg.net>

### CODE REVIEW

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: <b>3/429 tests failed</b> &#x26A0;.</p><p>The first 10 failing tests are: <br>sc_truncate_lockorder_generated [core dumped]<br>socksql_master_swings<br>sp_snapshot_generated</p>

**Review by nirbhayc — DISMISSED** [review]

**Review by aakash10292 — COMMENTED** [review]
Can haz a test?

**Comment by mohitkhullar** [comment]
example trace 
[insert into t(a,b) values(1,2)] failed with rc 100 Tag access denied for table t from SRMT# sundev2 PID 049921

**Review by mponomar — COMMENTED** [review]
Hate to ask - but we should probably have an option to disable?

**Comment by mohitkhullar** [comment]
added allow_unauthenticated_tag_access

**Comment by mohitkhullar** [comment]
$ comdb2sql -comdb2 mohitdb1 "insert into t(a,b) values(1,2)"
[insert into t(a,b) values(1,2)] failed with rc 100 Tag access denied for table t from SRMT# <hidden> PID 062225

 $ comdb2sql mohitdb1 "put tunable allow_unauthenticated_tag_access 'on'"

 $ comdb2sql -comdb2 mohitdb1 "insert into t(a,b) values(1,2)"
(.n_writeops_done=1)

**Review by roborivers — COMMENTED** [review]
Lint check:

```diff


@@ db/db_tunables.h @@
+ Please update the tunable documentation (docs/pages/config/config_files.md) accordingly.
```

**Comment by mohitkhullar** [comment]
Thanks

**Pull request merged**
