### PR TITLE
double check for error when IO error

### PR DESCRIPTION
**Pull request by dorinhogea**
Signed-off-by: Dorin Hogea <dhogea@bloomberg.net>

Double check for error.

### CODE REVIEW

**Review by roborivers — APPROVED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: Success &#10003;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p>The first 10 failing tests are: <br>ioerror_remsql [core dumped]</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/27d47f9/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/27d47f9/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2487'>Resubmit</a></p>

**Review by mponomar — APPROVED** [review]

**Comment by dorinhogea** [comment]
FTR: this is the design decision handling failures while reading remote index stats.
There are two choices if we miss some stats: 
1) hard failure with client error, or 
2) spew alerts and run anyway (potentially getting slow plans due to missing stats). Some queries will run with little performance penalty/

The design chose to be potentially slow instead of hard client failure.

This is the failure protocol:
- Code retries 3 times to get each stat table (1, then 4).
- For each retry, we try 16 times to properly open a cursor to a remote cluster, hopping from replicant to replicant if they fail to answer.
This process fails as follow:
- if stat1 fails to complete, stat4 is skipped
- if we retrieve some stat1 stats, we keep them and proceed to stat4, leaving us with partial stats
- if we completely failed to retrieve any stats, we keep empty local stats cache to avoid every query from repeating the stats acquisition process.

**Review by roborivers — CHANGES_REQUESTED** [review]
<p><a href='https://bloomberg.github.io/comdb2/contrib.html#code-style'>Coding style</a> check: <b>Error</b>. <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/formatting-a-pr.html'>Use clang-format</a> or <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/685abe4/format.diff'>view diff</a> &#x26A0;.<br>Smoke testing: Success &#10003;.<br>Cbuild submission: Success &#10003;.<br>Regression testing: Success &#10003;.</p><p><a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/685abe4/detail.txt'>Detail</a> | <a href='http://comdb2.s3-website-us-east-1.amazonaws.com/tests/685abe4/logs.tar.gz'>Log</a> | <a href='http://ec2-34-202-216-70.compute-1.amazonaws.com/restricted/index.php?id=2487'>Resubmit</a></p>

**Comment by dorinhogea** [comment]
Thanks Mike

**Pull request merged**
